samvera/hyku

.rubocop.yml
app/controllers/curation_concerns/generic_works_controller.rb
app/forms/curation_concerns/generic_work_form.rb
app/models/solr_document.rb

Better rubocop

---

app/assets/stylesheets/application.css
app/controllers/application_controller.rb
config/settings.yml
config/settings/production.yml
spec/requests/home_spec.rb

This may make it easier to develop and test against the application.

Disable multitenancy for non-production environments

---

app/controllers/roles_controller.rb
app/models/role.rb
app/models/user.rb
app/views/_toolbar.html.erb
app/views/roles/index.html.erb
config/routes.rb
spec/controllers/roles_controller_spec.rb
spec/features/roles_spec.rb
spec/models/role_spec.rb
spec/models/user_spec.rb
spec/routing/roles_routing_spec.rb

Incredibly not-awesome, but it might let us punt better role management for later.

Roles editor

---

app/controllers/sites_controller.rb
app/helpers/sufia_helper.rb
app/models/site.rb
app/views/sites/_form.html.erb
config/locales/en.yml
db/migrate/20160411212338_add_institution_name_to_site.rb
db/schema.rb
spec/controllers/sites_controller_spec.rb
spec/features/site_spec.rb
spec/views/sites/edit.html.erb_spec.rb

Add configuration settings for the institution name

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.css
app/controllers/admin/features_controller.rb
app/controllers/admin/strategies_controller.rb
app/models/feature.rb
app/views/_toolbar.html.erb
config/initializers/feature.rb
config/routes.rb
db/migrate/20160415212015_create_features.rb
db/schema.rb

Add 'flip' for dynamically toggling features on and off

---

app/controllers/accounts_controller.rb
app/controllers/application_controller.rb
app/models/account.rb
app/models/endpoint.rb
app/models/solr_endpoint.rb
app/views/accounts/_form.html.erb
config/initializers/apartment.rb
db/migrate/20160414155644_create_endpoints.rb
db/migrate/20160414155816_add_solr_endpoint_to_account.rb
db/schema.rb
spec/controllers/accounts_controller_spec.rb
spec/features/accounts_spec.rb
spec/models/account_spec.rb
spec/models/solr_endpoint_spec.rb

Add SolrEndpoint configuration to allow accounts to point at different solr urls

---

app/controllers/accounts_controller.rb
app/models/account.rb
app/models/fcrepo_endpoint.rb
app/views/accounts/_form.html.erb
db/migrate/20160414155816_add_solr_endpoint_to_account.rb
db/migrate/20160419214433_add_fcrepo_endpoint_to_account.rb
db/schema.rb
spec/controllers/accounts_controller_spec.rb
spec/features/accounts_spec.rb
spec/models/account_spec.rb
spec/models/fcrepo_endpoint_spec.rb
spec/models/solr_endpoint_spec.rb

Add FcrepoEndpoint model for Fedora connections

---

.solr_wrapper
Gemfile
Gemfile.lock
app/controllers/accounts_controller.rb
app/jobs/create_solr_collection_job.rb
app/models/account.rb
app/models/solr_endpoint.rb
app/services/create_account.rb
app/services/solr_config_uploader.rb
config/settings.yml
config/settings/test.yml
config/solr.yml
lib/tasks/zookeeper.rake
spec/controllers/accounts_controller_spec.rb
spec/features/accounts_spec.rb
spec/jobs/create_solr_collection_job_spec.rb
spec/middleware/account_elevator_spec.rb
spec/models/account_spec.rb
spec/rails_helper.rb
spec/services/create_account_spec.rb
spec/services/solr_config_uploader_spec.rb

Create a new solr collection when creating an account

---

app/controllers/accounts_controller.rb
app/jobs/cleanup_account_job.rb
app/models/account.rb
app/models/fcrepo_endpoint.rb
app/models/solr_endpoint.rb
spec/controllers/accounts_controller_spec.rb
spec/jobs/cleanup_account_job_spec.rb
spec/models/account_spec.rb

Clean up the fedora base path and solr collection when an account is deleted

---

config/settings.yml

Pending a native approach offered by e.g. https://github.com/railsconfig/config/pull/125

Explicitly use environment variables for application settings

---

.ebextensions/sidekiq.config

Hopefully this is only temporary, until we migrate to SQS, worker environments, and shared storage..

Add .ebextension to launch the sidekiq process on the webapp boxes

---

.ebextensions/install.config

Hopefully this is also temporary, until we decide how to handle the first run experience (probably poking actions through the UI)?.

Run the zookeeper:upload rake task when spinning up a new or updated instance

---

app/views/_toolbar.html.erb
config/initializers/stats_admin.rb
config/routes.rb

Clearing the path forward for making the administrative stats page visible in HyBox on AWS.

Nuke notifications in dashboard dropdown

---

.rubocop.yml
app/actors/curation_concerns/actors/generic_work_actor.rb
spec/actors/curation_concerns/actors/generic_work_actor_spec.rb

Tracking change in curation_concerns 1.0.0.beta2
https://github.com/projecthydra-labs/curation_concerns/commit/502138bf4c55002797b6a6849fb4f4f7b6a2bf66

Move actor to the correct namespace

---

solr/config/solrconfig.xml

This lets us make use of the Admin Stats feature from Sufia.

Enable the TermsComponent in Solr.

---

Gemfile.lock
config/initializers/sufia.rb

This fixes the problem where uploaded files were not being characterized.

Update to latest version of sufia + CC 1.0.0.beta3

---

Gemfile
Gemfile.lock
app/controllers/curation_concerns/generic_works_controller.rb
app/presenters/concerns/displays_image.rb
app/presenters/curation_concerns/generic_work_show_presenter.rb
app/presenters/hybox/file_set_presenter.rb
spec/presenters/curation_concerns/generic_work_show_presenter_spec.rb
spec/presenters/hybox/file_set_presenter_spec.rb

Updates to use projecthydra/curation_concerns#806
Fixes #179

Presenters have a request by default

---

Gemfile.lock

Update riiif to support redirecting with encoded slashes

---

Gemfile
Gemfile.lock

It'll work this time. I promise.

Update RIIIF ... again

---

app/controllers/application_controller.rb
config/settings.yml
spec/controllers/splash_controller_spec.rb
spec/requests/home_spec.rb

Other uris without account should be 404.

Only redirect to the splash page on the root uri.

---

config/initializers/simple_form.rb
config/initializers/simple_form_bootstrap.rb

Update to template shipping with current version of curation_concerns

---

README.md

Remove stale sidekiq reference from README

---

app/assets/stylesheets/lerna.scss

Bring back the cloud

---

app/controllers/accounts_controller.rb
spec/controllers/accounts_controller_spec.rb

Don't use the admin layout for new users

---

app/controllers/accounts_controller.rb
spec/controllers/accounts_controller_spec.rb

Authorize Accounts#index to the superadmin

---

app/controllers/roles_controller.rb
spec/controllers/roles_controller_spec.rb

Exclude guest users from the role page.

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.css

Install datatable assets.

---

app/controllers/account_sign_up_controller.rb
app/controllers/accounts_controller.rb
app/views/account_sign_up/new.html.erb
app/views/splash/index.html.erb
config/routes.rb
spec/controllers/account_sign_up_controller_spec.rb
spec/controllers/accounts_controller_spec.rb
spec/features/splash_spec.rb
spec/views/account_sign_up/new.html.erb_spec.rb

Extract new account sign up controller

---

app/controllers/curation_concerns/file_sets_controller.rb
spec/factories/generic_works.rb
spec/features/edit_file_spec.rb

Add sufia behavior to FileSetController

---

app/controllers/accounts_controller.rb
spec/controllers/accounts_controller_spec.rb

The public functionality moved to AccountSignUpController in
https://github.com/projecthydra-labs/lerna/pull/344
Fixes #328 (again)

Disallow public users on AccountsController

---

db/migrate/20160328222236_change_trophy_generic_file_id_to_work_id.sufia.rb
db/migrate/20160328222237_change_proxy_deposit_generic_file_id_to_work_id.sufia.rb
db/migrate/20160328222239_change_proxy_deposit_request_generic_file_id_to_work_id.sufia.rb
db/migrate/20160510000007_change_featured_work_generic_file_id_to_work_id.sufia.rb

See https://github.com/projecthydra/sufia/blob/master/db/migrate/20160328222236_change_trophy_generic_file_id_to_work_id.rb

Fix migration to match what exists in Sufia

---

.rubocop_todo.yml
app/controllers/content_blocks_controller.rb
app/models/content_block.rb
app/models/lerna/content_block_behavior.rb
app/models/site.rb
app/views/content_blocks/edit.html.erb
app/views/pages/show.html.erb
spec/controllers/content_blocks_controller_spec.rb
spec/features/content_blocks_spec.rb
spec/models/content_block_spec.rb
spec/views/content_blocks/edit.html.erb_spec.rb
spec/views/pages/show.html.erb_spec.rb

Move the about page editor to the content block editors screen.

---

app/models/lerna/content_block_behavior.rb
spec/models/content_block_spec.rb

Make ContentBlocks set a site_id by default.

---

app/controllers/curation_concerns/admin_controller.rb
app/views/sufia/admin/_sidebar.html.erb
spec/features/admin_dashboard_spec.rb

Ran `rails generate curation_concerns:admin_dashboard`
This prevents a `uninitialized constant CurationConcerns::AdminController` when going to `/admin`

Generated the curation_concerns dashboard

---

app/assets/stylesheets/lerna.scss
app/views/sufia/admin/_sidebar.html.erb

Improve admin sidebar styling

---

app/controllers/application_controller.rb
app/controllers/status_controller.rb
app/models/account.rb
app/models/fcrepo_endpoint.rb
app/models/redis_endpoint.rb
app/models/solr_endpoint.rb
app/views/status/_service.html.erb
app/views/status/index.html.erb
app/views/sufia/admin/_sidebar.html.erb
config/locales/en.yml
config/routes.rb
spec/features/admin_dashboard_spec.rb
spec/models/fcrepo_endpoint_spec.rb
spec/models/redis_endpoint_spec.rb
spec/models/solr_endpoint_spec.rb

Add a simple service status page to the admin dashboard

---

config/initializers/redis_config.rb
config/initializers/sidekiq.rb
config/redis.yml

This reverts commit 2691cde5108f68878dc21443ff02bf57d5227cd0.

Revert "Add Redis sentinel clustering configuration"

---

db/migrate/20161115142213_create_permission_template.sufia.rb
db/migrate/20161115142214_create_permission_template_access.sufia.rb
db/schema.rb

Add the PermissionTemplate tables

---

db/migrate/20161202201717_add_release_to_permission_templates.sufia.rb
db/migrate/20161202202255_add_label_to_sipity_workflows.rb
db/migrate/20161202202754_change_sipity_entity_workflow_state_to_null.rb

the change do db/schema.rb has already been merged to master, but these belong with it.

Add the missing migrations that were used to create db/schema.rb

---

Gemfile.lock

Update to latest version of Hyrax

---

app/controllers/status_controller.rb
app/views/status/index.html.erb

System status page should appear like other admin pages

---

app/models/account.rb
spec/models/account_spec.rb

Automatically load workflows when switching accounts

---

Gemfile.lock

Update blacklight and active_fedora-noid

---

app/models/account.rb
app/services/create_account.rb
spec/models/account_spec.rb
spec/services/create_account_spec.rb

Load workflows in CreateAccount

---

Gemfile.lock

Pull in changes that fix routing errors for collections on atom feed.

Update version of hyrax

---

app/views/hyrax/base/show.html.erb
app/views/shared/_footer.html.erb

Update view overrides with latest from Hyrax, taking care not to rollback our druthers

---

config/database.yml

Set the pool to be equal to the number of incoming connections so we
don't get timeout errors waiting on a connection. Fixes #622

Expand the database connection pool

---

app/services/create_account.rb
spec/services/create_account_spec.rb

Create workflows in the tenant schema when account is created.

---

solr/config/solrconfig.xml

Set lucene to match version of solr

---

Gemfile.lock

```console
$ bundle update solr_wrapper
```

Updating solr_wrapper dependency

---

.gitignore

These are generated when developing according to the steps in README.

Ignore postgres artifacts

---

Gemfile
Gemfile.lock

Use a thread-safe version of ActiveFedora

---

README.md

Also added command to start sidekiq

DISABLE_REDIS_CLUSTER

---

lib/active_job_tenant.rb

This will give us more useful data when there is a fault in honeybadger.

Add the job data to the honeybadger context

---

Gemfile
Gemfile.lock

Refers to brigade/scss-lint#278
Fixes random appearance of **Undefined method "bubbles"**  

Fix error with undefined method 'bubbles'

---

Gemfile.lock
config/routes.rb

Mount QuestioningAuthority

---

app/controllers/catalog_controller.rb

Search descriptions, creators and keywords

---

app/models/user.rb

Cleaning up the User class a bit.

Remove duplicate include

---

Gemfile.lock

Update LDP and other dependencies

---

lib/stanford/importer/purl_retriever.rb

Raise an error when this happens.
Fixes #621
Fixes #752

Detect 404s from Stanford's PURL service

---

README.md

Link to Development Guide wiki page

---

Gemfile.lock
db/migrate/20170217164907_add_workflow_id_to_permission_template.rb
db/schema.rb
lib/importer/factory/object_factory.rb
spec/jobs/import_work_from_purl_job_spec.rb
spec/rails_helper.rb

Update hyrax and other dependencies

---

config/initializers/carrierwave_config.rb

See https://github.com/carrierwaveuploader/carrierwave/pull/1201/files
Fixes #805 🤞

Don't set storage = :fog until that adapter has been loaded

---

Gemfile.lock
config/locales/hyrax.en.yml
config/locales/hyrax.es.yml

Refs https://github.com/projecthydra-labs/hyrax/issues/404

Update Hyrax. Set default institution_name to "institution"

---

app/controllers/content_blocks_controller.rb
app/models/hyku/content_block_behavior.rb
app/models/site.rb
app/views/content_blocks/_form.html.erb
app/views/hyrax/admin/_sidebar.html.erb
spec/controllers/content_blocks_controller_spec.rb
spec/models/content_block_spec.rb
spec/views/content_blocks/edit.html.erb_spec.rb

Also fixed editable blocks since TinyMCE is now loaded by hyrax in the header
Fixes #516

Add an editable "Help Page" block to the admin menu

---

app/controllers/admin/groups_controller.rb

To resolve an error honeybadger just caught in the AWS environment.

Extending what @jcoyne did in #844 to other group controller

---

app/controllers/admin/group_users_controller.rb
app/controllers/admin/groups_controller.rb
config/locales/en.yml
config/locales/es.yml

Fixes https://github.com/projecthydra-labs/hyrax/issues/467

Add breadcrumbs to group pages

---

db/migrate/20170320131133_tidy_up_because_of_bad_exception.hyrax.rb
db/schema.rb

@1263ed5ae718723bf92e081369a1095ba391e69a
```console
$ rake hyrax:install:migrations
```
@7d87c8e40bc38c1e683fe72ec171a5a0cce5323c
Making a localized tweak; not certain how things got out of sync.
```console
$ rake db:migrate
```

Updating hyku migrations

---

Gemfile.lock
db/migrate/20170320135902_add_allows_access_grant_to_workflow.hyrax.rb
db/schema.rb

CVE-2016-4658 and CVE-2016-5131

Update gems. Addresses Nokogiri security issues

---

.ebextensions/logzio.config

Installs Filebeat (https://www.elastic.co/products/beats/filebeat) via Elastic Beanstalk extentions for shipping logs to logz.io.

Adds config for log capture via logz.io

---

app/assets/stylesheets/variables.scss

This matches the designs in https://ggeisler.github.io/lerna-dashboard/index.html

Make the navbar smaller. Fixes #891

---

app/views/hyrax/dashboard/_sidebar.html.erb
config/locales/en.yml
config/locales/es.yml
spec/presenters/hyku/menu_presenter_spec.rb

Also moved "Workflow roles" into the Configuration section
Fixes #910

Remove duplicate "Review Submissions" menu link

---

config/application.rb

Fixes #917
Fixes #875
Fixes #873
Fixes #868
Fixes #767

Render the not found page if I18n::InvalidLocale is rescued

---

app/presenters/hyku/menu_presenter.rb
app/views/hyrax/dashboard/_sidebar.html.erb
spec/presenters/hyku/menu_presenter_spec.rb

Sidebar expand/collapse memory

---

app/services/iiif_thumbnail_path_service.rb
spec/services/iiif_thumbnail_path_service_spec.rb

This is closer to the size we are actually displaying it at.

Use a more appropriate thumbnail size

---

app/presenters/hyku/menu_presenter.rb
app/views/hyrax/dashboard/_sidebar.html.erb
spec/presenters/hyku/menu_presenter_spec.rb

Don't show the empty settings menu

---

app/views/hyrax/base/_representative_media.html.erb

Ref https://github.com/projecthydra-labs/hyrax/issues/392
Fixes #933

Use the correct canonical image

---

app/presenters/hyku/menu_presenter.rb
app/views/hyrax/dashboard/_sidebar.html.erb
spec/presenters/hyku/menu_presenter_spec.rb

Don't show the tasks section to depositors

---

config/application.rb

This reverts commit 67144da2b99f07ddc82bfb06056da556296de2c3.
Fixes #947

Revert "Temporarily turn off the rescuing of not found exceptions"

---

app/views/hyrax/dashboard/_sidebar.html.erb

Push configuration to the bottom as it's the least used.
Fixes #900

Reorder the left sidebar menu

---

app/forms/hyrax/image_form.rb
app/models/image.rb
config/locales/hyrax.en.yml
config/locales/hyrax.es.yml

Fixes #877
Adds dc extent field to image works.

Adds dc term extent to image works.

---

config/application.rb
config/initializers/hyrax.rb

Otherwise we were seeing Devise raising invalid authenticity tokken
errors

Do dependency injection after classes have loaded

---

Gemfile.lock

http://www.mikeperham.com/2017/04/25/hello-sidekiq-5.0/

Update sidekiq to 5.0

---

db/seeds.rb

Create default admin set and workflows when bin/setup is run

---

app/controllers/admin/accounts_controller.rb

`before_action :ensure_admin!` is already part of `AdminController`.

Remove redundant action

---

app/views/shared/_footer.html.erb
config/initializers/version.rb
spec/features/splash_spec.rb
spec/lib/hyku_spec.rb
spec/support/matchers.rb

This is a minor change but I wanted to bring it to your attention, @hannahfrost @ggeisler @bbranan.

Add version to Hyku and display in footer

---

app/jobs/import_work_from_purl_job.rb

To track
https://github.com/projecthydra-labs/hyrax/commit/f59d048cb30b44c72c1b68c50f30c266266f8f30

Change rights to license

---

config/database.yml

Avoids conflicts in postgres database when developing multiple applications on the same postgres system (only applies to test and development).

config/database.yml - use a "hyku_*" namespace

---

app/views/account_sign_up/new.html.erb
app/views/proprietor/accounts/new.html.erb
db/migrate/20170502000659_remove_title_from_accounts.rb
db/schema.rb
spec/models/account_spec.rb
spec/services/create_account_spec.rb
spec/views/account_sign_up/new.html.erb_spec.rb
spec/views/proprietor/accounts/new.html.erb_spec.rb

Remove unused "title" field from accounts

---

config/blacklight.yml

Compare to:
- solr.yml, and
- https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/templates/config/blacklight.yml

Support SOLR_URL in all 3 modes

---

docker-compose.yml

Remove environment quotes to fix problem with newer docker engines

---

config/database.yml

We don't use sqlite here, even in development.

Trim comment

---

Gemfile.lock

Update Hyrax. Fixes #1040.

---

app/presenters/hyku/menu_presenter.rb
app/views/hyrax/dashboard/_sidebar.html.erb
spec/presenters/hyku/menu_presenter_spec.rb

Only show system status menu item to admins

---

config/locales/blacklight.zh.yml
config/locales/devise.zh.yml
config/locales/en.yml
config/locales/generic_work.zh.yml
config/locales/hyrax.zh.yml
config/locales/image.zh.yml
config/locales/simple_form.zh.yml
config/locales/zh.yml

Add missing Chinese translations

---

Gemfile.lock

Update Hyrax to pick up commit w/ fix to FileSet labels

---

docker-compose.base.yml
docker-compose.yml

fcrepo runs on port 8080 in docker

---

config/workflows/mediated_deposit_workflow.json

Fixes https://github.com/projecthydra-labs/hyrax/issues/856

Update Hyku workflow to match Hyrax

---

app/indexers/work_indexer.rb
spec/indexers/work_indexer_spec.rb

Fixes #1023 
Index descriptive metadata like the hyrax work generator does.

Restores indexing of descriptive metadata.

---

Gemfile.lock
config/workflows/mediated_deposit_workflow.json

Update Hyrax and reflect changes to workflow json

---

app/jobs/create_account_inline_job.rb
app/jobs/create_default_admin_set_job.rb
app/services/create_account.rb
config/initializers/apartment.rb
spec/jobs/create_account_inline_job_spec.rb
spec/jobs/create_default_admin_set_job_spec.rb
spec/services/create_account_spec.rb

Address error during account creation. 
See: https://app.honeybadger.io/projects/48327/faults/33545313#notice-trace

Change acct creation steps order and in-linedness

---

app/actors/hyrax/actors/image_actor.rb
app/controllers/catalog_controller.rb
app/controllers/hyrax/images_controller.rb
app/forms/hyrax/image_form.rb
app/indexers/image_indexer.rb
app/models/image.rb
app/models/solr_document.rb
app/presenters/hyku/manifest_enabled_work_show_presenter.rb
app/presenters/hyrax/image_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
config/initializers/hyrax.rb
config/locales/blacklight.en.yml
config/locales/blacklight.es.yml
config/locales/blacklight.zh.yml
spec/actors/hyrax/actors/image_actor_spec.rb
spec/controllers/hyrax/images_controller_spec.rb
spec/features/create_image_spec.rb
spec/forms/hyrax/image_form_spec.rb
spec/models/image_spec.rb
spec/presenters/hyrax/image_presenter_spec.rb

Add extent field to show page

---

Gemfile
Gemfile.lock

Revert part of 918ccaed0828ba5d963046ba1511667f4fd7d7b0
Hopefully this gets our jobs running again.
Ref #1100

Go back to active elastic job 1.7

---

config/application.rb

This may help reveal why jobs are failing.

Turn off ParseError handling

---

Gemfile
Gemfile.lock
app/jobs/cleanup_account_job.rb
app/jobs/create_account_inline_job.rb
app/jobs/create_fcrepo_endpoint_job.rb
app/jobs/create_redis_namespace_job.rb
app/jobs/create_solr_collection_job.rb
app/jobs/import_work_from_purl_job.rb
app/services/create_account.rb
config/application.rb
config/environments/production.rb
config/initializers/apartment_activejob.rb
config/settings/test.yml
lib/active_job/queue_adapters/better_active_elastic_job_adapter.rb
lib/active_job_tenant.rb
spec/controllers/account_sign_up_controller_spec.rb
spec/factories/accounts.rb
spec/features/create_tenant_spec.rb
spec/jobs/create_account_inline_job_spec.rb
spec/jobs/create_fcrepo_endpoint_job_spec.rb
spec/jobs/create_redis_namespace_job_spec.rb
spec/lib/active_job_tenant_spec.rb
spec/services/create_account_spec.rb

Update active-elastic-job to 2.0 and fix tenant jobs

---

db/migrate/20170524170114_change_checksum_audit_log.hyrax.rb
db/schema.rb

Add missing migration from hyrax

---

.ebextensions/fits.config

Downgrade FITS to 1.0.5. Fixes #1175

---

config/initializers/hyrax.rb

Disable BrowseEverything temporarily.

---

docker-compose.yml

Share the uploads directory between the web and workers

---

docker-compose.yml

Set the path for fits in docker

---

Dockerfile

Add ghostscript to docker build for PDF/etc. derivatives

---

Gemfile.lock
app/jobs/import_work_from_purl_job.rb

Don't rely on Hyrax::Configuration#model_to_create
Fixes #1220

Update hyrax and dependencies

---

lib/importer/factory/object_factory.rb

Add a note about a broken method

---

db/schema.rb

A migration was added in
https://github.com/samvera-labs/hyku/commit/da41e1a13f18c0d72d76dd526ef65e8a8a9c0f52
but the schema change was not checked in.

Run migrations to update schema

---

app/views/hyrax/admin/appearances/show.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/it.yml
config/locales/pt-BR.yml
config/locales/zh.yml

Update and i18nize hint text for banner image 

---

docker-compose.yml

Inspired by
https://github.com/docker/compose/issues/1393#issuecomment-99988242
Fixes #1261

Clear the puma pidfile when docker restarts

---

Gemfile.lock

Update hydra-derivatives and other dependencies

---

Gemfile.lock

Update hyrax and rdf-xsd

---

Gemfile.lock

Update riiif to fix caching bug

---

app/models/nil_endpoint.rb
app/models/nil_fcrepo_endpoint.rb
app/models/nil_solr_endpoint.rb
spec/models/nil_fcrepo_endpoint_spec.rb
spec/models/nil_solr_endpoint_spec.rb
spec/views/proprietor/accounts/edit.html.erb_spec.rb

Allow edit account page to show NilConnections

---

app/presenters/concerns/displays_image.rb
spec/presenters/hyku/file_set_presenter_spec.rb

See PR #1326 ... trying a new PR as I think my failures are due to the original PR coming from a fork rather than a branch.

Fix for #1171 - only include images in the IIIF Manifest

---

config/initializers/carrierwave_config.rb

No longer needed for anything.

Remove config initializer line for `fog_provider`

---

app/jobs/cleanup_account_job.rb
app/models/fcrepo_endpoint.rb
app/models/nil_endpoint.rb
app/models/nil_redis_endpoint.rb
app/models/redis_endpoint.rb
app/models/solr_endpoint.rb

Fixes #1351
This is an alternative to #1387  What do you think @tdonohue?

Allow tenants with NilEndpoints to be deleted

---

.rubocop.yml
lib/tasks/grant_superadmin.rake
lib/tasks/user.rake
spec/tasks/rake_spec.rb

Add a rake task to create a superadmin

---

Gemfile
Gemfile.lock

Use upstream Config gem instead of mjgiarlo branch

---

bin/graph

I don't know if this belongs here.  I'm not eager to force users to install graphviz just for this tool they may or may not use.  Maybe this should be an external gem?

Tool for visualizing workflows

---

Gemfile.lock

To fix latest security vulnerability.

Update sprockets (security vulnerability)

---

Gemfile
Gemfile.lock

Update iiif_manifest to 0.5.0

---

Gemfile.lock

Fixes error with ruby 2.5.* https://github.com/plataformatec/devise/issues/4736 mentioned in #1544

Update devise 

---

app/views/hyrax/base/_representative_media.html.erb

UV data-uri needs full URI otherwise the embed code won't work on other sites

Use polymorphic_url instead of _path for UV data-uri 

---

Dockerfile

Update Ruby to latest version 2.5.3.

Ruby 2.3.1 -> 2.5.3

---

Gemfile.lock

Update loofah and rack

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SUPPORT.md

Updated:
* CONTRIBUTING
* README (added badges for docs, added product owner, added toc and a few other changes)
Added:
* CODE-OF-CONDUCT
* SUPPORT

For promotion out of labs

---

Gemfile
Gemfile.lock

Update nokogiri to 1.10.1

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.css
app/controllers/application_controller.rb
app/models/ability.rb
app/views/_masthead.html.erb
config/initializers/peek.rb
config/routes.rb

Fixes #1565 
Peek is basically unmaintained and most hyku users don't seem to benefit from this.

Remove Peek

---

Gemfile.lock

Simple fix for bootstrap-sass version issue. https://github.com/samvera/hyku/network/alerts

update bootstrap sass to fix vulnerability

---

docker-compose.production.yml
docker-compose.yml

Fixes #1583 
Lock docker versions to make local and production runs more consistent.

lock versions of docker dependencies to known working versions

---

.circleci/config.yml
Gemfile.lock
config/initializers/version.rb

Nokogiri has a security issue, this bump fixes it.  We also are nearing a 2.1 release which will bring Hyku up to Hyrax 2.5.1.  Lastly I'm still trying to con coveralls and circle in to getting along.

bump nokogiri version, prep new release, try and fix coveralls

---

Dockerfile.base

Fixes #1569 
Re-enable PDFs in ImageMagick in the Docker images.

pdf thumbnail fix

---

Gemfile.lock

This includes a fix for multi-tenant apps which was causing frequent logouts for admins and updates to BagIt and CSV parsers.

update to the latest bulkrax

---

app/controllers/labels_controller.rb
app/controllers/proprietor/accounts_controller.rb
app/forms/appearance_form.rb

Favoring "permitted" instead of "white list"

Rewording documentation to improve accessibility

---

.github/PULL_REQUEST_TEMPLATE.md

Change PR template call out

---

app/models/user.rb
db/schema.rb
spec/models/ability_spec.rb
spec/models/user_spec.rb
spec/requests/institution_visibility_spec.rb

Add a role to users when they register so that they can see institutional works. Also fleshed out the specs @cjcolvar started a little more.

Institution visibility with roles

---

Gemfile
Gemfile.lock
config/initializers/version.rb

See https://github.com/projectblacklight/blacklight_oai_provider/pull/28

Upgrade blacklight_oai_provider for visibility fix

---

README.md

Update instructions to include starting background workers

---

Gemfile
README.md
app/assets/javascripts/application.js
app/assets/stylesheets/application.css
config/initializers/bulkrax.rb

Fixed #1703 
Bulkrax was being loaded whether we meant to or not. It also was trying to compile in the assets all the time. This means that turning bulkrax on has an extra assets step, but at least does not throw an exception on boot.

Bulkrax optional fix

---

.env
Dockerfile
README.md
docker-compose.yml

bring docker-compose up to 3.8, fix worker not including fits.sh

---

README.md

This PR updates the README to include additional switch methods supplied in [PR#1705](https://github.com/samvera/hyku/pull/1705)
* Adds additional switch methods that were supplied in [PR#1705](https://github.com/samvera/hyku/pull/1705)
@orangewolf (In case you need to review)

Updates the README to include additional switch methods supplied in PR#1705

---

app/middleware/account_elevator.rb
app/models/concerns/account_switch.rb
config/application.rb

- made switch take account,cname or name
- include it in rails console
in Rails console
```
switch!(Account.first)
switch!('my.account.com')
switch!('myaccount')
```

make it easier to switch accounts

---

.gitignore
Dockerfile
README.md
app/models/concerns/account_switch.rb
db/schema.rb
docker-compose.override-nodory.yml
docker-compose.yml

Fixes zookeeper to solr connection and updates instructions for first time spin up of application.
* add ffmpeg package
* reduce ownership changes in Dockerfile
* updates solr volume
* removed db_migrate service
* adds first time spin up instructions to readme

Updates docker configuration for app start up

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/SUPPORT.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SUPPORT.md

Much thanks to @jthurner for the assistance.

Update links for Samvera wiki move

---

Dockerfile
Gemfile
Gemfile.lock
README.md
config/application.rb

Fixes #1714 
Conditionally have `Bundler` require the `bulkrax` gem group using the `ENV['SETTINGS__BULKRAX__ENABLED']` variable 
* Properly require the Bulkrax gem group conditionally 
* Update the version of Bulkrax to v1.0.1 
* Clarify documentation in README 

Fix Docker build when using Bulkrax. Update Bulkrax to v1.0.1

---

Dockerfile

Up hyrax base to v3.0.2 (latest)

---

config/authorities/licenses.yml

Updates the Creative Commons licenses to the most recent
BEFORE
AFTER
**_Code Contribution courtesy of Palni-Palci_**

Cc license update

---

app/models/concerns/account_settings.rb

This is a very small fix missing from #1749

small fixes for false booleans and smtp settings

---

.circleci/config.yml
Dockerfile
Gemfile.lock
app/models/account.rb
db/seeds.rb
spec/rails_helper.rb

single tenant seeds were broken by account validation

---

README Updated

Fixes #issuenumber ; refs #issuenumber
Present tense short summary (50 characters or less)
More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.
Description can have multiple paragraphs and you can use code examples inside:
``` ruby
class PostsController
def index
respond_with Post.limit(10)
end
end
```
*
*
*

updated hyku environment variables

---

Gemfile.lock
db/schema.rb

refs https://github.com/samvera/hyku/pull/1820
Updates schema and gemlock to include Bulkrax

update schema with bulkrax enabled

---

package.json
yarn.lock

BEFORE: 
AFTER:
ISSUE: 
command not found: shx

uv not rendering 

---

.gitlab-ci.yml
ops/staging-deploy.tmpl.yaml

ref: https://gitlab.com/notch8/utk-hyku/-/issues/103

make env vars consistent

---

.circleci/config.yml
.gitlab-ci.yml
ops/review-deploy.tmpl.yaml

First pass at some env variables that are lingering since removing
the settings gem as I go through Palni-Palci upgrade.

removing-lingering-settings-envs

---

app/helpers/blacklight/blacklight_helper_behavior.rb

fixes https://github.com/samvera/hyku/issues/1857

Backport fix from UTK

---

app/views/devise/shared/_links.html.erb

Ref #1879 
Follow up to #1880 (post-merge [feedback](https://github.com/samvera/hyku/pull/1880#discussion_r1061775987)) 

Remove unnecessary equality check

---

.env
Gemfile
Gemfile.lock
README.md
app/controllers/hyrax/contact_form_controller.rb
ops/review-deploy.tmpl.yaml
ops/staging-deploy.tmpl.yaml
spec/rails_helper.rb
spec/views/hyrax/contact_form/new.html.erb

Documentation: https://github.com/subwindow/negative-captcha
Contributing back the implementation of negative captcha from Palni-Palci's Hyku Upgrade.

Contributing back negative captcha

---

.github/workflows/build-test-lint.yaml
.github/workflows/deploy.yaml
bin/git-cleanup
ops/demo-deploy.tmpl.yaml
ops/iiif.tmpl.yaml

We want to deploy code automatically to the SoftServ stack. This will make testing easier, similar to how Nuerax functions for the Hyrax community.

working on automated deployment

---

.github/workflows/deploy.yaml
ops/demo-deploy.tmpl.yaml
ops/iiif-deploy.tmpl.yaml
ops/staging-deploy.tmpl.yaml

sentry and solr password, sentry environment

more deploy fixes

---

app/views/hyrax/admin/collection_types/_form_participants.html.erb
app/views/hyrax/batch_edits/_delete_selected.html.erb
app/views/hyrax/dashboard/collections/_form_share.html.erb
config/locales/hyrax.de.yml
config/locales/hyrax.en.yml
config/locales/hyrax.es.yml
config/locales/hyrax.fr.yml
config/locales/hyrax.it.yml
config/locales/hyrax.pt-BR.yml
config/locales/hyrax.zh.yml

Ref Ticket: https://github.com/scientist-softserv/palni-palci/issues/400
Updated to add locales for translations
Generated each of the translations

i400-gwr-translations

---

.github/workflows/base.yaml
.github/workflows/build-test-lint.yaml
.github/workflows/deploy.yaml

ref ticket: https://github.com/scientist-softserv/dev-ops/issues/526
Adds gha cool titles

i526-add-gha-cool-titles

---

config/initializers/version.rb

update Hyku::VERSION to 5.0.1

---

docker-compose.production.yml

Needs a few things
- check readme to see if it needs an update
- verify that this comes up first try from a clean env

bring back a production worthy docker-compose example

---

lib/tasks/reset.rake

Refs https://github.com/samvera-labs/bulkrax/issues/647
This task wraps Bulkrax's reset task and makes it work for all tenants. Waiting for https://github.com/samvera-labs/bulkrax/pull/648 to be merged and Bulkrax to be updated before we merge this.

add a reset task that wraps the task from bulkrax

---

Gemfile
Gemfile.lock

add `pry-byebug` for additional debugging options.

install pry-byebug

---

Gemfile.lock

This commit bumps bulkrax to pull in a small collection of bug fixes
ref
- https://github.com/samvera-labs/bulkrax/releases/tag/v5.4.0

upgrade bulkrax to 5.4.0

---

app/controllers/hyrax/my/works_controller_decorator.rb

Related to:
- https://github.com/samvera/hyku/pull/2023/files
- https://github.com/scientist-softserv/atla-hyku/pull/198

🐛 Fix bad method name

---

db/schema.rb

Updates to add schema changes after pulling locally and building and bringing the application up fully and running bundle/rails db:migrate

commit-schema-updates

---

app/assets/stylesheets/hyku.scss
app/views/splash/index.html.erb

This change was part of the bulk upgrade of Bootstrap 3 to 4.

🧹 Restore btn-sign-up on splash page

---

app/controllers/identity_providers_controller.rb
app/views/hyrax/dashboard/sidebar/_configuration.html.erb
app/views/identity_providers/_form.html.erb
app/views/identity_providers/index.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/it.yml
config/locales/pt-BR.yml
config/locales/zh.yml

Add or correct translations to handle "false" text due to missing.
Add breadcrumbs to index view.

🐛 Handle missing labels

---

config/initializers/version.rb

ref: 
- https://github.com/scientist-softserv/hykuup_knapsack/issues/96

update version to 6.0.0rc1

---

Gemfile
Gemfile.lock

Revert "knapsack gemfile additions or replacement"

---

Gemfile
Gemfile.lock

See inline documentation regarding purpose and intent of the hard-coded
branch logic.

🧹 Specify knapsack required branch

---

app/forms/roles_form_decorator.rb
app/models/generic_work_resource.rb
app/models/hyrax/administrative_set_decorator.rb
app/models/hyrax/pcdm_collection_decorator.rb
app/models/image_resource.rb
app/views/hyrax/dashboard/collections/_form_discovery.html.erb
config/initializers/hyrax.rb

The first pieces of work to get Collections working.

WIP to get collections & admin sets working

---

app/models/solr_endpoint.rb
config/initializers/hyrax.rb
config/initializers/riiif.rb
lib/wings/services/custom_queries/find_ids_by_model_decorator.rb
spec/features/collection_spec.rb
spec/features/oai_pmh_spec.rb
spec/models/account_spec.rb
spec/models/solr_endpoint_spec.rb
spec/rails_helper.rb
spec/requests/catalog_controller_spec.rb

Ideally the code would reference the SolrService in one manner.  This is
an effort to create an insulating layer around that.

♻️ Favor Hyrax::SolrService

---

app/models/generic_work.rb
app/models/generic_work_resource.rb
app/models/image.rb
app/models/image_resource.rb

Per Rob, remove HYKU_IIIF_PRINT conditional. Iiif print will be enabled by default.
Starting this PR so that we don't forget about it.

remove HYKU_IIIF_PRINT conditional

---

lib/tasks/index.rake

Related to:
- https://github.com/samvera/hyku/pull/2129

📚 Remove completed TODO item

---

Gemfile
Gemfile.lock
config/initializers/willow_sword.rb
config/routes.rb

This PR will introduce the [Willow Sword gem](https://github.com/CottageLabs/willow_sword/) and configure it to work with Valkyrie.  The gem we are using is a clone of the original from [Cottage Labs](https://github.com/CottageLabs/willow_sword)

🎁 Install and configure Willow Sword gem

---

config/environments/production.rb
ops/demo-deploy.tmpl.yaml
ops/staging-deploy.tmpl.yaml

This commit will add the HYRAX_VALKYRIE env var so Hyku will now use Valkyrie.  It will also add a HYKU_SHOW_BACKTRACE env var so that the backtrace will be shown on the staging server.

⚙️ Use valkyrie and show backtrace on staging

---

spec/rails_helper.rb

The current setting is too large to be useful.

change window size for selenium

---

package.json

This script checks if there are any files in the knapsack's config/uv/ directory and copies the files into the application's public/uv/ dir. This way we can have institution specific uv-config json files work in a knapsack application.

🎁 Modify yarn script to copy knapsack uv config

---

Gemfile
Gemfile.lock

We were getting dependency conflicts if doing a clean bundle install. This should fix it.

⬆️ Update googleauth

---

app/assets/stylesheets/hyku.scss
app/assets/stylesheets/themes/institutional_repository.scss
app/views/blacklight_range_limit/_range_limit_panel.html.erb
app/views/hyrax/admin/users/index.html.erb
app/views/themes/neutral_repository/layouts/_share_your_work_row.html.erb
config/locales/hyrax.de.yml
config/locales/hyrax.en.yml
config/locales/hyrax.es.yml
config/locales/hyrax.fr.yml
config/locales/hyrax.it.yml
config/locales/hyrax.pt-BR.yml
config/locales/hyrax.zh.yml

This PR has a few frontend fixes

Some frontend fixes

---

Gemfile.lock

https://github.com/scientist-softserv/iiif_print/releases/tag/v2.0.1

Update iiif print to 2.0.1

---

config/initializers/hyrax.rb

These need to be registered before use

add missing authorities

---

Gemfile.lock

Bring in changes for a new Hyrax config.
Ref:
- https://github.com/samvera/hyrax/commit/9d8d5f8dad116f9143e985e57ed26fd2543d4ec6

⬆️ Update Hyrax

---

Gemfile.lock
db/schema.rb

this pulls in valkryie support to handle the import of remote files.
Related issues: 
- https://github.com/scientist-softserv/hykuup_knapsack/issues/173
- https://github.com/scientist-softserv/adventist_knapsack/issues/723
- https://github.com/scientist-softserv/adventist_knapsack/issues/708

🧹 update bulkrax version

---

Gemfile.lock

This commit will bring in a fix with the service document.
Ref:
- https://github.com/scientist-softserv/willow_sword/commit/8fe4f5399fcbc783cab272ac6225fbd90702bd0b

⬆️ Update WillowSword

---

app/models/concerns/account_cname.rb
app/models/domain_name.rb

A refiling of https://github.com/samvera/hyku/pull/1654

Subdomains to exclude

---

config/application.rb

Fixes #issuenumber ; refs #issuenumber
Present tense short summary (50 characters or less)
More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.
Description can have multiple paragraphs and you can use code examples inside:
``` ruby
class PostsController
def index
respond_with Post.limit(10)
end
end
```
*
*
*

dont stop app start if goodjobs tables are not created yet

---

config/initializers/wings.rb

By setting `WINGS_CONCERNS` and using it we can make it simpler to set Wings and we can then use that set up to look them back up in reverse for the valkyrie adapter.

make initialization of wings simpler and make it easier to override

---

.github/workflows/build-test-lint.yaml

Fixes #issuenumber ; refs #issuenumber
Present tense short summary (50 characters or less)
More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.
Description can have multiple paragraphs and you can use code examples inside:
``` ruby
class PostsController
def index
respond_with Post.limit(10)
end
end
```
*
*
*

Update build-test-lint.yaml to allow step debugging

---

Gemfile.lock

ref:
- https://github.com/scientist-softserv/iiif_print/pull/374
Issue: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/856

update iiif_print for image progessing bug fix

---

app/assets/javascripts/application.js

bulkrax file uploads are broken

fix bulkrax file loader

---

.github/workflows/base.yaml
.github/workflows/build-test-lint.yaml
.github/workflows/deploy.yaml
Gemfile
Gemfile.lock
app/jobs/create_large_derivatives_job.rb
app/models/sushi.rb
app/models/sushi/platform_report.rb
app/presenters/hyrax/collection_presenter_decorator.rb
app/services/hyrax/work_uploads_handler_decorator.rb
app/services/iiif_print/tenant_config.rb
config/application.rb
spec/controllers/hyrax/homepage_controller_spec.rb
spec/features/feature_flag_spec.rb

renames all instances of scientist-softserv to notch8 due to company transition changes

:broom: renames scientst-softserv => notch8

---

Gemfile.lock

update bulkrax to v.9.0.2 to pull in fix for the importer edit form

update bulkrax to v9.0.2

---

Gemfile.lock

Update Bulkrax to fix a bug with import.
Ref:
- https://github.com/samvera/bulkrax/pull/1014

⬆️ Update Bulkrax

---

app/parsers/bulkrax/csv_parser_decorator.rb
lib/tasks/tenants.rake

Contributing back any changes from PALNI-PALCI repo from April to now.

I117 pals vs pals knapsack comp

---

Gemfile.lock
config/initializers/hyrax.rb
config/initializers/willow_sword.rb

This commit will update the WillowSword gem to bring in logic for the HykuCrossWalk.  We need to deglate the embargo and lease methods so that WillowSword can ask the object itself what those properties are instead of asking the embargo or lease object.
Ref:
- https://github.com/notch8/palni-palci/issues/1014
- https://github.com/notch8/willow_sword/pull/6

⬆️ Update WillowSword gem

---

Gemfile.lock

Pull in patches for pdf re-splitting and remote url bulkrax imports

Update hyrax, bulkrax, and iiif_print

---

Gemfile.lock
app/models/concerns/account_settings.rb

I was unable to start the application because of missing GA4 credentials. The application should still run even if these aren't set.

Ga4 follow up

---

Gemfile.lock

Issues and prior commits:
- https://github.com/notch8/palni_palci_knapsack/issues/247
- https://github.com/samvera/hyrax/issues/7028
- https://github.com/samvera/hyrax/pull/7039
- https://github.com/samvera/hyku/pull/2471

Update hyrax for finding sipity entity

---

.github/workflows/build-test-lint.yaml
Dockerfile
bin/bundle
bin/web
bin/worker
docker-compose.yml

Add app bin dir to path to make accessing commands more convenient

---

Dockerfile
docker-compose.yml

forces the PATH to a controlled setting that includes `hyrax-webapp/bin`

make the PATH part of the docker ENV

---

ops/staging-deploy.tmpl.yaml

fix redis for staging

---

app/controllers/catalog_controller.rb
app/models/concerns/account_settings.rb
config/locales/de.yml
config/locales/es.yml
config/locales/fr.yml
config/locales/hyrax.de.yml
config/locales/hyrax.es.yml
config/locales/hyrax.fr.yml
config/locales/hyrax.it.yml
config/locales/hyrax.pt-BR.yml
config/locales/hyrax.zh.yml
config/locales/it.yml
config/locales/pt-BR.yml
config/locales/simple_form.de.yml
config/locales/simple_form.en.yml
config/locales/simple_form.es.yml
config/locales/simple_form.fr.yml
config/locales/simple_form.it.yml
config/locales/simple_form.pt-BR.yml
config/locales/simple_form.zh.yml
config/locales/zh.yml
spec/models/concerns/account_settings_spec.rb

<details><summary>search result</summary>
</details>
<details><summary>setting</summary>
</details>
<details><summary>search result</summary>
</details>

Add Account setting to exclude chosen fields from search results page

---

Gemfile.lock

Refs https://github.com/samvera/bulkrax/issues/1027
Brings in relationship job fixes.

Bring in bulkrax's relationship fixes

---

Gemfile.lock

Ref:
- https://github.com/notch8/hykuup_knapsack/issues/383
- https://github.com/notch8/hykuup_knapsack/issues/388
- 383 - Code syntax showing on new work modal
- 388 - Keep chunk uploading in sync when multi processes are involved
Updates Hyrax SHA for 5.0-flexible branch.
`bundle update hyrax --conservative`

⚙️ Updating Hyrax to the latest commit

---

Gemfile.lock

- https://github.com/samvera/hyrax/commit/2567adeaca68ea6c60f5fccd6dd8b1c0261a9bc2
Issue: 
- https://github.com/notch8/hykuup_knapsack/issues/442

:bug: updates hyrax to pull in delete bug fix

---

.github/workflows/build-test-lint.yaml
.github/workflows/release.yml
Dockerfile
docker-compose.yml

remove the hyku base to cut build times and complexity

🥳 hyrax base now has parity with the hyku base again!

---

.github/workflows/build-test-lint.yaml
.github/workflows/release.yml
Dockerfile
docker-compose.yml

Backport Base removal to 6.1 

---

app/assets/stylesheets/hyku.scss
app/views/hyrax/base/_form_share.html.erb

Fixes #2541 ; Ref #2542
Fixes the styling of the statuses on the permission form page (work edit tab)
Fixes the advanced search formatting

6.1 lightning round

---

ops/iiif-deploy.tmpl.yaml
ops/iiif.tmpl.yaml
ops/staging-deploy.tmpl.yaml

ref # https://github.com/notch8/dev-ops/issues/957
Update the nginx bitnami image

Update the bitnami-nginx image

---

docs/getting-started.md

The goal of this change is to provide a clear happy path for developers to get a Hyku development environment running using Docker.
This change intentionally moves or removes advanced options that are not essential for setting up a basic sandbox environment.
Changes
* Remove references to production docker-compose setup in development section
* Remove obsolete instructions for fixing docker groups
* Update release tag for checkout to v6.2.0
* Emphasize Stack Car as happy path for DNS/TLS
* Moved all optional setup and config information to it's own section
* Added initial troubleshooting section
* [Temporary] Remove testing instructions since they fail
TODO: diagnose why local testing is not working, fix, and add appropriate instructions.

Streamline Getting Started docs

---

Gemfile.lock

Brings in bug fixes for exporter

Updates bulkrax

---

Gemfile.lock

ref:
- https://github.com/samvera/hyrax/commit/bae59673f355479b9bf69a044096d0bd83c3a059

adds warning description to batch uploads for 6.2

---

config/initializers/console.rb

I just can't take it any more... I keep forgetting.

loading message about account switching

---

Gemfile
Gemfile.lock

Update gemfile to just release v0.3.0 of hyrax-doi and bundle install

Update gemfile to just release v0.3.0 of hyrax-doi and bundle install

---

Gemfile.lock

- Pulls in work to enable Bulkrax FileSet create and update for Valkyrie on branch 5.0-flexible
Connected to https://github.com/notch8/hykuup_knapsack/issues/454

Update hyrax version for Bulkrax FileSet Create and Update

---

Gemfile
Gemfile.lock

Updates to latest Bulkrax release, which includes FileSet update implementation

Update Bulkrax version 9.3.1
