samvera/hyku

config/initializers/apartment_activejob.rb, lib/active_job_tenant.rb, spec/lib/active_job_tenant_spec.rb
Fixes #55 
Using the general pattern from https://github.com/influitive/apartment-activejob, extend ActiveJob::Base to inject apartment and our own multitenancy requirements.
=> Extend ActiveJob::Base to support apartment tenants

Gemfile, Gemfile.lock, Rakefile
This is complaining about every migration we've generated thus far
=> Remove strong_migrations_gem

Gemfile, Gemfile.lock, config/initializers/riiif.rb, config/routes.rb
You can hit the image server by going to
http://localhost:3000/images/3t945r21d%2Ffiles%2F3a81f05c-5570-47a5-8f04-974317c20323/full/full/0/default.jpg
You can construct this ID by doing:
```ruby
fs = FileSet.find('3t945r21d')
CGI.escape(fs.original_file.id)
=> "3t945r21d%2Ffiles%2F3a81f05c-5570-47a5-8f04-974317c20323"
```
Fixes #112
=> Install RIIIF to provide IIIF image API

.rubocop.yml, app/controllers/accounts_controller.rb, app/controllers/application_controller.rb, app/controllers/splash_controller.rb, app/models/account.rb, app/services/create_account.rb, app/views/accounts/_edit_form.html.erb, app/views/accounts/_new_form.html.erb, app/views/accounts/edit.html.erb, app/views/accounts/new.html.erb, app/views/layouts/multitenant.html.erb, app/views/splash/index.html.erb, config/locales/blacklight.en.yml, config/locales/en.yml, config/locales/sufia.en.yml, config/routes.rb, config/settings.yml, config/settings/production.yml, db/migrate/20160506091234_add_name_to_account.rb, db/schema.rb, spec/controllers/accounts_controller_spec.rb, spec/factories/accounts.rb, spec/models/account_spec.rb, spec/requests/home_spec.rb, spec/views/accounts/edit.html.erb_spec.rb, spec/views/accounts/index.html.erb_spec.rb, spec/views/accounts/new.html.erb_spec.rb, spec/views/accounts/show.html.erb_spec.rb
- add a simple splash page
- only require an account name, and generate default settings for other params
- use a uuid for account tenant identifier
- use a local subdomain, and push custom cnames to editing account
=> Simply multitenant account creation workflow

README.md, app/models/account.rb, spec/models/account_spec.rb
This allows us to use a single command instead of having to switch both
the account and the Apartment::Tenant separately
=> Add Account.use_account!

app/builders/manifest_helper.rb, app/controllers/curation_concerns/file_sets_controller.rb, app/controllers/curation_concerns/generic_works_controller.rb, app/presenters/concerns/displays_image.rb, app/presenters/curation_concerns/generic_work_show_presenter.rb, app/presenters/hybox/file_set_presenter.rb, config/initializers/file_set_displays_image.rb, spec/controllers/curation_concerns/file_sets_controller_spec.rb, spec/controllers/curation_concerns/generic_works_controller_spec.rb, spec/presenters/curation_concerns/generic_work_show_presenter_spec.rb, spec/presenters/hybox/file_set_presenter_spec.rb
Manifest generator needs a host, but we also need to support
multitenant. This passes the host through the controllers to the
presenters where it's needed to draw IIIF manifests.
Fixes #177
=> Pass the hostname from the request to IIIF

Gemfile, Gemfile.lock
This new version of riiif does the prescribed redirect from the base
image route to the info.json route
=> Update dependencies, including Riiif 0.2.1

Gemfile.lock
This fixes a bad route in riiif 0.2.2
```
NoMethodError (undefined method `info_path' for #<Riiif::ImagesController:0x0056376a120988>):
riiif (0.2.2) app/controllers/riiif/images_controller.rb:37:in `redirect'
```
=> Update Riiif to 0.2.3

app/assets/stylesheets/lerna.scss
=> Fix link text color in masthead dropdown menu

spec/services/iiif_thumbnail_path_service_spec.rb
This should prevent an error  in testing like:
```
ActiveFedora::IllegalOperation:
Attempting to recreate existing ldp_source:
`http://127.0.0.1:8986/rest/test/s1/78/4k/72/s1784k724'
```
=> Don't assign an id to the FileSet

app/assets/stylesheets/accounts.scss, app/assets/stylesheets/sufia.scss, app/views/accounts/_new_form.html.erb, app/views/accounts/new.html.erb
Ideally this would also include removing the navbar below the brand bar, since on this page the user would have no reason to use the links or search box, but it's not clear to me how to remove it.
=> Update content and styling of new account page

app/assets/stylesheets/accounts.scss, app/views/accounts/_new_form.html.erb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/initializers/simple_form.rb
Added Devise views and customized layout of sign up page. 
We'll probably want to revisit some of this (e.g., simple form wrapper customization) when we tackle the other related views (Log in, New password, etc.) to ensure all related forms are using the same layout and error message display in an efficient way.
=> Sign up page styling

lib/active_job/queue_adapters/better_active_elastic_job_adapter.rb, spec/lib/active_job/queue_adapters/better_active_elastic_job_adapter_spec.rb
Rails 5 updated the adapter API, and upstream has hard-coded their class name.
Fixes #301
Also pursuing upstream at https://github.com/tawan/active-elastic-job/pull/44.
=> Fix SQS job enqueueing problem

app/controllers/application_controller.rb, config/initializers/new_framework_defaults.rb
Rails 5 no longer prepends the CSRF forgery check, so we need to ensure it appears at the top of the call chain. For some, yet to be determined, reason, simply moving it to the top of `ApplicationController` is insufficient.
=> Use rails 5 CSRF default settings; fixes #303

app/controllers/application_controller.rb
The controller that is extending ApplicationController may not be using
the main application route set.  Fixes #367
=> Redirect to splash_path with the route_set

Dockerfile, Gemfile, README.md, config/environments/production.rb, config/initializers/apartment.rb, config/initializers/redis_config.rb, config/initializers/sidekiq.rb, config/redis.yml, config/settings.yml, docker-compose.base.yml, docker-compose.yml
```
$ docker-compose up
$ docker-compose scale web=3 workers=2 solr=3 zookeeper=2 redis=2 redis_sentinel=2
```
=> Add docker-compose manifest for launching the stack using docker

Gemfile.lock, app/assets/stylesheets/lerna.scss, app/helpers/application_helper.rb, app/views/sufia/admin/_sidebar.html.erb, spec/features/admin_dashboard_spec.rb, spec/features/labels_spec.rb
Not great right now, but at least it's a start.
=> Update the admin sidebar to use standard bootstrap components

app/controllers/admin/users_controller.rb, app/controllers/users_controller.rb, app/views/sufia/admin/_sidebar.html.erb, config/routes.rb, spec/controllers/admin/users_controller_spec.rb
Because the public still uses the regular UsersController and they don't
want to use it with the admin layout.
Fixes #478
=> Move UsersController to Admin::UsersController

app/controllers/hyrax/mailbox_controller.rb, app/controllers/mailbox_controller.rb, spec/controllers/hyrax/mailbox_controller_spec.rb
Previously it was using the non-namespaced controller, but Hyrax uses
the controller in its namespace.
Fixes #509
=> Require the correct MailboxController

.rubocop_todo.yml, app/controllers/concerns/hyku/iiif_manifest.rb, app/controllers/hyrax/generic_works_controller.rb, app/controllers/hyrax/images_controller.rb, app/presenters/hyku/manifest_enabled_work_show_presenter.rb, spec/controllers/hyrax/generic_works_controller_spec.rb, spec/presenters/hyku/manifest_enabled_work_show_presenter_spec.rb
Previously manifests were only created for GenericWorks (not for
Images).
Fixes #501
=> Provide iiif manifests for all work types

app/models/ability.rb, app/models/user.rb, spec/models/ability_spec.rb
This allows the access controls to match objects that have the admin
group set. Ref #536
See
https://github.com/projecthydra-labs/hyrax/blob/1e504c200fd9c39120f514ac33cd42cd843de9fa/app/services/hyrax/admin_set_create_service.rb#L17
for an example of where it expects the admin to be a member of the admin
group.
=> Ability#user_groups should include the admin group

Gemfile.lock
This fixes a bug in hyrax that was preventing one from assigning depositors to an admin set.
=> Update hyrax. Ref #536

app/views/hyrax/homepage/_featured_researcher.html.erb
Removed "Featured Researcher" heading because the title is already either on the content
section or on the tab from the prior partial (in hyrax). 
Also changed to access the text from the hyrax yml file to enable appropriate language function for this content block.
This resolves issue https://github.com/projecthydra-labs/hyku/issues/555
=> Remove duplicate "Featured Researcher" title

config/initializers/redis_config.rb
Previously the configuration hash included:
```ruby
{ sentinels: nil }
```
This caused an error with the redis client.
Now we no longer pass along `sentinels:` if it is not present in the
configuration file.
Fixes #466
=> Fix Redis config when sentinels are not specified

Gemfile.lock
BrowseEverything was previously causing a NameError to be raised in
background jobs. See
https://github.com/projecthydra/browse-everything/issues/146
=> Update dependencies including browse-everything

app/views/content_blocks/_form.html.erb
Fixes https://github.com/projecthydra-labs/hyku/issues/574
Note: inactive tabs have a smaller text box area than the active tab (see images below comparing the active tab vs other tab tab). This seems to be somewhere in the javascript for the tinymce setup, where the height setting passed in is not affecting the actual size of the displayed box. Since the box enlarges as content is added to it, this is a minor issue, but if it needs to be fixed, someone with more JS knowledge than mine will need to investigate it.
=> Make only about_page tab active

app/views/hyrax/admin/_sidebar.html.erb
Moves the "Reviews" menu item on the admin sidebar to the "Tasks" section.
Resolves git issue: https://github.com/projecthydra-labs/hyku/issues/634
Related PR in hyrax changes the menu item title to Workflows.
=> Move "reviews" on admin sidebar

Gemfile, Gemfile.lock
Previously running bundle install showed this warning:
```
WARNING: `scss-lint` has been renamed to `scss_lint` to follow proper
RubyGems naming conventions. Update your Gemfile or relevant install
scripts to install `scss_lint`.
```
=> Switch from scss-lint to scss_lint

app/controllers/catalog_controller.rb
`before_filter` is deprecated.  The code was fixed already, but the comment wasn't.
=> Trivial comment fix

README.md
Pulling from [wiki](https://github.com/projecthydra-labs/hyku/wiki)
We need to bind to 0.0.0.0 to support development w/ multiple tenants (w/ modified hosts file).
=> Update rails server line

app/jobs/cleanup_account_job.rb, app/jobs/remove_solr_collection_job.rb, spec/jobs/cleanup_account_job_spec.rb, spec/jobs/remove_solr_collection_job_spec.rb
This improves the idempotency of CleanupAccountJob
Fixes #711
=> Separate RemoveSolrCollectionJob from CleanupAccountJob

.ebextensions/nginx.config
Jobs that run longer than 75-90s time out on nginx as a stale connection. This commit bumps the timeout ceiling to 10 minutes for long running jobs. 
=> Bumps nginx timeouts to 10m

app/presenters/hyku/menu_presenter.rb, app/views/hyrax/admin/_sidebar.html.erb, config/locales/en.yml, config/locales/es.yml, spec/features/admin_dashboard_spec.rb
Resolves issue https://github.com/projecthydra-labs/hyku/issues/483 by renaming "Roles and Permissions" to "Users and groups" and removing the menu link to manage roles and permissions. 
=> Rename Roles and Permissions admin menu item

app/jobs/import_work_from_purl_job.rb, spec/jobs/import_work_from_purl_job_spec.rb
This means we don't have to retreive metadata subsequently if there is
an error during work creating.
=> Separate the metadata fetching from the work creation

config/routes.rb
Work-around pending https://github.com/projecthydra-labs/hyrax/issues/376
=> Add proprietor route for the dashboard pending upstream bug fix

app/views/shared/_footer.html.erb
This work was done in Sufia in January (https://github.com/projecthydra/sufia/pull/3010) but we override the footer partial, so we did not pick up changes. Adding the new `site-footer` class to our override fixes this.
=> Affix footer to bottom of the screen

Gemfile, Gemfile.lock, app/assets/javascripts/hyku/groups/add_member.js, spec/features/admin_dashboard_spec.rb, spec/rails_helper.rb
This effectively hides the supposed-to-be-hidden form field that the username lookup field uses behind the scenes. In order to test this, I pulled in `poltergeist` and `database_cleaner`, since this relies on javascript firing.
Fixes #837
=> Group management javascript should use Blacklight.onLoad

.ebextensions/logzio.config
Fixes current busted deploys.
The cloudflare folks moved the location of their certs to a subdir. This adjusts to that change.
=> Fix logz.io cert location

Gemfile, Gemfile.lock, README.md, config/application.rb, spec/spec_helper.rb
See https://github.com/fphilipe/i18n-debug. We may need to observe if
this adds any significant time to builds.
Below is example output that is written to
`./log/test.log`:
```console
[i18n-debug] en.simple_form.labels.file_set.files => nil
[i18n-debug] en.simple_form.labels.file_set.files => nil
[i18n-debug] en.simple_form.labels.defaults.files => "Upload a file"
[i18n-debug] en.simple_form.required.text => "required"
[i18n-debug] en.simple_form.required.mark => "*"
[i18n-debug] en.simple_form.required.html => "<span class=\"label label-info required-tag\">required</span>"
[i18n-debug] en.simple_form.hints.file_set.files => nil
[i18n-debug] en.simple_form.hints.file_set.files => nil
[i18n-debug] en.simple_form.hints.defaults.files => nil
[i18n-debug] en.simple_form.hints.defaults.files …
```
=> Adding support for i18n-debug

config/initializers/hyrax.rb
NOIDs were taking too long when there is contention for the minter. Maybe we can take a closer look at this post-mvp?
=> Use UUID instead of NOIDs for the MVP

app/assets/stylesheets/hyku.scss, app/assets/stylesheets/variables.scss
Our previous strategy for reducing the height of the topbar/brandbar adversely affected the main menu navigation bar. This PR scopes changes to the topbar and to desktop viewports, so the height is unaffected on mobile where the taller topbar is helpful for containing the taller expand menu icon.
=> Reduce height of topbar when viewport is desktop size

app/assets/stylesheets/hyku.scss, app/assets/stylesheets/variables.scss
Fixes earlier PR that inadvertently resulted in 15px of space below the top bar. Also, removes related CSS no longer needed with recent sidebar updates.
=> Fix extra space below top bar

config/application.rb
So that we can figure out why non-admins can't submit works.
Ref https://github.com/projecthydra-labs/hyrax/issues/753
=> Temporarily turn off the rescuing of not found exceptions

Gemfile, Gemfile.lock
https://github.com/PerfectlyNormal/tinymce-rails-imageupload/issues/86
Fixes #955
=> Use a known-good version of tinymce-rails-imageupload

Gemfile.lock
Bundler was setting beta.2 even though I specified beta.
=> Manually tweak the Gemfile.lock

.rubocop.yml, .rubocop_todo.yml, lib/tasks/grant_superadmin.rake, spec/support/rake.rb, spec/tasks/rake_spec.rb
Create superadmin:grant rake task.
Fixes #733
`rake superadmin:grant[user1@example.org]`
A rake task to grant the superadmin role to the specified users. 
'spec/support/rake.rb' is adapted from hyrax with added support for multiple task arguments.
find_by_user_key is whitelisted because it is actually a defined method of User..
=> Create superadmin:grant rake task.

config/initializers/attach_files_monkeypatch.rb
Pushing this through for a workshop being held tomorrow, so they can upload files.
=> Ugly workaround to get the AttachFilesToWorkJob working again on AWS

app/jobs/create_default_admin_set_job.rb, spec/jobs/create_default_admin_set_job_spec.rb
After a long discussion with @atz, @cbeer, and @jcoyne, I have decided to start by adding a new job to create a default Admin Set. A follow-up PR might be to sacrifice idempotency to handle account creation in a single job. This would be temporary, to ensure that default AS creation works during the community beta testing period (May 15th through June). Ultimately we should pursue the "UX step" approach outlined by @atz in #884, though we likely don't have time to complete and test that for a month or two.
=> Create a default admin set when a tenant is created

app/jobs/create_account_inline_job.rb, app/services/create_account.rb, spec/jobs/create_account_inline_job_spec.rb, spec/services/create_account_spec.rb
The strategy here is to inline the account creation, invoking our current jobs synchronously in order.
Anything else I should add to this? More condition checking, so if a job *is* run twice it "does the right thing?" Ideas, @atz @jcoyne @cbeer?
=> Inline account creation to ensure default Admin Set exists

app/jobs/create_account_inline_job.rb, app/jobs/create_default_admin_set_job.rb, spec/jobs/create_default_admin_set_job_spec.rb
Otherwise it is invoked outside of the tenant context.
=> Pass account object to AS creation job

db/migrate/20170320131133_tidy_up_because_of_bad_exception.hyrax.rb
Using the column_names method on the Hyrax::PermissionTemplate class leads to false positives, which lead to exceptions, which were eaten by the bare `rescue`. Now it is possible to run `rails db:drop db:create db:migrate` without errors
=> Use column_exists? to see if :workflow_id is present

app/jobs/cleanup_account_job.rb, spec/jobs/cleanup_account_job_spec.rb
Currently, if you attempt to destroy a tenant from the SuperAdmin UI scaffolding at
http://[my.admin_host.url]/proprietor/accounts
(Note: this path is only accessible to superadmins. See https://github.com/projecthydra-labs/hyku/wiki)
You'll receive an error on [this line of code](https://github.com/projecthydra-labs/hyku/blob/master/app/jobs/cleanup_account_job.rb#L13) showing a 405 Response from Fedora.
This PR fixes the tenant deletion by passing a relative path to Fedora `delete()` (e.g. "[tenant-uuid]") instead of the `base_path` (e.g. "/[tenant-uuid]").  Because the latter starts with a slash (/), Fedora assumes it should be a root path and fails to locate the Container to delete.
After this PR is applied, you can delete tenants from the UI by doing the following:
* Login as a …
=> Fix tenant deletion by passing relative path to Fedora delete() call

db/migrate/20170427003546_add_index_to_accounts.rb, db/schema.rb, spec/models/account_spec.rb
Only one account should be able to reference a given **[solr|fcrepo|redis]_endpiont**.  It is important to understand that Rails validations never truly provide guarantees of uniqueness in a multi-server application.  It **must** be done at the database level, since at runtime, the database is the only component used in common.  
For more background, see:
https://robots.thoughtbot.com/the-perils-of-uniqueness-validations
Hyku is fortunate, since it is already using postgres in all environments and postgres is perfectly capable of handling referential integrity.
=> Referential integrity for endpoint IDs

app/jobs/cleanup_account_job.rb, spec/jobs/cleanup_account_job_spec.rb
Enhances `CleanupAccountJob` to also cleanup Redis namespace whenever an Account/tenant is deleted. This is a followup to comments in #1022.
The code works, but the specs currently leave something to be desired.  Just pushing this up for now and will take another look next week.
=> Ensure Redis namespace is cleaned up during tenant deletion

app/assets/stylesheets/hyku.scss
Fixes #982 
Indents submenu items in admin sidebar so it is more clear that they below to their parent menu item.
--
=> Indent admin menu submenu items

app/views/admin/groups/edit.html.erb, app/views/admin/groups/index.html.erb, app/views/admin/groups/new.html.erb, app/views/admin/groups/remove.html.erb, app/views/admin/groups/users.html.erb
Fixes #946 
Apply page header css to groups admin pages.
Uses content_for to add surrounding divs to the page header so they match the style of other admin pages.
=> Apply page header css to groups admin pages.

app/models/user.rb
User code should not refer to `account` in this App, as this is an important distiction in this app.
=> User - remove comment reference to account

config/initializers/hyrax.rb
Also, use a more compact tree (without an annoying leading slash) when uploading into S3.
=> Segregate tenant uploads into separate subfolders

app/models/account.rb, spec/models/account_spec.rb
Because these have bearing on our rails-level detection for unique cname.
See:
https://github.com/projecthydra-labs/hyku/issues/1012#issuecomment-297899330
=> Test methods individually

app/assets/stylesheets/hyku.scss, app/assets/stylesheets/variables.scss
Fixes #1078.
@ggeisler you were trying to fix the top navbar height in #945, but the fix broke other navbar styling (see #1078). This commit reverts it, and changes the top navbar to the default 50px, so at least nothing looks broken.
How important is it that the top navbar be 35px high? Is 50px something we can live with for now, or do we need to come up with a better fix?
=> Revert "Fix extra space below top bar"

docker-compose.base.yml
Not only is the docker-ified application not set up for that, it is interpreted in railsconfig-land as the string `"false"` (which is truth-y)
I suspect this was introducing unintentionally in #954.
=> Remove `SETTINGS__MULTITENANCY__ENABLED` setting

app/models/account.rb, app/models/fcrepo_endpoint.rb, app/models/redis_endpoint.rb, app/models/solr_endpoint.rb, spec/models/account_spec.rb
Prevents half-formed tenants from partially or entirely in the global lobby.  
Also refactors `reset!` to be at each Endpoint's descendants' class level, therefore `@account.reset!` is not dependent on account well-formedness, while `switch!` decidedly is.
=> Switch all or bust

.travis.yml, config/settings/test.yml, spec/controllers/account_sign_up_controller_spec.rb, spec/controllers/admin/group_users_controller_spec.rb, spec/controllers/admin/groups_controller_spec.rb, spec/controllers/hyrax/admin/appearances_controller_spec.rb, spec/controllers/splash_controller_spec.rb, spec/factories/accounts.rb, spec/models/account_spec.rb, spec/requests/home_spec.rb, spec/requests/riiif_spec.rb, spec/routing/admin/accounts_routing_spec.rb, spec/routing/proprietor/accounts_routing_spec.rb, spec/support/multitenancy_metadata.rb, spec/views/account_sign_up/new.html.erb_spec.rb, spec/views/proprietor/accounts/edit.html.erb_spec.rb, spec/views/proprietor/accounts/index.html.erb_spec.rb, spec/views/proprietor/accounts/new.html.erb_spec.rb, spec/views/proprietor/accounts/show.html.erb_spec.rb
See #989 where this was all debated over being merged into a branch that was thrown away.  But we actually want this.
=> Mutlitenancy in test

app/controllers/hyrax/file_sets_controller.rb, app/controllers/hyrax/generic_works_controller.rb, app/controllers/hyrax/images_controller.rb
Fixes #1096 
The issue describes the approach taken here.  Basically, it updates the hyrax controllers with a new mixin for the breadcrumbs.
NOTE:  the breadcrumbs for the `FileSetsController` is a GUESS.  I don't know, yet, whether it should be added and, if so, whether it should be a `BreadcrumbsForCollections` mixin.
=> hyrax controllers are missing a breadcrumbs mixin

app/controllers/application_controller.rb, config/settings.yml
This method was added in aaac7e99c1588132e15ef9ff02f17923df0a61fa and
we stopped using it in 986b905ec7b71500bc3a569c5db86e133a6a8200
=> Remove unused worker? method

app/controllers/content_blocks_controller.rb, app/controllers/labels_controller.rb, app/controllers/sites_controller.rb, app/forms/appearance_form.rb, app/views/hyrax/admin/appearances/show.html.erb, config/routes.rb, spec/controllers/hyrax/admin/appearances_controller_spec.rb, spec/controllers/sites_controller_spec.rb
`SitesController` previously had a call that *required* set_site to exist in itself, but it did not have it defined.  This is required to make `SitesController` useful. At the same time, we can utilize inheritance.
Fixes #960
=> Consolidate set_site to SitesController and inherit downstream

spec/models/collection_spec.rb, spec/models/qa/local_authority_entry_spec.rb, spec/models/qa/local_authority_spec.rb
Mostly this is just to help us avoid "pending" warnings in the test suite.
=> Add missing model tests

spec/spec_helper.rb
This is no longer required since we're not using AF::Noid
=> Remove unused AF-noid rspec stuff

app/jobs/cleanup_account_job.rb, app/jobs/remove_solr_collection_job.rb, spec/jobs/cleanup_account_job_spec.rb, spec/jobs/remove_solr_collection_job_spec.rb
Fixes following issues on `master`:
* Partial tenants (e.g. where one or more endpoints are missing) cannot be deleted (as an exception is thrown when `Account.switch` is called on a partial tenant). This is resolved by https://github.com/projecthydra-labs/hyku/pull/1140/commits/cfc07300c2e36e8ea12b8f4f8a8dfd14f2c3f609
* When a Solr endpoint is deleted, the underlying Solr Collection remains. This is resolved by https://github.com/projecthydra-labs/hyku/pull/1140/commits/d58a760178e6fb4cb31c2c6c328cfa99ddc1b7fb
=> Fixes to tenant deletion (cleanup_account_job.rb)

app/jobs/create_fcrepo_endpoint_job.rb, app/jobs/create_redis_namespace_job.rb, app/jobs/create_solr_collection_job.rb, app/models/account.rb, app/models/nil_fcrepo_endpoint.rb, app/models/nil_redis_endpoint.rb, app/models/nil_solr_endpoint.rb, app/services/create_account.rb, spec/models/account_spec.rb, spec/models/nil_fcrepo_endpoint_spec.rb, spec/models/nil_redis_endpoint_spec.rb, spec/models/nil_solr_endpoint_spec.rb, spec/services/create_account_spec.rb
=> Use the Nil Object Pattern for non-initialized connections.

config/workflows/default_workflow.json
This enables the default workflow should allow sharing and makes
our template comparable to what is generated in the recent version
of hyrax.
=> Add missing allows_access_grant property to workflow template

config/initializers/hyrax.rb, config/settings.yml
Fixes #1174 
Changes contact email config value to pull from settings.yml, allowing the value to be set via an environment variable. Also fixes the comment in settings.yml that indicates how to set values via an environment variable.
Note; I think this should work, but don't have a local environment set up that allows testing this change. Comments and testing are welcome.
=> Allows contact form email address to be set via an environment variable

app/views/hyrax/base/show.html.erb
It was already removed from the same template in Hyrax, which is overridden in Hyku. Without this change, the workflow label appears twice: once styled and once unstyled.
=> Remove span from overridden view

app/controllers/transfers_controller.rb
This override is already happening upstream, so we have no need of this.
It's referencing a missing constant preventing deploys
=> Don't reference a missing constant

.rubocop.yml, app/controllers/hyku/registrations_controller.rb, app/views/_user_util_links.html.erb, config/locales/en.yml, config/locales/es.yml, config/locales/zh.yml, config/routes.rb, config/settings.yml, spec/controllers/hyku/registrations_controller_spec.rb, spec/views/_user_util_links.html.erb_spec.rb
When account creation is disabled, redirect to the homepage with an alert. When enabled, let Devise do its thing. This implementation relies on a small routing change that lets Hyku override two methods in `Devise::RegistrationsController`.
Fixes #1203
=> Disable account signup depending on Settings variable

Gemfile, Gemfile.lock, app/controllers/proprietor/accounts_controller.rb, app/models/account.rb, app/models/site.rb, app/models/user.rb, app/views/proprietor/accounts/edit.html.erb, app/views/proprietor/accounts/index.html.erb, app/views/proprietor/accounts/new.html.erb, app/views/proprietor/accounts/show.html.erb, config/initializers/devise.rb, config/locales/devise_invitable.en.yml, config/locales/devise_invitable.es.yml, config/locales/devise_invitable.zh.yml, config/locales/en.yml, config/locales/es.yml, config/locales/simple_form.en.yml, config/locales/simple_form.es.yml, config/locales/simple_form.zh.yml, config/locales/zh.yml, db/migrate/20170605152346_devise_invitable_add_to_users.rb, db/schema.rb, spec/controllers/proprietor/accounts_controller_spec.rb, spec/features/accounts_spec.rb, spec/models/account_spec.rb, spec/models/site_spec.rb, spec/views/proprietor/accounts/show.html.erb_spec.rb
Fixes #725 by enhancing the existing SuperAdmin UI (`/proprietor/accounts`) to provide the ability to easily add/remove/review Account Administrators.  Here's an example screenshot (for an account with cname="test3.lvh.me"):
Adding a new Account Administrator uses `devise_invitable` to send an email invitation if the person does not yet have a login for that Account. If the person does have a login, then their login is immediately updated with Admin rights.
Also cleans up existing SuperAdmin UI screens to use `simple_form_for` and add i18n to all views.
**NOTE: This is flagged as a WIP, as it does not yet include updated specs or translations.**  However, the basic functionality is ready for review/comment, as it works.
=> Add ability to add/remove/review Account Admins in SuperAdmin UI

docker-compose.yml
Fixes #1246 
Moves mount point of the Solr Docker container's solr volume.
The Solr container saves its index data at `/opt/solr/server/solr`, instead of `/data` where the solr volume is mounted currently. Moving the index data to `/data` is not feasible because of volume permission issues, so keeping the data at its default location (and persisting it) is the simplest fix.
=> Move Solr container volume to where Solr data lives.

app/assets/javascripts/application.js
=> Load Hyku javascript assets before Hyrax ones, following a pattern found in ScholarSphere

docker-compose.yml
Previously line 185 was overwriting line 180.
The volume previously on line 180 is critical for running on
docker-machine, but was not needed on Docker CE.
See https://hub.docker.com/r/dockercloud/haproxy/ "Running with Docker
Compose v2 (Compose Mode)"
=> Merge volume directives

docker-compose.yml
The current directions do not work on docker CE and cause the following error:
```
ERROR: for lb  Cannot create container for service lb: invalid volume spec ".": invalid volume specification: '.': invalid mount config for type "volume": invalid mount path: '.' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
```
=> Comment out DOCKER_CERT_PATH by default

app/mailers/hyrax/contact_mailer.rb, config/initializers/devise.rb, config/settings.yml
Fixes #1265
See corresponding documentation here: https://github.com/samvera-labs/hyku/wiki/Set-email-addresses
Also, override Hyrax mailer to inject tenant name into contact form submissions.
Fixes #1230
=> Use settings to configure a From address for user invitation email

app/services/iiif_thumbnail_path_service.rb, spec/services/iiif_thumbnail_path_service_spec.rb
Standard thumbnails for PDFs. This was needed because RIIIF doesn't
flatten pdfs, making them look all black. Similar to:
https://github.com/samvera/hydra-derivatives/issues/110
=> Only make iiif thumbnails for images.

Gemfile, Gemfile.lock
It seems like this may have broken the AWS deploy. Files are no longer attaching.
=> Revert hyrax to before the file ingest change

app/assets/stylesheets/viewer.scss, app/views/hyrax/base/_representative_media.html.erb
Fixes #1251
Adds a wrapper class around viewer div so height can be set without using viewer class.
=> Wrap viewer so height can be set without using viewer class.

spec/models/solr_endpoint_spec.rb
This failed with certain test seeds and not others.
=> Fix test that was failing intermittently.

config/initializers/riiif.rb
This was definining a #logger method on the ruby top-level `main` object, globally available to all code anywhere, beyond this initializer.  (I verified indeed that happened)
I think this was unintentional (if you wanted to do such a thing, you wouldn't
do it here), and it's poor code hygiene. Opens you up to other bugs where
some other code somewhere else calls `logger` thinking it's getting something
else, but gets main#logger instead. Or calling `super` somewhere and getting this even weirder.
=> Remove accidental definition of global #logger method

config/initializers/hyrax.rb
Because we aren't installing ffmpeg on AWS/Docker.
Fixes #1141
Ref #1162
We should revert this when we install ffmpeg
=> Turn off transcoding using ffmpeg

public/bower_includes/universalviewer/dist/uv-2.0.1/lib/embed.js
Workaround for:
https://github.com/UniversalViewer/universalviewer/issues/471
This replacement will need to be repeated whenever we upgrade jquery
=> Don't let UV load a second copy of jquery

spec/controllers/sites_controller_spec.rb, spec/models/uploaded_file_spec.rb
Don't fail if run w/ live Settings.s3.upload_bucket.
This prevents tests from hardcoding the dev/test configuration and allows them to more accurately establish their expectations.  
This approach would help us test Carrierwave-AWS against live S3 configuration, which is a point of failure for us.
=> Carrierwave test flexibility

app/models/account.rb, lib/tasks/tenantize_task.rake, spec/models/account_spec.rb, spec/support/rake.rb, spec/tasks/rake_spec.rb
Fixes #1357
To run the `rake user:list[email,foobar]` task within the context of all tenants, invoke `rake tenantize:task[user:list,email,foobar]`. To run the task only in specified tenants, use an environment variable named `tenants`, with each tenant cname separated by a space: `rake tenantize:task[user:list,email,foobar] tenants="foo.localhost baz.localhost quuuuux.localhost"`
=> Add a rake task that runs other tasks on all or selected tenants

app/models/account.rb, app/models/nil_site.rb, app/models/site.rb, app/models/user.rb, spec/models/account_spec.rb, spec/models/nil_site_spec.rb, spec/models/site_spec.rb, spec/models/user_spec.rb
Fixes #1041
While this isn't a serious issue, it's extremely annoying/confusing to debugging other issues (see #1041). So, I'm scratching my own itch and simply fixing it.
This PR creates a new `NilSite` object which is used to represent the `Site` object in a global scope (i.e. global tenant in a multitenant environment). This `NilSite` ensures that an empty Site is not persisted to the database (and admin rights assigned) as described in #1041.
This PR comes with specs, but can also be tested by repeating the behavior described in #1041 and ensuring that an empty Site is not generated in the global / default database schema.
Comments/suggestions welcome, but this was the easiest way I could figure out to resolve this strange behavior.
=> Ensure Site object in global scope is NilSite and never persisted.

app/controllers/account_sign_up_controller.rb, app/views/splash/index.html.erb, config/locales/en.yml, config/settings.yml, spec/controllers/account_sign_up_controller_spec.rb, spec/features/splash_spec.rb, spec/views/splash/index.html.erb_spec.rb
Fixes #735
Adds a new configuration `Settings.multitenancy.admin_only_tenant_creation` (default is true). When enabled, new tenants can only be created by logged in, superadmin users. When disabled, anonymous users can create new tenants & setup an account on that tenant (this scenario is mostly for demo purposes).
This results in two views of the splash page:
* If `admin_only_tenant_creation=false`, the splash page works like the existing demo site, and a big green "Get Started" button appears. In this scenario, anonymous users can create tenants.
* If  `admin_only_tenant_creation=true` (new default), the big green button will now say "Login to get started" and sends you to authenticate as a superadmin first. In this scenario, you must be a superadmin user to create tenants.
* If you …
=> Create new admin_only_tenant_creation setting, default to true

.ebextensions/honeybadger.config
The honeybadger deployment notification script was breaking deploys to the stanford demo stack. This fixes that.
This adds the need for another environment variable of `GITHUB_REPO` at the beanstalk environment to work properly. I made an issue to track that work: https://github.com/hybox/aws/issues/169
=> Fixes honeybadger deployment notification

Gemfile, Gemfile.lock, app/presenters/hyku/manifest_enabled_work_show_presenter.rb, solr/config/schema.xml, spec/presenters/hyku/manifest_enabled_work_show_presenter_spec.rb
The IIIF Presentation API supports adding arbitrary metadata within a `metadata` array.
This small change in Hyku add a manifest_metadata method into ManifestEnabledWorkShowPresenter to support adding metadata into the IIIF manifest. It takes the `required_fields` for the object and returns a metadata array. This method is then consumed by the `iiif_manifest` gem (via this [PR](https://github.com/samvera-labs/iiif_manifest/pull/9)) and the metadata is added to the manifest. In Universal Viewer, the metadata will be displayed in the **_More Information_** tab to the right.
The mechanism for getting the required fields is a bit brittle and wouldn't work with works generated with a namespace. Having said that, it does not error, it just means metadata won't be retrieved by the …
=> Add metadata into IIIF Manifest

config/initializers/config_monkeypatch.rb
Fixes #1462 
This PR monkey patches the `config` gem, based on @mjgiarlo's bug fix PR to that gem: railsconfig/config#180
As such, this is only a temporary fix until the railsconfig/config#178 ticket is fixed and a new version of the `config` gem is released.   Once that occurs, this monkeypatch should be deleted.
I've tested this locally, and with this monkey-patch in place, setting `SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION=false` as an environment variable now works as expected.
=> Monkey-patch config gem per railsconfig/config#180

db/migrate/20171208100918_change_foreign_key_for_qa_local_authority_entries.rb, db/schema.rb
See Hyrax [issue 1034](https://github.com/samvera/hyrax/issues/1034)
This is caused by an incorrect foreign key. This PR adds a new migration to remove the incorrect foreign key and add the correct one.
Tested by running `hyrax:controlled_vocabularies:language` which now successfully imports lexvo.
=> Fix invalid foreign key error in languages importer

.travis.yml, Gemfile, Gemfile.lock, spec/rails_helper.rb
Poltergeist is no longer maintained
Rails 5.1 introduces ActionDispatch::SystemTestCase which should allow
our feature tests to be speed up when this is done:
https://github.com/rspec/rspec-rails/pull/1813
=> Switch from Poltergeist to headless Chrome

Dockerfile, docker-compose.yml
Fixes #1274. referenced in #1301
```
RuntimeError: Unable to execute command "/opt/fits-1.0.5/fits.sh -i "/data/tmp/uploads/[etc]""
workers_1         | Exception in thread "main" edu.harvard.hul.ois.fits.exceptions.FitsToolException: 
Error loading native library for MediaInfo please check that fits_home is properly set
```
Change proposed in this pull request:
* Add an environment variable pointing to FITS in `docker-compose.yml`
(CLA coming soon)
=> Fix error loading Fits MediaInfo dependency [Docker]

Gemfile, Gemfile.lock
Fixes #1535
fixes the fact that apache no longer creates md5sums for releases
This and a new config options appear to be the only things happening in the delta between solr_wrapper 1.2 and 2.0
=> solr_wrapper update, sha1 usage

README.md
This fixes the waffle badge.
This is a duplicate of https://github.com/samvera-labs/hyku/pull/1522 but made from a branch instead of a fork to test whether this build will pass or whether the aws tests will fail. These are the tests in question: https://github.com/samvera-labs/hyku/blob/master/spec/models/uploaded_file_spec.rb#L39-L108
=> Use shields.io to fix waffle badge

app/views/hyrax/base/show.html.erb
This already exists in [Hyrax](https://github.com/samvera/hyrax/blob/ca0766b3cc1b83859ce1b08d7cafbda18be07c84/app/views/hyrax/base/show.html.erb#L3)
before change:
The change proposed populates the metadata tags drafted [here](https://github.com/samvera/hyrax/blob/ca0766b3cc1b83859ce1b08d7cafbda18be07c84/app/views/shared/_citations.html.erb).
=> Hook up supported metadata tags

spec/spec_helper.rb
Fixes #1524 
No longer run S3 related specs on non-samvera-labs repos. This will allow specs to pass on forks.
This is a first swing at getting Travis to not run the specs unless the code is in samvera-labs/hyku. Specs on forks will thus pass and the 4 failing S3 specs from forks will get run properly once code is merged.
Note - need to check that the specs in question are run after this is merged.
=> Fixing the s3 specs

app/presenters/hyku/manifest_enabled_work_show_presenter.rb, app/views/hyrax/base/show.html.erb, app/views/shared/_additional_citations.html.erb, spec/factories/generic_works.rb, spec/presenters/hyku/manifest_enabled_work_show_presenter_spec.rb
This builds on PRs #1527 and #1528 ; adding logic to have `doi` and `isbn` citation tags for Google Scholar indexing:
=> Add DOI and ISBNs citations tags

app/presenters/hyku/manifest_enabled_work_show_presenter.rb, app/views/hyrax/base/show.html.erb, spec/presenters/hyku/manifest_enabled_work_show_presenter_spec.rb
As discussed in #1531  @orangewolf 
I also modified the ISBN regex: when I double-checked the feature in browser there was some wrongly identified isbn argh! I've modified the test so it would catch the bug: `match_array` instead of `include`.
=> Included render file

spec/spec_helper.rb
As hypothesized, the specs are not running in master any more.  That appears to be because TRAVIS_PULL_REQUEST_SLUG if you are not talking about a pull request. This should work in both cases now.
=> Fix s3 specs - part 2

app/forms/hyrax/form_terms.rb, app/forms/hyrax/generic_work_form.rb, app/forms/hyrax/image_form.rb, spec/forms/hyrax/generic_work_form_spec.rb, spec/forms/hyrax/image_form_spec.rb, spec/support/shared_examples_spec.rb
Display the Creative Commons "License" menu in the main fields when adding a new work, by adding `license` to `primary_terms`
We implemented this change in [our fork of Hyku](https://github.com/ubiquitypress/hyku).
=> Creative Commons License in main fields when adding a new work

app/services/concerns/iiif_thumbnail_paths.rb, spec/services/iiif_work_thumbnail_path_service_spec.rb
Fixes samvera/hyrax#1095
Do not assume all files have thumbnails available.
IIIFThumbnailPaths assumes that a thumbnail derivative was created for all filesets, however derivative creation depends on the file file mime type being included in the list of supported mime types. Falling back on Hyrax in this case should display the default work icon in place of a thumbnail.
* Use behavior from hyrax when `thumbnail?` is called on a fileset with an unsupported mime type.
=> Do not assume that everything has a thumbnail available.

Dockerfile
*If* you choose to download and execute random unsigned code off the internet, you should at the very least use HTTPS.
=> Fix fits download URL to use HTTPS

app/views/hyrax/dashboard/_sidebar.html.erb, app/views/hyrax/dashboard/sidebar/_activity.html.erb, app/views/hyrax/dashboard/sidebar/_configuration.html.erb, app/views/hyrax/dashboard/sidebar/_tasks.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/it.yml, config/locales/pt-BR.yml, config/locales/zh.yml, spec/features/admin_dashboard_spec.rb
This PR adds the Collection Types tab into the admin dashboard, and removes Admin Sets (now part of Collections). In addition, I've harmonized the dashboard with current Hyrax.
List of changes:
* split code into partials to mirror Hyrax
* add collection types to settings
* remove admin sets (now part of collections)
* removed 'users and groups', moved manage users and manage groups to 'tasks'
* renamed Technical to Features
* removed unused labels from locales
=> Harmonize dashboard with current Hyrax code

Gemfile.lock, app/models/fcrepo_endpoint.rb, spec/models/fcrepo_endpoint_spec.rb
We have a live Hyku where fedora shows as `down` in the system status. I think this must be because it uses authentication. When I try the ping directly in the rails console, I get `Ldp::NotFound`.
The current `ping` method is:
```
def ping
ActiveFedora::Fedora.instance.connection.head('/').response.success?
rescue StandardError
false
end
```
Changing it to the following works with our authenticated fedora:
```
def ping
ActiveFedora::Fedora.instance.connection.head('/').response.success?
rescue Ldp::NotFound
ActiveFedora.fedora.connection.http.head.success?
rescue StandardError
false
end
```
Feedback welcome on this change. The tests still pass but they *don't* currently test for an authenticated fedora. Advice on how to approach that, or on how to do this in a better way, would be …
=> Support pinging fedora endpoints with basic auth

README.md
Part of trying to get Coveralls back in a working spot.
=> Remove labs from several badge links to reflect new repo home

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/models/solr_document.rb, config/routes.rb, config/settings.yml, spec/features/oai_pmh_spec.rb
Fixes #1499 This work was sponsored by [PALNI](http://www.palni.org)
Brings in and configures the existing blackight-oai gem. 
This allows each tenant to have a /catalog/oai endpoint which provides OAI-PMH access to the collections within.  This is an initial feature offering, so I'm expecting it to become more sophisticated over time.
=> Add Blacklight OAI to Hyku

chart/sample.yaml, chart/templates/sidekiq-deploy.yaml, chart/templates/web-deploy.yaml
This PR:
1. adds network_files to the shared mounts
2. fixes a typo which was mounting different paths for derivatives on sidekiq and web
=> Add network_files to Helm chart

chart/sample.yaml, chart/templates/web-ing-wildcard.yaml, chart/templates/web-ing.yaml
The ingress resource will apply a default 1m setting to `client_max_body_size`. Setting `proxy-body-size` via an annotation allows us to override this.
=> Add proxy-body-size to ingress

app/services/hyrax/collection_thumbnail_path_service.rb
All references to "default collection images" or the like within this PR refer to theming default images that are uploaded under the Appearance Dashboard tab, _not_ the Hyrax default collection image. 
The `Hyrax::CollectionThumbnailPathService` was attempting to shove the entire `Hyrax::AvatarUploader` object into the `thumbnail_path_ss` Solr field: 
```ruby
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error parsing JSON field value. Unexpected OBJECT_START at [513], field=thumbnail_path_ss
```
`Collection` creation should no longer fail in production environments. Default collection images should be applied to newly created `Collections` (and `AdminSets`) successfully and resize appropriately. 
1.  The determining factor of whether this bug occurred or not was whether a …
=> Fix CollectionThumbnailPathService

docker-compose.yml, ops/nginx.sh
Forcing RAILS_ENV to development makes the specs run in the development environment instead of test
We mount tmp/cache to speed up page loads, but that volume often gets defaulted to root permissions.
=> Set tmp/cache permisisons and do not force RAILS_ENV

spec/lib/importer/mods_importer_spec.rb, spec/lib/importer/mods_parser_spec.rb, spec/lib/stanford/importer/mods_parser_spec.rb, spec/support/shared_examples_for_csv_importer.rb
I'm working on an engine which pulls Hyku in via a git submodule for its internal test application.  I want to occasionally run Hyku's test suite within the engine to ensure nothing is broken (or at least be aware of when something is being deliberately broken).  Rspec is being run from the engine root so the relative paths used in some tests cause them to fail.  Switching to these paths to use `fixture_path` which uses `Rails.root` fixes this issue while not affecting the Hyku tests.
=> Use paths based on Rails.root instead of pure relative paths in tests

docker-compose.yml, ops/nginx.sh
Anything that makes a lot of small files on a bind mounted directory can cause slowness in certain Docker environments such as Docker.app for Windows or Mac and some Linux file system types.  Dynamically compiling the assets is exactly the sort of small file IO that triggers this slowness. By moving the tmp/cache directory to a volume we significantly speed up page upload, especially when editing CSS, JS or view files (think 1 minute pages loads down to < 15s). 
=> volume for tmp/cache significantly speeds up dynamic asset building on windows/mac and some linux file systems

app/services/create_account.rb
When running the seed file, the fedora and solr endpoints are not being saved. Added account.save to the CreateAccount.create_external_services method to fix this.
* added account.save in the CreateAccount.create_external_services method
=> Seed files were erroring

config/initializers/apartment.rb
Fixes issue where switch callbacks weren't firing in rails console and possibly other cases like activejobs and single tenants.
=> Remove guard clause to ensure switch callbacks work

Gemfile, Gemfile.lock
Running docker-compose up web on a fresh checkout wasn't working without these changes:
- Switch active_elastic_job to `git: https://github.com/` from `github:`
- Add aws-sdk-sqs under the aws group
- Remove the BUNDLED WITH from the bottom of Gemfile.lock
=> Tweak Gemfile and Gemfile.lock for docker building

db/schema.rb
I was running into problems running my engine's migrations because schema.rb was out of sync with bulkrax's migrations.  This PR should bring them up to date.  To make this, I dropped the database, manually created it, then ran db:migrate.
=> Update schema.rb to reflect current state of migrations

app/controllers/hyrax/generic_works_controller.rb
Fixing this allows for Hyrax plugins to work as expected when injecting module mixins into the normal Hyrax presenters.
See https://github.com/samvera/hyku/blob/master/app/presenters/hyrax/generic_work_presenter.rb#L6
@samvera/hyrax-repo-managers
=> Use specific work type presenter since it is a subclass of Hyku::WorkShowPresenter

Gemfile.lock, docker-compose.yml
Sidekiq requires a newer version of Redis (>= 4), otherwise the workers container falls over locally and background jobs don't get processed. 
* Upgrade Redis to major version 5 
* Update sidekiq/redis gem/redis-namespace to fix `#exists` vs `#exists?` issue 
@samvera/hyku-code-reviewers 
This code was provided to Hyku by PALNI/PALCI.
=> Upgrade to Redis v5

docker-compose.yml
This change makes solr run more reliably in our specs and was recommended in dev chat with the folks working on the Solr docker image.
=> Helps with Solr sometimes falling over in dev/test

app/models/ability.rb, spec/features/create_work_spec.rb, spec/models/ability_spec.rb
- Do not show institution only works to users who do not have at least one role on the tenant in question.
- Do not allow creation of works unless the user has at least one role on the tenant in question.
My understanding is these are the 2 blockers for the 3.0 release.
=> Prevent users who do not have roles on a given tenant from being in the registered group automatically

Gemfile, Gemfile.lock
Use an official release and force hyrax to 2.9.1 or greater to pull in https://github.com/samvera/hyrax/pull/4660 and https://github.com/samvera/hyrax/pull/4656 along with the auto-expiry jobs (https://github.com/samvera/hyrax/pull/4526)
=> Use latest released 2.x Hyrax

Dockerfile.base, config/initializers/version.rb
This sets the version number to 3.0 and makes sure the bundler version matches the Gemfile.lock both now and in the future as needed to refresh the Docker hub images.
=> set version to 3.0 and fix base build

app/views/admin/work_types/edit.html.erb
When no work types are selected from the available options, then an `undefined method `include?' for nil:NilClass` will be thrown, preventing the user from selecting an option and resolving the issue. 
This tiny PR just catches the error and allows the checkboxes to be unchecked.
=> Prevent an error occuring in admin when no work types are selected

.circleci/config.yml
Fixes the CircleCI build which is failing currently.  See https://app.circleci.com/pipelines/github/samvera/hyku/323/workflows/74d691c6-f883-4db9-af65-28ac6f8302aa/jobs/352
=> Fix zookeeper bundle install

app/views/admin/work_types/edit.html.erb
By default it seems that the checkboxes on the work type select page are not wrapped in labels and thus far harder to select than it they were. This mini-PR adds a label around each checkbox. 
=> Use label tag to allow accessibly access

spec/rails_helper.rb
Facinatinly the feature spec flapping did not turn out to be related to order of
spec run! I was able to get semi-reliable failure running only one feature spec
over and over again. Running just create_image I could get failure locally about
50% of the time over 300 runs.
The issue with feature specs failing appears to stem from not waiting long
enough for the page to load after clicking a button. This ups from 2 seconds
to 8 seconds of wait time. It will only make specs that fail take longs than
nessisary practice and only by the 6 seconds. I ran 100 runs of the feature
specs locally with 3, 5 and 8 seconds. I got about 50% failure with 3 seconds
1% failure with 5 seconds and 0% failure with 8 seconds. So here is hoping
we can put the feature failure behind us.
cc @bess as I know you …
=> Reduce Feature Flapping

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, lib/active_job_tenant.rb, public/500.html
This might be a little forward of me however the Gem causes an almost intolerable amount of log noise when used with Ruby 2.7.x. 
```
> docker-compose exec web bundle exec rails console
Hyrax::Engine.after_initialize - persisting registered roles!
** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=3.3.1 framework=rails level=1 pid=45
** [Honeybadger] Development mode is enabled. Data will not be reported until you deploy your app. level=2 pid=45
/usr/local/bundle/gems/honeybadger-3.3.1/lib/honeybadger/plugin.rb:19: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/local/bundle/gems/honeybadger-3.3.1/lib/honeybadger/plugin.rb:65: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead …
```
=> Remove Honeybadger Gem

app/models/user.rb, spec/models/user_spec.rb
On a fresh checkout of hyku, I was not able to register a user on the global tenant because the
before_create callback errored when trying to add the registered role
due to a validation error on the role: `Resource type is not included in the list`
This was not caught in the tests because there wasn't a check that the
user actually got created.
=> Don't try to assign registered role on global tenant

config/cable.yml, config/redis.yml
the hyrax chart provides a `REDIS_PASSWORD`. the default configuration should
use it in production.
=> allow redis password in config

app/controllers/roles_controller.rb, app/jobs/delete_old_guests_job.rb, app/models/hyku/group.rb, app/models/user.rb, app/presenters/hyrax/admin/dashboard_presenter.rb, spec/jobs/delete_old_guests_job_spec.rb
Fixes #606 
Make sure we do not display guest users in the UI. These are created and used for Blacklight sessions, but have no value to admins or other logged in users of the system. Also prune guest users periodically.
=> set default scope for users to exclude guests, remove old guests

app/middleware/account_elevator.rb, config/initializers/carrierwave_config.rb, config/settings.yml
some file systems (nfs/samba) do not support chmod. This allows it to be disabled so carrierwave will still work on these shared drives.
=> Allow uploads to non-acl mounts like Samba or EFS

app/models/user.rb, db/schema.rb
We missed a page found here: https://share.getcloudapp.com/kpuDxy4K when doing the user scope limiting. This limits the scope of all "registered" calls to make sure there are not other missing
This work is sponsored by the British Library
=> all users where showing on admin user list instead of just the users of a given tenant

app/models/concerns/account_switch.rb, db/migrate/20210729105649_add_delivery_tracking_info_to_mailboxer_receipts.mailboxer_engine.rb, db/schema.rb
Fixes #1732 
Adds a missing migration of the Mailboxer gem that was making the email notification delivery throw a 500 error.
The migration file has been generated using the instructions at: https://github.com/mailboxer/mailboxer/issues/391
``` ruby
rails g mailboxer:install
```
* Run rails g mailboxer:install to add the missing migration file
=> Add missing Mailboxer gem migrations

Dockerfile, README.md
No slash version works on some versions of Docker, but not others, the code copy got lost in a merge. Fix both.
=> Small Docker Build Fix

docker-compose.yml
Dory needs a dot to use as a wildcard for subdomain resolution. It was sometimes working by accident because it falls back to the "first" one if no match is found.
=> Allow Dory to resolve subdomains

ops/review-deploy.tmpl.yaml
Fixes startup issue in the `load-solr-config` InitContainer for the hyrax pod due to a solr collection name mismatch. The default value is `hyrax` upstream. If it's intended to use `$CI_COMMIT_SHORT_SHA`, then we'd just need to do the opposite and set the collection name under the `solr` property.
=> (fix) solr collection name should match upstream hyrax chart default

app/views/hyrax/admin/appearances/_banner_image_form.html.erb, app/views/hyrax/admin/appearances/_default_images_form.html.erb, app/views/hyrax/admin/appearances/_directory_image_form.html.erb, app/views/hyrax/admin/appearances/_logo_image_form.html.erb
When an admin navigates to the Dashboard Settings page and clicks the Appearance tab, the help-blocks for the Logo, Banner Image, Directory Image, and Default Image say `Hint` rather than the appropriate text.
The help-block texts say `Hint` rather than the appropriate text.
The help-block texts should say the appropriate text to help the user with the setting. 
BEFORE
AFTER
**_Code Contribution courtesy of Palni-Palci_**
=> Make sure help text was mapping to the correct place in the yaml files

app/assets/stylesheets/themes/institutional_repository.scss, app/views/themes/institutional_repository/hyrax/homepage/_resource_type_slider.html.erb, spec/models/account_spec.rb
The IR theme's slider on the homepage had irregular spacing when at the medium breakpoint: this MR makes the spacing correct at all breakpoints.
https://share.getcloudapp.com/OAuneX6n
1. Go to the dashboard and change the theme for the homepage to "Institutional Repository"
2. Create a generic work and select at least 7 work types
3. Save the work and make sure it is public and approved if necessary
4. Navigate to the home page
5. Check that the resource type carousel has even spacing at all breakpoints
**_Code Contribution Courtesy of Palni-Palci_**
=> fixes the spacing for the Institutional Repository theme slider

app/assets/stylesheets/hyku.scss, spec/models/account_spec.rb
This MR makes the content on the homepage full width when the featured researcher/collection sections are toggled to off
After: How it looks when featured researcher/collection sections are off - 
https://share.getcloudapp.com/8Lu5E0nA
After: How it looks when featured researcher/collection sections are on - 
https://share.getcloudapp.com/2NulemZD
**_Code Contribution Courtesy of Palni-Palci_**
=> Fix justification on homepage

app/presenters/hyrax/collection_presenter.rb
Collection pages currently show size in KB, but it is broken and isn’t helpful. Notch8 will remove this from the application. 
BEFORE
AFTER
**_Code Contribution courtesy of Palni-Palci_**
=> Remove size from collection pages

app/views/hyrax/admin/appearances/show.html.erb, app/views/themes/cultural_repository/hyrax/homepage/_explore_collections.html.erb, app/views/themes/cultural_repository/hyrax/homepage/_featured_fields.html.erb, app/views/themes/cultural_repository/hyrax/homepage/_recent_document.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_explore_collections.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_recent_document.html.erb, spec/models/account_spec.rb
Follow up PRs for theming:
- Removes under construction labels on theme selection tab in appearance panel
- Fixes links on Neutral and Cultural repository home pages
References: #379 and #281
**_Code Contribution Courtesy of Palni-Palci_**
=> Remove under construction labels, fixed home page title links on themes

app/views/layouts/hyrax.html.erb, app/views/shared/_appearance_styles.html.erb
Custom button colors, set in the admin interface should not apply to the admin dashboard or the proprietor pages. They should only apply to user facing pages. 
This PR was sponsored by Andrews University
=> Styles should apply to non-admin pages only

app/views/themes/cultural_repository/layouts/hyrax.html.erb, app/views/themes/institutional_repository/layouts/homepage.html.erb, app/views/themes/neutral_repository/hyrax/homepage/index.html.erb
Fixes #1787 
After submitting Contact Form when a theme is applied, an error message prevents the page from loading
`undefined method 'draw_select_work_modal?' for nil:NilClass`
- This contact form page is rendering and there is no presenter. 
- Safe navigation avoids this error.
* add safe navigator to the home page themes
=> use safe nav for home page theme modal check

app/views/themes/institutional_repository/layouts/homepage.html.erb
Fixes #1787 
After submitting Contact Form when IR theme is applied, an error message prevents the page from loading
undefined method 'display_share_button?' for nil:NilClass
This contact form page is rendering and there is no presenter.
Safe navigation avoids this error.
add safe navigator to the IR home page themes
=> nil check in ir theme

Dockerfile, bin/db-migrate-seed.sh, docker-compose.yml
There have been issues with starting Hyku reliably in dev.  Solr some times has a race condition with the initialize_app job and that causes bad system states and requires domain knowledge when clearing your database. This code change fixes that while still being very fast to start up the app.
- this PR doesn't address the fact that the Bitnami Solr image is not available on M1 ARM yet and running it in qemu can be unstable.
=> Faster better cheaper solr dev upstream

app/assets/javascripts/delete_uploaded_thumbnail.js.erb, app/assets/stylesheets/hyku.scss, app/controllers/hyrax/dashboard/collections_controller.rb, app/middleware/no_cache_middleware.rb, app/services/hyrax/indexes_thumbnails.rb, app/services/uploaded_collection_thumbnail_path_service.rb, app/views/hyrax/dashboard/collections/_current_thumbnail.html.erb, app/views/hyrax/dashboard/collections/_form.html.erb, config/environments/production.rb, config/locales/hyrax.en.yml, config/routes.rb
CoAuthors: @eltiffster from uVic & @sephirothkod
Related: https://gitlab.com/notch8/britishlibrary/-/issues/260
Currently there is only a convoluted way of adding an image to the collection. Ideally would just upload an image to the collection edit page rather than be forced to created a mock work and add the image as a file to that work.
Add the ability to upload a custom thumbnail/image to a collection page
Shows the uploaded collection thumbnails saving and showing up on home page:
https://share.getcloudapp.com/GGullKPJ
=> Collection Thumbnail Uploads

app/controllers/hyrax/dashboard/collections_controller.rb
Selecting works from the collection thumbnail dropdown that do not have images attached will return a `We're sorry, something went wrong.` page. 
example:
| before | after |
| ------ | ------ |
| <img width="914" alt="Screen_Shot_2022-03-23_at_12 00 20_PM" src="https://user-images.githubusercontent.com/73361970/162271489-6107c6ee-79f1-4f43-987a-5ca011467843.png"> | <img width="923" alt="Screen_Shot_2022-03-23_at_12 04 03_PM" src="https://user-images.githubusercontent.com/73361970/162271597-c51f89ae-3b1f-42c7-a58b-acd008acc433.png"> |
* https://gitlab.com/notch8/britishlibrary/-/issues/314
=> Collection thumbnail dropdown bugs

.github/CONTRIBUTING.md, CONTRIBUTING.md
Fix inaccurate branch name references in the contributing documentation.
The CONTRIBUTING docs, while they have a note on language, still refer to a 'master' branch which doesn't exist in the repo. This simply replaces 'master' with 'main' in CONTRIBUTING.md and copies that file to .github/CONTRIBUTING.md too. There is one more ref to 'master' in the main readme.md but it's for coveralls and replacing 'main' in it doesn't fix the badge so I'm not sure whether to change it.
* Only documentation changes
I submitted an iCLA just today and am doing this work on my free time and not as part of my institution. Sorry if I didn't follow any standards, I read through the contributing doc and tried to follow it but didn't create a …
=> replace refs to 'master' branch with main

app/controllers/proprietor/accounts_controller.rb, app/views/proprietor/accounts/show.html.erb, spec/controllers/proprietor/accounts_controller_spec.rb, spec/views/proprietor/accounts/show.html.erb_spec.rb
This MR is contributed back from work conducted on behalf of the British Library by Scientist Software Services. It adds pagination to the proprietor accounts show page for "Current Account Administrators" and "All Users" tables to reduce load time.
Screenshots of what MR accomplishes:
=> add-pagination-to-proprietor-account-show-tables

app/helpers/shared_search_helper.rb, app/views/catalog/_index_header_list_default.html.erb, spec/factories/accounts.rb, spec/helpers/shared_search_helper_spec.rb
Louisville reported issues with links on the catalog pointing to single.tenant.default as the URL. This is because all page views were using the account_cname instead of just on shared search views.
=> fix single tenant catalog links

app/views/proprietor/users/_form.html.erb, app/views/proprietor/users/new.html.erb, spec/features/proprietor_spec.rb, spec/models/user_spec.rb
Fix issue 74 in UTK https://gitlab.com/notch8/utk-hyku/-/issues/74
**Summary** 
Global User form to create new users triggers a 500 error response when the email and password fields are not populated. The form did not make it clear what fields were required. 
**Changes proposed in this pull request:**
* Add required fields to email and password for `app/views/proprietor/users/_form.html.erb`
=> global user new form 500 error

app/controllers/sites_controller.rb, app/forms/hyrax/forms/admin/appearance.rb, app/helpers/hyrax_helper.rb, app/jobs/reindex_admin_sets_job.rb, app/jobs/reindex_collections_job.rb, app/jobs/reindex_works_job.rb, app/views/_logo.html.erb, app/views/hyrax/admin/appearances/_banner_image_form.html.erb, app/views/hyrax/admin/appearances/_default_images_form.html.erb, app/views/hyrax/admin/appearances/_directory_image_form.html.erb, app/views/hyrax/admin/appearances/_logo_image_form.html.erb, app/views/layouts/homepage.html.erb, app/views/themes/cultural_repository/_logo.html.erb, app/views/themes/cultural_repository/layouts/homepage.html.erb, app/views/themes/institutional_repository/_logo.html.erb, app/views/themes/institutional_repository/layouts/homepage.html.erb, app/views/themes/neutral_repository/layouts/homepage.html.erb, config/locales/simple_form.en.yml, spec/controllers/sites_controller_spec.rb, spec/helpers/hyrax_helper_spec.rb
Fixes #[utk-hyku #54](https://gitlab.com/notch8/utk-hyku/-/issues/54)
Adds:
* ability to add alternate text for images added via Appearance admin menu.
* use of alternate text for main page logo
* use of alternate text via title attribute for main page banner image
* missing reindex jobs (referenced when adding default images)
* default logo view (pulled up from hyrax) to allow use of alt text
=> Accessibility changes

app/controllers/hyrax/dashboard/collections_controller.rb, app/presenters/hyrax/collection_presenter.rb, app/views/hyrax/collections/show.html.erb, app/views/hyrax/dashboard/collections/_form_branding.html.erb, app/views/hyrax/uploads/_js_templates_branding.html.erb
The collection branding table includes a fields for alternative text, but banner doesn't allow entry of the text. The branding tab for the collection should allow entry of custom descriptive text, similarly to the way the logo does. Additionally, background images do not support alt text, so banner image should use this alt text as title rather than alt.
Fixes ticket https://gitlab.com/notch8/utk-hyku/-/issues/60
* collection banner text can be entered and edited
* collection banner text is used as title text on collection's public view if it has been entered
* modifications to branding view to correct images not appearing
=> Add alt text for collection banner

app/views/proprietor/accounts/show.html.erb
Fixes [UTK-77](https://gitlab.com/notch8/utk-hyku/-/issues/75)
Able to remove Current Account Administrators from Manage Account show page
- rename variable for clarity
- fix array logic
=> Able to remove Current Account Administrators

app/views/hyrax/collections/show.html.erb, app/views/hyrax/dashboard/collections/_show_actions.html.erb
Fixes [UTK #78: Hyku upgrade - collection's public show page's "Add to collection" button does nothing](https://gitlab.com/notch8/utk-hyku/-/issues/78)
- Corrects javascript functionality of `Add to Collection` button on the public show page. 
- Also removes duplicated count of items under title.
- Completion of function routes to the collection's show page on the dashboard. 
**Screen Shots:**
=> Fix modal functionality for collection public show

.env, app/views/hyrax/dashboard/sidebar/_repository_content.html.erb, config/initializers/bulkrax.rb, config/initializers/hyrax.rb, config/routes.rb
Fixes https://gitlab.com/notch8/utk-hyku/-/issues/76
Environment variables are strings so the conditional was not working.
* Include a commented out line for ease of use in `.env`
* rework `ENV.fetch` conditional
=> an update to fix the way #fetch evaluates env variables

.gitlab-ci.yml, app/models/endpoint.rb
FEDORA_URL has been renamed to FCREPO_URL, however we missed a few. This MR updates all instances for consistency.
=> rename fedora_url to fcrepo_url for consistency

app/views/hyrax/dashboard/collections/_form_discovery.html.erb
Fixes [UTK 94](https://gitlab.com/notch8/utk-hyku/-/issues/94)
Through radio buttons, give indicator what visibility the collection is currently set to.
* overwrite hyrax view
* add checked option to radio button
=> add checked option to radio button

app/views/proprietor/users/new.html.erb
- stop checking for `@user.errors.details[key].first[:value]` because it does not exist
- https://gitlab.com/notch8/britishlibrary/-/issues/372
=> 1837 better user error handling

app/views/themes/cultural_repository/hyrax/homepage/_featured_works.html.erb
This is contributed back work from the Palni Palci Hyku Upgrade. This update was a bug that didn't allow the admin user the ability to save the featured works list. Ticket: https://gitlab.com/notch8/palni-palci/-/issues/541
=> contribute_back_i541-featured-works-save

app/models/concerns/account_settings.rb
Adds a check for the presence of the google_analytics_id. In a staging environment, if the google_analytics_id was not available we would receive a routing error for the partials in the admin dashboard locally. I also saw errors in my local logs when account_settings.rb would use the method, `reload_library_config`, on the step of `config.google_analytics_id = google_analytics_id` it didn't matter if google_analytics_id.present? or not, the application would need to look in the analytics.yml file which is commented out, and throws an error. In a staging or production environment it gets caught in the hyrax step of the web deployment process.
Error:
```yaml
Block in reload_library_config at /app/samvera/hyrax-webapp/app/models/concerns/account_settings.rb:160
Unable to fetch any keys from …
```
=> add-clause-to-account-settings-for-google_analytics_id

app/forms/hyrax/forms/admin/appearance.rb, app/helpers/hyrax_helper.rb, app/models/content_block.rb, spec/models/content_block_spec.rb
Prior to this commit there were two very similar chunks of code regarding `ContentBlock.block_for` type logic.
With this commit, those chunks of code are consolidated.
Why the consolidation?  There's an opportunity to more aggressively cache those values.
At present, looking at the logs there are numerous singular queries of the ContentBlock structure.  (See the details block below)
Through this consolidation we can now more
easily introduce a caching and invalidation layer.
One possible caching mechanism would be on initial query to load all named blocks into an in memory array; then when we update the block we invalidate the in-memory array.
The present logging does not provide insight into the cost of each of those individual queries but that is a lot of query calls (which ActiveRecord …
=> Moving ContentBlock methods

app/views/themes/neutral_repository/_theme_container.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_featured_works.html.erb
Fixes #1865 
In Hyku main, when the Neutral Repository theme is selected, and the Featured Work feature flipper is toggled off, the Share your work button is toggled off as a side effect.
* move share your work partial outside of the featured work partial
=> moves share your work button outside of featured works partial

app/assets/stylesheets/themes/cultural_repository.scss
Fixes #1863 
In Hyku main, when the Cultural Repository theme is selected, the CSS overrides the workflow actions header to have a white background. The text is also white, so the panel is invisible to the user.
update the CSS in the Cultural Repository theme so the workflow actions panel does not have a white background with white text
=> workflow actions header color

Dockerfile
Fixes #1869 
When spinning up a new instance of Hyku, filesets are not attaching and thumbnails are not being created.
* add libreoffice to Dockerfile
=> adds libreoffice to Dockerfile

app/models/hydra/access_controls/embargo_decorator.rb, app/models/hydra/access_controls/lease_decorator.rb
Fixes #1871 
When an admin user releases an expired lease/embargo, the lease/embargo does not release to its new visibility. It should release from `Lease`/`Embargo` to `[new visibility]`. Instead, it releases from `Lease`/`Embargo` to `[old visibility]`
* add embargo decorator to fix timing issue
* add lease decorator to fix timing issue
=> fix embargo and lease date time issue

app/views/themes/neutral_repository/hyrax/homepage/_explore_collections.html.erb
Fixes #1873 
After the new Featured Collections feature was added, there were inadvertent design changes made to the Neutral Repository home page theme.
When a non-admin user views the Neutral homepage theme on new staging, the Featured Collections section has gaps of empty space.
* Adjust the css classes on the Neutral Repository home page theme partial for featured collections so the design reverts back to the intended spacing.
=> fixes neutral repo home page collections

app/controllers/catalog_controller.rb, app/search_builders/hyrax/collection_member_search_builder_decorator.rb
Fixes #1875 
When viewing a collection page, the central search bar does not return results for the content or metadata of works or sub-collections, only the titles. Optimally, this search would function just as the main search bar for each tenant does, searching the text of PDFs, and all metadata fields, but only within the collection.
* adds a decorator the includes methods to add filesets to the search on the collection show pages
* adds all_text_timv to the catalog controller search fields
=> add filesets to search for collection show page

app/views/devise/shared/_links.html.erb
Fixes #1879 
`Account#allow_signup` returns a boolean, not a string. This conditional would always return `false` due to this data type mismatch.
=> Fix sign up link not rendering

Dockerfile, worker
Contributing back
- Adds worker script with helpful developer hints.
- This script has been `chmod +x`
- The Dockerfile has been updated to call the script `CMD ./bin/worker` 
- And removes `CMD bundle exec sidekiq`
=> add-worker-script-executable-update-dockerfile-cmd

.env, app/views/hyrax/dashboard/sidebar/_activity.html.erb, config/analytics.yml
rspec spec/features/create_generic_work_spec.rb
Rspec feature test [was failing](https://app.circleci.com/pipelines/github/samvera/hyku/1162/workflows/ceb0f71c-6c6b-49cf-845b-4940bd4e0606/jobs/1250/tests#failed-test-0) due to not being able to access the dashboard because Google Analytics was enabled by default (half-setup) and no p12 file to allow the feature test to access the dashboard so adding a check to see if google analytics is setup and commenting out the analytics env variables in the env file.
- Bringing over [Hyrax fix](https://github.com/samvera/hyrax/commit/73437b8ed8d2441b7fe3bbff14e41e53922d3fdb) for not erroring the dashboard view if analytics isn't enabled yet
- Disables Google analytics in the env file on default
=> disable-analytics-env-also-dont-error-if-not-enabled

app/presenters/hyrax/iiif_manifest_presenter_decorator.rb
With all the work going in the [IIIF Print](https://github.com/scientist-softserv/iiif_print) gem, we need a way to safely override methods.  Instead of updating the `IiifManifestPresenterDecorator` with a injections from a generator, the safer approach is to check `super` to see if there's another implementation of it, in our case, coming from the IIIF Print gem.  If not then carry on as usual.
=> add conditional to account for when iiif print gem is installed

.github/CONTRIBUTING.md, .github/release.yml, .github/workflows/release_labels.yml, CONTRIBUTING.md
Borrow changelog config from [Bulkrax](https://github.com/samvera-labs/bulkrax).
This will organize listed PRs when generating release notes by using labels. 
- Add changelog template 
- Add PR label validating GitHub Action
- Include PR label instructions in contributing guidelines
=> Add release notes template

.circleci/config.yml, Gemfile, Gemfile.lock, app/controllers/hyrax/dashboard/collections_controller.rb, app/jobs/reindex_collections_job.rb, config/initializers/hyrax.rb, docker-compose.yml
This skips the very slow nested indexing and will be default behavior in Hyrax 4.0. The only downside is it will not work if the Solr Cloud shard count is > 1
=> upgrade to hyrax 3.5, make graph indexer on by default

app/presenters/hyrax/collection_presenter_decorator.rb, app/services/group_aware_role_checker.rb
Before this change, the `.terms` method was not actually being overwritten; `#prepend` does not work for class methods.
- Refactor the `CollectionPresenterDecorator` override to use `#decorate`
- Remove resolved TODO comment
=> refactor CollectionPresenterDecorator to use #decorate

app/services/roles_service.rb, spec/services/roles_service_spec.rb
Ref https://github.com/scientist-softserv/palni-palci/issues/430 
Ensure admin group gets manage access to all Collections when running `rake hyku:roles:create_collection_accesses`
If a Collection did not previously have a permission template, one would have been been created for it when running this script. Since we weren't granting admins any access before this change, admins were not able to do things like deposit works into these "broken" Collections
=> Update script grants admins manage access to Collections

Dockerfile, lib/tasks/reset.rake
This PR updates the hyrax image version to the latest in order to resolve issue where the QA gem requirements (ldpath) needed at least ruby 2.7.5 but the beta2 image was using 2.7.2
This also removes the `malloc arena max` variable from the dockerfile as the new image resolves the issue surrounding this. 
I don't believe there are any formal github issues for either of these things.
* Upgrade hyrax docker image
* remove unneeded malloc variable
=> upgrade hyrax docker image and remove malloc env var.

app/controllers/concerns/hyrax/works_controller_behavior.rb
Fixes work/edit form error flash messages
This was implemented in [atla-hyku](https://github.com/scientist-softserv/atla-hyku)
Error messages from validations in the edit-work form were appearing as blank- the message was not being parsed correctly. This PR updates the works controller behavior to make sure that these error messages are being set.
- https://github.com/scientist-softserv/atla-hyku/issues/45
- users would see a blank error message
- users will not see a blank error message at the top of the screen
<details>
<summary>Working error message for :video_embed</summary>
</details>
=> Fixes work/edit form error flash messages

app/controllers/concerns/hyrax/works_controller_behavior.rb, app/controllers/hyrax/contact_form_controller.rb, app/controllers/hyrax/homepage_controller.rb, app/controllers/hyrax/pages_controller.rb
Fixes #1949 
Running rubocops autocorrect mistakenly changes the calling of the `view_paths=` method into a variable assignment. This PR fixes a previously changed instance, and add code comments to each of the calling of the `view_paths=` method to prevent this change from happening again.
=> Adds code comment and reverts a rubocop change that breaks theming

app/views/shared/_footer.html.erb, config/locales/hyrax.de.yml, config/locales/hyrax.en.yml, config/locales/hyrax.es.yml, config/locales/hyrax.fr.yml, config/locales/hyrax.it.yml, config/locales/hyrax.pt-BR.yml, config/locales/hyrax.zh.yml
Contributed back from [Palni/Palci](https://github.com/scientist-softserv/palni-palci)
* makes the copyright year in the footer say the current year
- Ticket: https://github.com/scientist-softserv/palni-palci/issues/531
- PR: https://github.com/scientist-softserv/palni-palci/pull/539
=> Copyright year

config/application.rb
As we're moving through updates to the underlying Psych and Rails we're noticing the following errors happening:
```
Psych::DisallowedClass: Tried to load unspecified class:
ActiveSupport::HashWithIndifferentAccess
```
This relates to work done in:
- https://github.com/scientist-softserv/palni-palci/blob/02493401e92515832b054aa018332c252b768b0c/config/application.rb#L64
- https://github.com/IU-Libraries-Joint-Development/essi/blob/f187698d57c66f076b933177d481827921d89ac5/config/application.rb#L33
This is the PR for ESSI's fix: https://github.com/IU-Libraries-Joint-Development/essi/commit/c530abab1222c81aa81dc0b63f6752d38f217fae
=> 🐛 Addressing Psych::DisallowedClass error with YAML changes

app/views/_user_util_links.html.erb, app/views/themes/cultural_repository/_user_util_links.html.erb, app/views/themes/institutional_repository/_user_util_links.html.erb
Prior to this commit, if we remove the User's `devise registerable` configuration we would encounter an error with the path methods not existing.  With this change, we allow for disabling of the registerable feature; in a Devise friendly manner.
We could look to the below view and extract a helper method for this. But this seems to be a path of least problem.
From `app/views/devise/shared/_links.html.erb`:
```
<%- if devise_mapping.registerable? && controller_name != 'registrations' && !Account.global_tenant? && current_account.try(:allow_signup) %>
<%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end -%>
```
The `devise_mapping` method is `Devise.mappings[<key>]`; and in this case that key is `:user`.  See …
=> 🐛 Adding conditional when Devise is non-registerable

.circleci/config.yml, Gemfile, Gemfile.lock, spec/rails_helper.rb
The changes of this PR will modify the gemfile to downgrade Sidekiq 7 to version 6 as Redis is currently on version 5. Sidekiq 7 requires Redis version 6, and depends on the redis-client gem. Redis-client does not get introduced until Redis version 6.
=> Downgrade sidekiq until redis is upgraded

Gemfile.lock, app/assets/javascripts/hyrax/app.js.erb, app/presenters/hyku/collapsable_section_presenter.rb, app/presenters/hyku/menu_presenter.rb, app/views/_logo.html.erb, app/views/hyrax/collections/_media_display.html.erb, app/views/hyrax/dashboard/_sidebar.html.erb, app/views/hyrax/dashboard/collections/_list_collections.html.erb, app/views/hyrax/dashboard/sidebar/_activity.html.erb, app/views/hyrax/dashboard/sidebar/_configuration.html.erb, app/views/hyrax/dashboard/sidebar/_repository_content.html.erb, app/views/hyrax/dashboard/sidebar/_tasks.html.erb, app/views/hyrax/dashboard/works/_list_works.html.erb, app/views/hyrax/my/collections/_list_collections.html.erb, app/views/hyrax/my/works/_list_works.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/hyrax.de.yml, config/locales/hyrax.en.yml, config/locales/hyrax.es.yml, config/locales/hyrax.fr.yml, config/locales/hyrax.it.yml, config/locales/hyrax.pt-BR.yml, config/locales/hyrax.zh.yml, config/locales/it.yml, config/locales/pt-BR.yml, config/locales/zh.yml, spec/presenters/hyku/menu_presenter_spec.rb
refs https://github.com/scientist-softserv/utk-hyku/issues/489
This PR will bring in accessibility changes from UTK which includes:
- making the admin dashboard sidebar automatically collapse at screen widths under 768px
- adding title attributes to all sidebar links
- ensure that the custom alt text will be displayed for collection and work thumbnail images
- update translations
Relevant PR's
- https://github.com/scientist-softserv/utk-hyku/pull/519
- https://github.com/scientist-softserv/utk-hyku/pull/505
- https://github.com/scientist-softserv/utk-hyku/pull/469
=> Improve accessibility

README.md
during summer's samvera workshop two people were using windows machines and couldn't access hyku.test. these instructions are based on what rory instructed william fyson to do in order to make his setup work.
related:
- https://github.com/scientist-softserv/softserv-training-workshops-2023/pull/4
add instructions for accessing hyku.test on windows machines
=> startup on windows

config/locales/devise_invitable.de.yml, config/locales/devise_invitable.en.yml, config/locales/devise_invitable.es.yml, config/locales/devise_invitable.fr.yml, config/locales/devise_invitable.it.yml, config/locales/devise_invitable.pt-BR.yml, config/locales/devise_invitable.zh.yml
Fixes #1998
When a new user receives an email to activate their account, the email has a <br /> tag in it. We have received a lot of reports of these emails going to spam and this could be a contributing factor.
removes the `<br />` tag from the email text in each of the locale files
=> User invite email has html tag

app/controllers/hyrax/admin/appearances_controller.rb, config/application.rb
Prior to this commit, we were looking for themes yaml files relative to the directory of the spawning script.  For Hyku that was always the `Rails.root` directory.  However, when running specs in Knapsack, that directory was `Knapsack::Engine.root`.
This unearthed a potential configuration issue; namely that we want Knapsack's to control what themes are available, meaning we don't want to require amending Hyku's themes.
So, we introduce a mechanism for looking up files first in the Knapsack then in Hyku.
I discovered this bug in the specs for knapsack (below is the *Error stack trace*)
<details>
<summary>Error stack trace</summary>
```
2) Hyrax::Admin::AppearancesController with an administrator GET #show assigns the requested site as @site
Failure/Error: get :show, params: {} …
```
=> ♻️ Add handling for Knapsack theme overrides

app/services/uploaded_collection_thumbnail_path_service.rb, app/views/hyrax/dashboard/collections/_current_thumbnail.html.erb
Given the existence of Knapsack we need to consider how overrides in Knapsack will take precedence over Hyku files.  This change handles cases where we want to use the Knapsack's uploaded thumbnails.
Related to:
- #2010
=> ♻️ Favor Hyku::Application.path_for over Rails.root

app/controllers/hyrax/contact_form_controller.rb
Previously there was a bug because even if you typed in a subject, the contact form would error saying that it was blank.
Part of issue:
- https://github.com/scientist-softserv/adventist-dl/issues/608
=> :bug: subject can't be blank for the contact form

app/forms/hyrax/forms/admin/appearance.rb, app/services/uploaded_collection_thumbnail_path_service.rb, app/views/hyrax/admin/appearances/_default_colors_form.html.erb, app/views/hyrax/admin/appearances/_default_fonts_form.html.erb, spec/forms/hyrax/forms/admin/appearance_spec.rb
In Adventist, we're needing to override the constant's values.  By
making this a class_attribute we can more readily do the override via
configuration instead of obliteration of a constant.
=> ♻️ Favor class_attribute over constant

app/views/layouts/application.html.erb, config/application.rb, spec/config/application_spec.rb
Prior to this commit, we hard-coded the page title; this is something
that should be far more configurable.  And this refactor is a step
towards that.
This also allows for downstream implementors to not have to override the
view simply to change the title element.
=> ♻️ Favor configurable html head title value

.rubocop.yml, app/services/uploaded_collection_thumbnail_path_service.rb, app/views/records/show_fields/_license.html.erb
Prior to this commit, the License would render as a plain URL.  With
this change, we are now coercing the license into a URL that is labeled
and titled with the name of the license.
This is copied and modified based on [Rights show partial][1]
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/620
<details aria-hidden="true"><summary>Screenshot of Before Changes</summary>
</details>
<details aria-hidden="true"><summary>Screenshot of After Changes</summary>
</details>
[1]: https://github.com/samvera/hyrax/blob/b334e186e77691d7da8ed59ff27f091be1c2a700/app/views/records/show_fields/_rights.html.erb
=> 🐛 Add custom rendering for license

app/models/user.rb, config/application.rb, spec/config/application_spec.rb
For Adventist, we wanted to disable registration of accounts as this was
creating a case where folks were creating their own accounts and
tenants.
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/492
- https://github.com/scientist-softserv/adventist-dl/issues/618
- https://github.com/samvera/hyku/pull/1964
- https://github.com/scientist-softserv/adventist-dl/pull/493
=> ♻️ Add option to override devise configuration

app/assets/javascripts/admin_font_select.js, app/assets/javascripts/application.js
In the Settings > Appearance> Font tab, the input fields for body and header fonts were getting rendered twice.  We had duplicate code in two different files that called fontselect() on both elements. Because JS was getting called twice, two input fields were displayed. Removing one of them resolves the issue.
Fixes Issue:
- https://github.com/scientist-softserv/adventist-dl/issues/590
=> :bug: font inputs rendered twice fix

Dockerfile
Because assets were done in ONBUILD they always got compiled before the knapsack was mounted. This prevented knapsack assets from getting precompiled properly.
=> run asset build later in process to allow knapsack to run it only one time

app/controllers/hyrax/my/works_controller_decorator.rb
Prior to this commit, when you were on page 2 of your works and selected
a work to add to a collection, the query for available collections would
use the page 2 as part of the collection query.  This would mean the
first 100 collections (default page size) that you had access to add
works to were skipped.
With this commit, we omit the query parameters from the works page and
then query collections.
Related to:
- https://github.com/samvera/hyrax/pull/5972
- https://github.com/samvera/hyrax/issues/5969
- https://github.com/scientist-softserv/adventist-dl/issues/625
Co-authored-by: LaRita Robinson <larita@scientist.com>
=> 🐛 Fix Add to Collection for page 2+ of works

app/controllers/hyku/invitations_controller.rb, spec/controllers/hyku/invitations_controller_spec.rb
Ref 
- https://github.com/scientist-softserv/palni-palci/issues/813 
- https://github.com/scientist-softserv/palni-palci/pull/856 
Trying to add a user active in other repositories to another tenant does not return any error but does not add the user. 
* Always add invited users to the tenant's Registered Users group 
1. Login as a super admin 
2. Create a new tenant (e.g. `Tenant A`)
3. Navigate to `Tenant A` > Dashboard > Manage Users 
4. Invite a new user who does not already exist in the **application** (i.e. across all tenants, not just one) 
5. Verify that the new user gets added to the Registered Users group in `Tenant A` 
6. Create a new tenant (e.g. `Tenant B`) 
7. Navigate to `Tenant B` > Dashboard > Manage Users 
8. Invite the same user …
=> Inviting existing users fails

config/initializers/hyrax.rb, config/locales/simple_form.en.yml
The account setting's descriptions for contact_email and contact_email_to are confusing. This PR adds clarity to these configuration options. c/o Palni-Palci
TODO: run translations
=> 🧹 Update contact email descriptions

app/views/hyrax/dashboard/collections/_current_thumbnail.html.erb
Typo from https://github.com/samvera/hyku/pull/2012 broke collection thumbnail uploading.
=> 🐛 Change Hyky to Hyku

config/locales/simple_form.de.yml, config/locales/simple_form.en.yml, config/locales/simple_form.es.yml, config/locales/simple_form.fr.yml, config/locales/simple_form.it.yml, config/locales/simple_form.pt-BR.yml, config/locales/simple_form.zh.yml
I previously mixed up the descriptions between the two which introduced a bug. This commit corrects that mistake.
=> :bug: Correct contact_email and contact_email_to descriptions

app/models/concerns/hyrax/ability/work_ability.rb, spec/features/create_work_spec.rb
We implemented a fix for this bug in PALS and are contributing it back to Hyku.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/864
Prior to this commit, even if a user was granted the role of depositor to an admin set, they could not add a work.  If they were added in a group that had the depositor role, they still were not able to create a work.
Now, users who have the depositor role or in a group with the depositor role can deposit to admin sets.
https://github.com/scientist-softserv/palni-palci/assets/19597776/dcb324fa-02f5-4743-a804-ea18709bce73
By default Hyku doesn’t actually include everyone_can_create_curation_concerns in the ability logic. It’s behind an [ENV-controlled feature flipper](https://github.com/samvera/hyku/blob/main/app/models/ability.rb#L22-L24), …
=> :bug: Fix depositor role issue

app/views/layouts/application.html.erb, app/views/themes/institutional_repository/hyrax/homepage/_resource_type_slider.html.erb
Before this commit, when the user is at the homepage, then navigating away from it, then back to it, the slider icons would duplicate.  This PR will disable turbolinks caching for the slider partial to fix it.
Additionally this PR makes the icons clickable, which provides an intuitive action for the user. When you click on the links it will perform a facet search.
Ref:
- https://github.com/scientist-softserv/palni-palci/issues/277
- https://github.com/scientist-softserv/palni-palci/issues/842
DEMO: https://share.zight.com/E0um94El
Duplicate icon fixed: 
Icons perform facet search on click: 
The duplicate icons were only occurring when the carousel was activated by adding more icons in there.
=> 🐛 Fix duplicating slider icons in IR theme

.env
The same variable is defined two lines above and has a value, so I assume that is the correct one.
[The commit that added this duplicate](https://github.com/samvera/hyku/commit/ff2888faddd5bd97a5a74dbe532ea46aa97ea5e6) mentions various improvements (Bulkrax, Docker build, etc). Does removing the empty var break any of that? Should the var with a value be removed instead?
=> remove duplicate JAVA_OPTS env var

app/controllers/hyrax/my/works_controller_decorator.rb
b4e2d6a86f5efc49d0d10709fc5323a3d49fe498
Prior to this commit, when you were on page 2 of your works and selected
a work to add to a collection, the query for available collections would
use the page 2 as part of the collection query.  This would mean the
first 100 collections (default page size) that you had access to add
works to were skipped.
With this commit, we omit the query parameters from the works page and
then query collections.
Related to:
- https://github.com/samvera/hyrax/pull/5972
- https://github.com/samvera/hyrax/issues/5969
- https://github.com/scientist-softserv/adventist-dl/issues/625
Co-authored-by: LaRita Robinson <larita@scientist.com>
e201df00d26dcd43b2b1be6bef4f49beae7b6c1e
Related to:
- https://github.com/samvera/hyku/pull/2023/files
- …
=> Collection service backport

app/models/generic_work.rb, app/models/image.rb
In order to turn IIIF Print on, you need to set HYKU_IIIF_PRINT=true in your environment. This feature should be considered experimental and will be refined and changed significantly in a future release.
=> make iiif print off by default so we can mark it as an experimental feature

Gemfile, Gemfile.lock, db/schema.rb
Pinning the json-canonicalization to 0.3.1
gem 'json-canonicalization', "0.3.1"
=> pin-json-canonicalization-0.3.1

app/controllers/concerns/hyrax/works_controller_behavior.rb, app/controllers/hyrax/contact_form_controller.rb, app/controllers/hyrax/pages_controller.rb, config/application.rb
♻️ Introduce Hyku::Application.theme_view_path_roots
With the introduction of [HykuKnapsack][1], we are adjusting how we
create instances of Hyku.  Namely we don't clone Hyku but instead we
incorporate Hyku as a submodule into a Knapsack.
The Knapsack is a Rails engine that is mounted in the Hyku application.
What this means is that when we want to
Prior to this commit, the only way to adjust themed views would have
been to add them to the Rails application (e.g. Hyku) directly.  Which
would work in a non-Knapsack ecosystem.
However, with Knapsack we need a means of saying "Hey, for themes we
want to be able to add/adjust views within the knapsack."  Hence this
change.
[1]: https://github.com/samvera-labs/hyku_knapsack
=> ♻️ Introduce Hyku::Application.theme_view_path_roots

app/controllers/hyrax/contact_form_controller.rb, app/controllers/hyrax/homepage_controller.rb, app/controllers/hyrax/pages_controller.rb, app/controllers/search_history_controller.rb
removes the deprecated blacklight code allows the specs to run. We should consider if finding a replacement is necessary in the following ticket:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/54
- 
or the fix may be caught when we resolve failing specs
Issue:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/35
=> 🧹 Remove deprecated Blacklight code

bin/web, bin/worker
Rails provides [`Object#present?`][1], which is a method that is not
generally available in Ruby.  However in the changed context, the
scripts do not have access to Rails methods.
By using this adjusted approach we favor baseline Ruby methods.
[1]: https://api.rubyonrails.org/classes/Object.html#method-i-present-3F
=> 🧹 Avoid `#present?` in non-Rails situations

app/controllers/hyrax/homepage_controller.rb, app/views/themes/cultural_repository/layouts/hyrax.html.erb, app/views/themes/institutional_repository/layouts/hyrax.html.erb, spec/controllers/hyrax/homepage_controller_spec.rb
Refactor homepage controller to more closely align with Hyrax's homepage controller.
Adjust theme views to render `modal` instead of `ajax_modal`.
refs: https://github.com/scientist-softserv/hykuup_knapsack/issues/56
=> 🧹 Get Controller specs passing

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
Update Catalog Controller & fix broken spec
Refs https://github.com/scientist-softserv/hykuup_knapsack/issues/56
=> 🧹 Hyrax 5 catalog controller and specs

db/migrate/20231215215705_create_hyrax_counter_metrics.hyrax.rb, db/migrate/20231215215706_change_work_id_to_string.hyrax.rb, db/migrate/20231215215707_add_indices_to_hyrax_counter_metrics.hyrax.rb, db/migrate/20231215215708_add_fields_to_counter_metric.hyrax.rb, db/schema.rb
For table hyrax_counter_metrics (a sushi table)
=> Hyrax 5 upgrade db migrations

Gemfile.lock
Bring in most recent changes from double_combo branch.
=> Update hyrax double combo

app/models/concerns/account_settings.rb
Prior to this commit, we were casting the value to string.  However Hyrax attempts to do division on that string.
See https://github.com/samvera/hyrax/blob/b7891b758411c59f71ff54212e0d250fcc47e35f/app/views/hyrax/base/_form_files.html.erb#L6-L15
=> 🐛 Ensure :maxFileSize is integer

config/initializers/hyrax.rb
The encountered error was:
```
NoMethodError:
undefined method `split' for #<Valkyrie::ID:0x0000ffffa5f04bc8
@id="admin_set/default">
```
=> 🧹 Fix issue regarding Valkyrie::Identifier

spec/requests/work_approval_permissions_spec.rb
The Sipity conversion methods are now explicit functions (much like the `Array()` function).
- https://github.com/samvera/hyrax/blob/5aaa568d348a180add2a1337d9d794b740703df8/app/models/sipity.rb#L20
=> 🧹 Favor Sipity::Entity function over to_sipity_entity

.circleci/config.yml
Prior to this commit, we were seeing the following failure:
> Failure/Error: Site.application\_name || super
>
> ActionView::Template::Error:
>  Permission denied @ dir\_s\_mkdir - /app
The `Account#setup_tenant_cache` sets the cache\_store to be `ENV.fetch('HYKU_CACHE_ROOT', '/app/samvera/file_cache')`.  When I locally chanced it to `/blorg/samvera/file_cache` I could repeat the error.
With this commit, we're setting the cache value for the CircleCI run.
Why was it previously working?  Perhaps because
`Account#setup_tenant_cache` never got called due to other configurations?  There is a guard clause around the method call.
=> 🤖 Specify Cache Root

spec/services/create_account_spec.rb
In the following commit, we removed the deprecated
`AdminSet.find_or_create_default_admin_set_id`:
- https://github.com/samvera/hyrax/commit/863c4bc177702b3aa00ad01f93e7a3d214bb2d73
This commit follows the advice of the deprecation warning and now favors
the `Hyrax::AdminSetCreateService.find_or_create_default_admin_set.id`
method call.
Related to:
- https://github.com/samvera/hyrax/pull/6203
=> 🧹 Update spec to reflect AdminSet default behavior

spec/features/collection_type_spec.rb
There are three major changes:
1. Favor setting `collection_type` attribute instead of
`collection_type_gid`
2. Change `#collections?` to `#collections#any?`
3. Change CSS selector based on Bootstrap upgrade
The above changes are related to work done in:
- https://github.com/samvera/hyrax/pull/5730
- https://github.com/samvera/hyrax/pull/5742
- https://github.com/samvera/hyrax/pull/4701
See:
- https://github.com/samvera/hyrax/commit/eb6e04e312b039a65ef58b1781fa112fd93f2c0c
- https://github.com/samvera/hyrax/commit/237c0c63297df05b9d483a15b212900c2323a455
- https://github.com/samvera/hyrax/commit/280664bd6b0e59c2e10795151f0afcec91b9c15b
=> 🤖 Fix spec/features/collection_type_spec.rb

.circleci/config.yml
Lock chromedriver version
[Orb 1.4.6](https://github.com/CircleCI-Public/browser-tools-orb/pull/96) release was supposed to fix this but we are once again seeing the error, so we are attempting to lock the chrome version to bypass this error. 
The error message in the tools is attempting to use URL: https://chromedriver.storage.googleapis.com/index.html
Newer versions of chrome are not supported at this URL.
=> Lock chromedriver version

spec/models/redis_endpoint_spec.rb
These tests weren't verifying that we could reach Redis; they were
testing the interface of the `RedisEndpoint#ping` by mocking the
instance.
This commit changes the mocking by avoiding a call to
`Hyrax::RedisEventStore.instance` which was raising a Redis connection
error.
Again, this test is not is redis connecting but "assume we are trying to
connect to redis now demonstrate ping."
=> 🤖 Fix stub methods to pass tests

app/forms/hyrax/forms/workflow_responsibility_form_decorator.rb, app/forms/hyrax/forms/workflow_responsibility_group_form.rb
Prior to this commit, the specs failed because of the introduction of
the WorkflowResponsibilityFormDecorator.  The decorator extracted prior
logic from Hyrax::Admin::WorkflowRolesController.
In copying that logic we introduced a subtle bug.  Namely, we favored
the original `.new` behavior if and only if you provided a `:user_id`.
This broke places where we instantiated the form in a
view (e.g. `./app/views/hyrax/admin/workflow_roles/index.html.erb`).
With this change, we make the behavior of `.new` fail towards its
"normal" implementation and instead rely on the presence of an attribute
to switch to a different form instantatior.
See Commit:
- https://github.com/samvera/hyku/commit/095edca9a50e647eb1b3ee31a34711c32151912e
Related to:
- https://github.com/samvera/hyku/pull/2079 …
=> 🧹 Fix `./spec/requests/admin_dashboard_spec.rb` spec

app/actors/hyrax/environment_decorator.rb, spec/actors/hyrax/environment_decorator_spec.rb
Just found one actor that was overriding Hyrax.  This commit will switch
it to a decorator.
Ref:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/44
=> 🧹 Clean up actors

config/initializers/redis_config.rb, spec/features/admin_dashboard_spec.rb
Prior to this commit, when looking at the
`Hyrax::RedisEventStore.instance` we saw it's connection information as:
`#<Redis client v4.8.1 for redis://localhost:6379/0>`
We were expecting the connection to be the following:
`#<Redis client v4.8.1 for redis://redis:6379/0>`
What we were seeing in tests is when we hit the redis connection we were
getting an error about not being able to connect to 127.0.0.1:6379 (e.g.
localhost).
With this commit, we have a clear connection to Redis.
See Redis Config initializer:
- https://github.com/samvera/hyrax/blob/966951ffaa72524e4a775f8a198bd51a47ece7d9/lib/generators/hyrax/templates/config/initializers/redis_config.rb#L1-L10
Co-authored-by: Kirk Wang <kirk.wang@scientist.com>
=> 🎁 Upgrade Redis initializer to Hyrax 5's gen version

Gemfile, Gemfile.lock, app/models/account.rb, app/models/fcrepo_endpoint.rb, app/models/redis_endpoint.rb, app/models/solr_endpoint.rb, spec/jobs/cleanup_account_job_spec.rb, spec/models/account_spec.rb, spec/models/fcrepo_endpoint_spec.rb, spec/models/redis_endpoint_spec.rb, spec/models/solr_endpoint_spec.rb
13775d6c2e1c5d80c135316e4760abc994668f8e
We're not concerned with where the cached file is for testing purposes;
so instead of hard-coding a value that can change in the ENV, let's
compare the constant that we use in the code.
tl;dr - Don't rely on magic strings
0dbddad8acb132e40b8c72405c69ef74bed0bb8e
The `CleanupAccountJob` was stubbing very nosily; needing to know too
much about implementation details of the end-points.  Instead this
preserves the over-view spec (e.g. what all the cleanup spec actually
cleans up) while moving that nosy logic to the constituent endpoint.
Most of these specs are testing that the method chains work; which is
perhaps adequate as the other option is far more expensive tests (e.g.
make a new Fedora node only to then immediately destroy it)
I'm also …
=> Hyrax 5 upgrade spec fixing

spec/views/hyrax/dashboard/collections/_form_share.erb_spec.rb
The partials rendered in the tested view assume that we've set a
collection type.
=> 🧹 Assigning collection_type

app/views/themes/institutional_repository/_masthead.html.erb, spec/features/appearance_theme_spec.rb, spec/features/cultural_repository_theme_spec.rb, spec/features/institutional_repository_theme_spec.rb
The selector was *very* specific, and with the HTML class changes for
Bootstrap 3 to 4, this almost certainly broke.
Note, there are still underlying issues with two other specs; there
errors are listed below:
```
1) Admin can select home page theme when a search results theme is
selected updates the search results page with the selected layout view
Failure/Error: super
ActionView::Template::Error:
undefined method `with_collection' for nil:NilClass
```
=> 🧹 Narrow specificity of CSS selector

app/controllers/catalog_controller.rb
Blacklight 7.35.0 's default document_component is `nil`, see:
- https://github.com/projectblacklight/blacklight/blob/ac5fa8b300c5ad5c35b1663ef0f15372ffa2be0f/lib/blacklight/configuration.rb#L213
- https://github.com/projectblacklight/blacklight/blob/ac5fa8b300c5ad5c35b1663ef0f15372ffa2be0f/lib/blacklight/configuration.rb#L186
Digging around in the wiki, you might find (only found because I cloned the repo):
- https://github.com/projectblacklight/blacklight/wiki/Configuration---Results-View
Related to:
- https://github.com/projectblacklight/blacklight/pull/2317
=> 🐛 Adding document_component to blacklight's config

spec/rails_helper.rb
Hyrax has :clean_repo and Hyku has :clean
Sometimes folks copy over specs from Hyrax, and bring along the :clean_repo; which looks like it should work.
With this commit, we bring that logic along!
Fixes #issuenumber ; refs #issuenumber
=> 🧹 Allow :clean or :clean_repo to work for the cleaners

Gemfile, app/models/featured_collection_list.rb, lib/tasks/tenantize_task.rake, spec/factories/collections.rb, spec/features/admin_set_form_participants_tab_spec.rb, spec/features/appearance_theme_spec.rb, spec/features/collection_editor_role_spec.rb, spec/features/collection_manager_role_spec.rb, spec/features/collection_reader_role_spec.rb, spec/features/create_generic_work_spec.rb, spec/features/create_image_spec.rb, spec/features/institutional_repository_theme_spec.rb, spec/features/work_editor_role_spec.rb, spec/features/work_search_institution_visibility_spec.rb, spec/features/work_show_institution_visibility_spec.rb, spec/features/work_show_open_visibility_spec.rb, spec/features/work_show_private_visibility_spec.rb, spec/models/uploaded_file_spec.rb, spec/requests/work_show_institution_visibility_spec.rb, spec/routing/featured_collections_route_spec.rb
Rubocop seams to prefer the Layout namespace for LineLength.
=> 🧹 Favor Layout/LineLength over Metrics/LineLength

spec/features/cultural_repository_theme_spec.rb, spec/jobs/create_default_admin_set_job_spec.rb
Checking the HTML (on the CircleCI SSH environment), it appears that the selector should work in test.  But it is not.  So I'm removing the specificity.
=> 🧹 The selector is not working

spec/rails_helper.rb
Prior to this commit, we did not automatically clean the features.  The
below ripgrep (and output) shows that there were some features which did
not start from a clean state.
```
rg "(clean|clean_repo):" spec/features --files-without-match
``
```
spec/features/accounts_spec.rb
spec/features/proprietor_spec.rb
spec/features/featured_collections_spec.rb
spec/features/user_roles_spec.rb
spec/features/oai_pmh_spec.rb
```
=> 🧹 Ensure feature specs run clean

app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb, config/application.rb, spec/config/application_spec.rb
Dear reviewer, put on your reading glasses.
This commit looks at the newly refactored
`Hyrax::IiifAv::DisplaysContentDecorator` as well as the current state
of [PALS's Hyrax::IiifAv::DisplaysContentDecorator][1] and attempts to
account for the variances between the two by introducing configurations.
Yes, we could port this to the hyrax-iiif_av gem, but for now that would
not solve the underlying issue of how we've been handling things.
Why the Hyku::Application class attribute?  Because the decorator is
being mixed into a module, which does not response to `.class_attribute`
methods.
[1]: https://github.com/scientist-softserv/palni-palci/blob/8754556c0225ce9f04674c1ffac6403586fd65f4/app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb
=> Prime hyrax 5 upgrade refactor for pals

config/application.rb
We add our local config locale directory to the I18n.load_path so that our local files take precendence over the ones found in our gems.
Related issue:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/55
=> 🧹 Change locale file load order so that our local files are prioritized

Gemfile, Gemfile.lock, ops/exiftool_image_to_fits.xslt
We were not seeing images loading correctly in the UV because we introduced the `Hyku::WorksControllerBehavior` and IIIF Print did not know about it.
- https://github.com/scientist-softserv/iiif_print/commit/cad2cf33fc07ec2abb5b6834a858b5ed74903c12
We were seeing a respon to mismatch error in the Hyrax IIIF AV.
- https://github.com/samvera-labs/hyrax-iiif_av/commit/4723b8fd0961fa179caf787532bd7922a44957ec
Also, the image that I tested was a phone image that apparently had different ExifImageHeight/ExifImageWidth values than the ImageHeight/ImageWidth values.  This was probably because modern phones typically generate multiple images so the user can choose the best shot. The exiftool_image_to_fits.xslt was proritizing the Exif values over the regular values and would cause our image …
=> 🧹 Update IIIF Print and AV gems

app/services/hyrax/file_set_derivatives_service_decorator.rb
In a previous commit we created the
`Hyrax::FileSetDerivativesServiceDecorator` to override the default thumbnails that Hyrax uses but I forgot to add the video thumbnail, which is fixed here.
Ref
- https://github.com/scientist-softserv/hykuup_knapsack/issues/69
=> 🐛 Fix video thumbnail generation

app/assets/javascripts/hyrax/app.js.erb, app/assets/stylesheets/hyku.scss, app/views/hyrax/dashboard/collections/_show_document_list_row.html.erb, app/views/hyrax/dashboard/works/_list_works.html.erb, app/views/hyrax/homepage/_home_content.html.erb, app/views/hyrax/my/works/_list_works.html.erb, spec/rails_helper.rb
f802001ad74461bd19b245f332dccf803f6c8403
e15b2dd5cd5027eea355aaa3ee592b346f7ead6d
This commit will change the maximized size to match Bootstrap 4 break
points.  Also, added btn-secondary to hyku.css so it doesn't get
overriden by appearance styles.  Finally, restructured the homepage to
make it look more like Hyrax 5.
=> Hyrax 5 fix css

app/controllers/application_controller.rb, app/controllers/proprietor/users_controller.rb, app/models/hyrax/group.rb, app/models/user.rb, app/services/group_aware_role_checker.rb, app/services/hyrax/workflow/permission_grantor.rb, app/views/proprietor/users/_form.html.erb, app/views/proprietor/users/index.html.erb, config/locales/en.yml, config/routes.rb, spec/models/hyrax/group_spec.rb
This check was originally disabled in order to get specs passing with minimal code changes. Now that specs are running, the corrections can safely be made to appease rubocop.
=> 🧹 Addresses Hyrax 5 PR feedback: Rubocop Naming/PredicateName errors

app/assets/stylesheets/hyku.scss, app/forms/generic_work_resource_form.rb, app/forms/image_resource_form.rb, config/metadata/basic_metadata.yaml, config/metadata/image_resource.yaml
This commit will:
- add extent to the image resource and form
- override basic_metadata to show bibliographic_citation on forms
- change PcdmObjectForm to ResourceForm because it was throwing errors
- add bolding to labels on forms
Also:
- Indexers were examined and no changes were needed
- Presenters don't seem to be a default thing for Valkyrie works
- Controllers were examined and no changes were needed
- Views were examined and no changes were needed
- Localizations don't seem to be a default thing for Valkyrie works
Ref:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/85
- https://github.com/scientist-softserv/hykuup_knapsack/issues/87
- https://github.com/scientist-softserv/hykuup_knapsack/issues/88
- https://github.com/scientist-softserv/hykuup_knapsack/issues/89
- …
=> 🧹 Get model mappings all in place

Gemfile.lock, app/models/solr_endpoint.rb, app/services/hyrax/custom_queries/find_by_bulkrax_identifier.rb, app/services/wings/custom_queries/find_by_bulkrax_identifier.rb, config/initializers/wings.rb, db/migrate/20240104192407_enable_uuid_extension.valkyrie_engine.rb, db/migrate/20240104192408_create_orm_resources.valkyrie_engine.rb, db/migrate/20240104192409_add_model_type_to_orm_resources.valkyrie_engine.rb, db/migrate/20240104192410_change_model_type_to_internal_model.valkyrie_engine.rb, db/migrate/20240104192411_create_path_gin_index.valkyrie_engine.rb, db/migrate/20240104192412_create_internal_resource_index.valkyrie_engine.rb, db/migrate/20240104192413_create_updated_at_index.valkyrie_engine.rb, db/migrate/20240104192414_add_optimistic_locking_to_orm_resources.valkyrie_engine.rb, db/schema.rb, lib/hyrax/solr_service_decorator.rb
07a174279fd31a54195ce6714249c5d31613ed0d
This copies over the a modified wings initializer from AMS.  It also
runs the migrations for the Valkyrie engine.
```sh
bundle exec rails valkyrie_engine:install:migrations
bundle exec rails db:migrate
```
12f86060fbc5aa99924aedf5f0678023d984e5f5
The problem we're facing is that the Valkyrie::IndexingAdapter registers
the Valkyrie::Indexing::Solr::IndexingAdapter as the default adapter,
however, this does not work in a multi-tenant environment.  The 'core'
is set to 'hyrax-valkyrie' and it needs to be the tenant's ID.  Also the
connection url needs the username and password in it.
See:
- https://github.com/samvera/hyrax/blob/double_combo/lib/valkyrie/indexing/solr/indexing_adapter.rb#L71
- …
=> I35 valkyrize hyku wings

lib/hyrax/solr_service_decorator.rb
The proprietor page hits the solr service decorator, which was throwing and error because valkyrie_index is not defined there.  We're adding a check to avoid the error.
=> 🐛 Proprietor page solr service fix

bin/helm_deploy, ops/demo-deploy.tmpl.yaml, ops/iiif-deploy.tmpl.yaml, ops/review-deploy.tmpl.yaml, ops/staging-deploy.tmpl.yaml
After making the changes to test if it works:
```sh
helm pull --untar oci://ghcr.io/samvera/charts/hyrax --version 3.5.1
touch .env.demo
dotenv -f .env.demo envsubst < ops/demo-deploy.tmpl.yaml > ops/demo-deploy.yaml
helm template --values ops/demo-deploy.yaml hyrax
rm -rf hyrax # you'll have a lot of untracked files so remove the bulk of them them with this
```
=> 🤖 Update charts for deploy

app/controllers/saved_searches_controller.rb, config/storage.yml
Removes SaveSearchesController as it is not longer supported. Blacklight::SavedSearched was removed in v7+ Adds storage.yml, a required file to boot up in production.
ref:
- https://github.com/projectblacklight/blacklight/wiki/Saved-Searches
- https://github.com/projectblacklight/blacklight/pull/1736
Issue 
- https://github.com/scientist-softserv/hykuup_knapsack/issues/78
=> 🎁 fixes to unblock deploys

app/indexers/concerns/hyku_indexing.rb, app/models/solr_document.rb
This commit will make sure that the set child flag transaction fires when ingesting with Bulkrax.  Also fixed a weird bug where the extra space in the query was causing the query to fail.
TODO: update gemfile.lock once the following gets merged
Issue: 
- https://github.com/scientist-softserv/hykuup_knapsack/issues/143
=> 🧹 Fix relationship links

.rubocop.yml, app/controllers/hyrax/dashboard/collections_controller_decorator.rb
A hyrax bug made it into Hyku via the collections controller decorator. This removes the unnecessary `collection_params method`.
Refs
- https://github.com/scientist-softserv/hykuup_knapsack/issues/183
- https://github.com/samvera/hyrax/commit/7add21367fb551174b07ba13803c16e5bd132458
=> 🐛 Fix collection membership bug

app/controllers/sites_controller.rb, app/jobs/reindex_admin_sets_job.rb, app/jobs/reindex_collections_job.rb, app/jobs/reindex_file_sets_job.rb, app/jobs/reindex_item_job.rb, app/jobs/reindex_works_job.rb
- Addresses all reindex jobs to ensure that they will work for either valkyrie or active fedora objects.
- Ensures that works and collections are appropriately reindexed as default work and collection images are added OR removed (previously, reindexing didn't occur with removal of default images, resulting in works displaying with a missing image.)
Refs https://github.com/scientist-softserv/hykuup_knapsack/issues/35
=> Valkyrize Reindex jobs

Gemfile.lock
The knapsack will require these gems from bundler.d instead of forcing hyku to care about them.
=> remove sentry dependencies

Gemfile.lock, app/forms/generic_work_resource_form.rb, app/forms/image_resource_form.rb, app/helpers/pdf_js_helper.rb, app/listeners/hyrax_listener.rb, app/models/concerns/pdf_behavior.rb, app/presenters/hyku/work_show_presenter.rb, app/views/hyrax/file_sets/media_display/_pdf.html.erb, config/metadata/with_pdf_viewer.yaml, spec/rails_helper.rb
This commit will bring back the full functionality of PDF.js for Valkyrie Hyrax.  This includes:
- toggle the PDF.js viewer
- toggle downlad pdf button
Ref:
- https://github.com/scientist-softserv/iiif_print/issues/342
=> 🐛 Fix PDF.js for Valkyrie

lib/hyrax/solr_service_decorator.rb, spec/requests/catalog_controller_spec.rb
refs https://github.com/samvera/hyku/issues/2177
The failure was happening due to the `post` method in Hyrax's `solr_service`. This method was using Hyrax's connection method, which fell back to `valkyrie_index.connection`, resulting in a url with no core so it used `hyrax-valkyrie`
=> 🐛 Fix solr endpoint default issue

lib/valkyrie/indexing/solr/indexing_adapter_decorator.rb
Refs https://github.com/samvera/hyku/issues/2177
=> Fixes more solr uri issues

app/views/catalog/_index_gallery_collection_wrapper.html.erb, app/views/catalog/_index_header_list_collection.html.erb, app/views/catalog/_thumbnail_list_collection.html.erb, app/views/hyrax/homepage/_recent_document.html.erb, app/views/themes/cultural_repository/hyrax/homepage/_recent_document.html.erb, app/views/themes/institutional_repository/hyrax/homepage/_recent_document.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_recent_document.html.erb
it wants a solr document. lets be consistant about what we give it
This change parallels one from Adventist.
fixes https://github.com/scientist-softserv/adventist-dl/issues/750
=> the generate_work_url method from iiif print does not want a hash

Gemfile.lock, db/schema.rb
Contribute bulkrax x embargo back to hyku
ref:
- https://github.com/samvera/bulkrax/commit/855ce39e805295377eda9a7c24645fbb0ee5617c
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/1008
=> Update Bulkrax for Embargo/Lease import support

Gemfile, Gemfile.lock
The deploy was not working because it was missing the `repeat` method which is provided by the `ActiveJob::Scheduler` gem.
=> 🎁 Add `ActiveJob::Scheduler`

app/views/layouts/hyrax.html.erb
This commit will bring the footer back for the splash page as well as retain the footer display on the homepage.
ref:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/211
=> 🐛 Bring back footer for splash page

config/initializers/willow_sword.rb
We had to do this because the willow_sword initializer called Hyrax which created loading issues with the SimpleSchemaLoaderDecorator in HykuKnapsack.
=> Wrap willow_sword initializer in after_initialize

.circleci/config.yml, config/application.rb
This commit will remove the knapsack decorator from the config/application.rb file because the knapsack already is taking care of this and would be redundant.
See:
- https://github.com/samvera-labs/hyku_knapsack/blob/main/lib/hyku_knapsack/engine.rb#L49-L55
=> Remove Knapsack decorator from config/application

.gitignore, app/assets/javascripts/hyrax/fileupload.js, app/assets/stylesheets/hyku.scss, app/controllers/concerns/hyku/collection_branding_behavior.rb, app/controllers/hyrax/dashboard/collections_controller_decorator.rb, app/forms/hyrax/forms/pcdm_collection_form_decorator.rb, app/helpers/application_helper.rb, app/presenters/hyrax/collection_presenter_decorator.rb, app/services/hyrax/thumbnail_path_service_decorator.rb, app/views/hyrax/dashboard/collections/_form_branding.html.erb, app/views/hyrax/my/collections/_list_collections.html.erb, app/views/hyrax/uploads/_js_templates_branding.html.erb, config/initializers/hyrax.rb, lib/hyrax/transactions/collection_update_decorator.rb, lib/hyrax/transactions/steps/save_collection_banner_decorator.rb, lib/hyrax/transactions/steps/save_collection_logo_decorator.rb, lib/hyrax/transactions/steps/save_collection_thumbnail.rb, lib/tasks/migrate_hyku_commons_collection_thumbnails_to_valkyrie.rake, spec/hyrax/transactions/steps/save_collection_thumbnail_spec.rb, spec/tasks/migrate_hyku_commons_collection_thumbnails_to_valkyrie_spec.rb
Issue: 
- https://github.com/scientist-softserv/hykuup_knapsack/issues/205
The ability for collections to have thumbnails will be deprecated in Hyrax v5.0.0. 
This PR implements the ability to upload collection thumbnails by following the precedence set by the collection's branding's banner and logo uploads.
Ideally we'd contribute this back if the community supports it. However, for the sake of time we are overriding Hyrax instead. 
```ruby
CollectionBrandingInfo.where(role: thumbnail) => 
[#<CollectionBrandingInfo:0x0000ffff7e0440d8     
id: 5,                                         
collection_id:                                 
"69afdb60-3a3d-41b1-9ecd-c8a5959516ed",       
role: "thumbnail",                             
local_path: …
```
=> 🚧 i205 - add ability to upload collection thumbnails

spec/views/themes/cultural_repository/_user_util_links.html.erb_spec.rb, spec/views/themes/institutional_repository/_user_util_links.html.erb_spec.rb
Contributes back missing spec files. 
Theme work has already been contributed back but the spec files were not.
=> contribute back theme spec files

app/views/catalog/_search_results.html.erb
This commit will override Blacklight to bring back the constraints. This may not be the final solution but it will do for now.  We remove the content_for block because it was not working as expected.
=> 🐛 Bring back catalog search constraints

db/migrate/20200513060858_create_domain_names.rb, db/migrate/20231215215705_create_hyrax_counter_metrics.hyrax.rb, db/migrate/20231215215707_add_indices_to_hyrax_counter_metrics.hyrax.rb, db/migrate/20231215215708_add_fields_to_counter_metric.hyrax.rb
We noticed in deploying Pals staging that these changes were needed to run migrations successfully.
=> 🐛 Add guards for migrations

app/forms/hyrax/forms/admin/appearance_decorator.rb, db/migrate/20240528232441_add_directory_image_alt_text_to_sites.rb, db/schema.rb
This comes from Palni/Palci as they and possibly other institutions use a custom splash page that shows the logos of each public tenant.  We would have to do some more thinking to contribute back the splash page but at least this sets it up for the future.
=> Contribute directory_image_alt_text to Hyku

config/initializers/good_job.rb
The sentry-raven gem has changed to the sentry-ruby gem and this is just a clean up of the module name.
=> Change Raven to Sentry

Dockerfile
The issue of branding, logo, and thumbnails not appearing has been solved before in other projects. ref:
- https://github.com/scientist-softserv/atla-hyku/pull/187
This commit is required to resolve the issue with uploading images from the Collections' branding tab. Because the symlink wasn't established, a user would not be able to see the images they uploaded even though the path correctly exists.
=> 🎁 Adds symlink between samvera and hyrax-webapp branding directories

config/initializers/willow_sword.rb, db/migrate/20240530205142_add_api_key_to_users.rb, db/schema.rb
This commit will add the api_key column to the user model and turn on authorized requests for WillowSword.  To give a user access, do something like the following:
```rb
u = User.find_by(email: 'some_user@example.com')
u.api_key = SecureRandom.uuid
u.save!
```
To add it in the header, it should look like this:
```sh
curl --request GET \
--url http://dev.hyku.test/sword/service_document \
--header 'Content-Type: application/xml' \
--header 'Api-key: some-api-key'
```
Ref:
- https://github.com/CottageLabs/willow_sword/wiki/Enabling-Authorization-In-Willow-Sword
- https://github.com/scientist-softserv/palni-palci/issues/1037
=> 🎁 Add Api-Key auth for WillowSword

README.md, docs/configuration.md, docs/getting-started.md, docs/support.md, docs/using-hyku.md
Contribution by @ryan-lang. I created this PR due to issues with a failing build in the original PR.
ref original PR:
- https://github.com/samvera/hyku/pull/2221/commits/e601d80c82c37cef4010fdd5e7bdca72bce34c63
Per @ryan-lang
Fixes #1920
Fixes #1981
Fixes #2155
Fixes #2142
Simply reorganizes the existing README documentation for clarity purposes, which had grown to a point where it was getting difficult to follow. Also adds a canonical approach to running the latest "stable" version locally, as suggested by @jeremyf [here](https://github.com/samvera/hyku/issues/2142#issuecomment-1908654296).
I'm a complete novice with the Samvera stack, so the documentation is mostly copy-paste from the original README, but I felt this would be a good step towards fixing a persistent pain point for new …
=> :gift: documentation reorg per ryan-lang

app/views/hyrax/contact_form/new.html.erb
This commit fixes the reason why the contact page would throw an error. There was a syntax error.
Issue: 
- https://github.com/scientist-softserv/palni_palci_knapsack/issues/37
=> :bug: [i37] - Fix syntax error on contact page

app/controllers/catalog_controller.rb, app/views/hyrax/homepage/_featured_collection_section.html.erb
`human_readable_type` has been replaced by `generic_type`.
Refs https://github.com/scientist-softserv/hykuup_knapsack/issues/226
This fixes
1) the `All Collections` button now finds collections
2) the catalog search now includes collections in the Type section
<details>
</details>
=> :bug: Fix collection search & facet

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb
Issue: 
- https://github.com/scientist-softserv/hykuup_knapsack/issues/229
b39333f9e6973905e14d0b7b53b9ce7be1425635
Previously, when the user looks at the catalog search results page and
sets the view to either gallery or masonry, the styling is really off.
Here this commit should fix that and also hide the bookmarks checkbox.
Hyrax dassie does not show it so we will mimic that until further notice
since the user can't even get to the /bookmarks route.
Ref:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/229
e677230d4b8a5ea8861c99a49182c8d854f4cf2e
=> Fix gallery and masonry catalog search results

app/assets/stylesheets/hyrax.scss
This will make any long links break.  Prior to this commit any links that didn't have a `-` or a character that would create a natural word break would push the UI until it looked weird.
=> 🐛 Break long links in catalog search

app/controllers/hyrax/dashboard/collections_controller_decorator.rb, app/helpers/application_helper.rb, app/presenters/hyrax/collection_presenter_decorator.rb, app/services/hyrax/thumbnail_path_service_decorator.rb, app/views/hyrax/collections/_media_display.html.erb, app/views/hyrax/collections/show.html.erb, app/views/hyrax/dashboard/collections/_list_collections.html.erb, app/views/hyrax/my/collections/_list_collections.html.erb, lib/hyrax/transactions/steps/save_collection_banner_decorator.rb, spec/tasks/rake_spec.rb
Fixes https://github.com/scientist-softserv/hykuup_knapsack/issues/205
Alt text did not work correctly for collection thumbnails and banner.
Default collection image did not get used... default work image was used instead.
=> Branding fixes

app/views/shared/_ga4.html.erb
Not doing so treats the ENV var as a class, and thus throws an error about that class not existing.
The site was unable to render
=> 🐛 Wrap quotes around ENV var

app/parsers/bulkrax/csv_parser_decorator.rb, spec/parsers/bulkrax/csv_parser_decorator_spec.rb
Ref:
- https://github.com/scientist-softserv/palni_palci_knapsack/commit/9549183db75c2ad10665ee59799ab73e5647b7fd
=> 🐛 Bring over CsvParserDecorator fix from Pals

app/views/hyrax/base/_show_actions.html.erb
The links under the Add Child dropdown was not working because the HTML structure was not correct.  This commit will close the button tag and then open the ul tag which allows the links to be clickable.
Ref:
- https://github.com/scientist-softserv/palni_palci_knapsack/issues/78
=> 🐛 Fix Add Child link

lib/hyrax/transactions/container_decorator.rb
In Bulkrax we are noticing that sometimes `Hyku::Transactions` isn't loaded.  This commit will ensure it's loaded.
=> 🐛 Ensure `Hyku::Transactions` is loaded

app/services/hyrax/file_set_derivatives_service_decorator.rb
When text extraction fails on a PDF, the derivative job resubmits. This was resulting in 5 Hyrax::FileMetadata objects on a file set, all for the same thumbnail file, because jobs automatically resubmit 5 times.
In this PR, I commented out the failing extract_full_text method, but also qualified the thumbnail creation on whether the thumbnail is already there.
<details>
</details>
=> Fix duplicate thumbnails for PDFs

app/parsers/bulkrax/csv_parser_decorator.rb, config/initializers/bulkrax.rb, spec/parsers/bulkrax/csv_parser_decorator_spec.rb
We are removing the bulkrax_identifier opinion because applications should declare their own source identifiers.  We are also commenting out the logic for required fields for now, it is not working for Valkyrie objects.
=> 🐛 Fix Bulkrax issues for Knapsack applications

app/views/hyrax/dashboard/collections/_form_share.html.erb
In PR#2236 we accidentally deleted the word as from the view.
ref:
- https://github.com/samvera/hyku/pull/2236/files
=> i51 - reverts accidental delete

Gemfile.lock, app/assets/stylesheets/hyku.scss, app/assets/stylesheets/hyrax.scss
15e8b91d3927446682a978220513ee1196a68804
This commit will align the facet count to the end of the flex row.
d941cfc988880ae903b058cb9816bd5fd7be87b4
This commit will update Hyrax to include some fixes to the UI that we
overrode in Hyku.  Now that the changes have been merged to Hyrax we can
go ahead and remove the overrides after updating to the latest revision.
=> Styling updates

spec/services/hyrax/quick_classification_query_spec.rb
The Hyrax::QuickClassificationQuery spec was leaking into other specs because the user ability was being loaded with just the GenericWork. Loading Hyrax::ModelRegistry.work_classes seems to ensure things are loaded correctly.
=> ✅ Fix QuickClassificationQuery leaky spec

.irbrc, spec/models/featured_collection_list_spec.rb
This commit will turn off the arguably annoying autocomplete when in Rails console.  Also, not keeping a save history.
Before:
https://github.com/user-attachments/assets/3052a178-5c10-40d5-be4b-6ffc66b5b24b
After:
https://github.com/user-attachments/assets/116aa8c5-e75a-402a-9378-261f4523bf5e
=> ⚙️ Turn off autocomplete in Rails console

app/assets/stylesheets/themes/cultural_repository.scss, app/assets/stylesheets/themes/institutional_repository.scss, app/assets/stylesheets/themes/neutral_repository.scss, app/views/themes/cultural_repository/_logo.html.erb, app/views/themes/institutional_repository/_logo.html.erb, app/views/themes/institutional_repository/layouts/homepage.html.erb
2e5f98f03fd9266d98fd2889b0dd18de86212dd2
This update will give a little more padding on the top of the text
inside of the banner.
2cb1b4a274d7a7884ddcbe018c8dc0b1ca6fca85
To align Hyku themes with Hyrax, we remove the globe since they did that
some time ago.
Ref:
- https://github.com/samvera/hyrax/commit/0d9e361946131ff86dc2bd3682bdbe043bcc587e
528d4b98cebf8105db7c619166563f52962af3f0
This commit will align the logo on the cultural_repository theme better.
8dc6eda6c941bc39961fe52b3c41c1cc468f0ef8
This update will give the neutral_repository theme's banner text more
padding and thus increasing the height of the banner area as well to
mimic how it looked previously.
Ref:
- https://github.com/scientist-softserv/palni_palci_knapsack/issues/56
=> More theme updates

config/initializers/wings.rb
Adding an unless condition for registering the Freyja adapter will allow knapsack to register custom queries.
Issue:
- https://github.com/scientist-softserv/adventist_knapsack/issues/743
=> ⚙️ Add condition for `Valkyrie::MetadataAdapter`

app/controllers/hyrax/admin/appearances_controller_decorator.rb, app/forms/hyku/forms/admin/appearance.rb, app/views/shared/_appearance_styles.html.erb, spec/forms/hyku/forms/admin/appearance_spec.rb, spec/views/hyku/admin/appearances/show.html.erb_spec.rb
In the HykuKnapsack we are running into an issue with a decorator that was trying to alter the `#customization_params` method of the `Hyrax::Forms::Admin::Appearance` however that method was being declared in a decorator in Hyku.  The decorator in Knapsack was trying to alter it prior to the method being declared and throwing a `NoMethodError`. This refactor will make the `Hyku::Forms::Admin::Appearance` inherit from the Hyrax version and override methods as needed thus declaring the `#customization_params` method so the HykuKnapsack decorator can alter it.
=> ♻️ Introduce the `Hyku::Forms::Admin::Appearance`

app/controllers/concerns/hyku/home_page_themes_behavior.rb, app/controllers/hyrax/contact_form_controller_decorator.rb, app/controllers/hyrax/homepage_controller.rb, app/controllers/hyrax/pages_controller_decorator.rb, config/application.rb, spec/controllers/concerns/hyku/home_page_themes_behavior_spec.rb
2ba8794749b0dff8fb3ad04104ab66d2f07e02b6
This commit will move the #inject_theme_views method and the
around_action that calls it into a concern.
94d495664bffa79804aa4c6c75c59671829454f5
In the HykuKnapsack, we want the themes view path to be prioritized over
the Hyku application's themes view path.
=> Themes logic refactor

app/assets/stylesheets/hyku.scss
Brings in a fix from this Hyrax to fix the graient styling in the handles of places like the featured works on the homepage.
Ref:
- https://github.com/samvera/hyrax/pull/6861/commits/fa1bffccdc36ef8de2a386ff11ea9035f63d0780
=> 💄 Fix the gradient on featured works on homepage

app/assets/stylesheets/hyku.scss, app/views/hyrax/dashboard/sidebar/_configuration.html.erb
547b01e69b791f8ac4fa6c45e700e8c25eee88e2
If a logo is chosen the height of the masthead in the dashbaord grows
big enough to cover part of the sidebar by a little bit.  This commit
will dial that back to 40px instead of 50px.
dce334bf3f6b7edd0bf608330eab1daad88d559b
This commit will make the dashboard sidebar fixed so it always stays on
the screen and the user can scroll through it.
8706790120f99c4d769e0a40a589da15d8da3fe9
At some point the Workflow Roles and Data Repair options were moved into
the Settings menu fold.  This moves them back out.
https://github.com/user-attachments/assets/f5599386-827f-488a-bcff-3c9ce6898437
=> Dashboard styling

app/forms/admin_set_resource_form.rb
`include CollectionAccessFiltering` was happening at the wrong time, and a needed method was not found by the edit view. This presented the lazy migration from happening for the admin set in the UI, but saving the resource in the console created a slightly broken valkyrized resource.
This PR fixes the edit, and the converted admin sets appear for use when creating a work via the UI or Bulkrax.
=> Fix Admin Set form to make edit work

Gemfile, Gemfile.lock
I'm struggling with getting IIIF Print to build with the committed constraint for DR.  Why? Because IIIF Print is installing Hyku in it's build and Hyku was previously requiring v0.5.2.
There's some twisted logic inversion that's happening.
=> ⚙️ Pinning DerivativeRodeo to a better version

app/services/hyrax/thumbnail_path_service_decorator.rb
In Adventist Knapsack we noticed that attaching a thumbnail to a collection would not render the thumbnail. This is part of the necessary fix.
Issue:
- https://github.com/scientist-softserv/adventist_knapsack/issues/763
=> :bug: incorrect path prevents thumbnails from rendering

Gemfile.lock
refs https://github.com/scientist-softserv/adventist_knapsack/issues/770
Updates bulkrax to use HashWithIndifferentAccess to prevent errors accessing data.
=> Update bulkrax to fix adventist ingesting

app/jobs/batch_email_notification_job.rb, app/models/sushi.rb, app/models/user.rb, app/models/user_batch_email.rb, db/migrate/20240820195641_remove_last_emailed_at_from_users.rb, db/migrate/20240820200440_create_user_batch_emails.rb, db/schema.rb, spec/jobs/batch_email_notification_job_spec.rb
Refs https://github.com/scientist-softserv/palni_palci_knapsack/issues/121
`last_emailed_at` was previously added to the User table. However User table is not tenant-specific, and this date needed to be unique to each tenant. This moves the `last_emailed_at` date to its own table and modifies the use to match the new location.
=> Batch Email Notifications

app/jobs/migrate_resources_job.rb, config/initializers/hyrax.rb, lib/tasks/index.rake, spec/jobs/migrate_resources_job_spec.rb
refs https://github.com/scientist-softserv/adventist_knapsack/issues/773
Creates rake task `migrate_collections` which will submit MigrateResourcesJob for each tenant to migrate all ActiveFedora AdminSets and Collections to Valkyrie resources.
Also sets solr_default_method = :post
=> Migration script for collections

Gemfile.lock, app/assets/stylesheets/hyku.scss, app/jobs/depositor_email_notification_job.rb, app/mailers/hyku_mailer.rb, app/views/hyku_mailer/depositor_email.html.erb, app/views/hyrax/base/_download_pdf.html.erb, spec/jobs/depositor_email_notification_job_spec.rb
This contains the following work needed to support google analytics: 
- missing from: 
Issue: 
- https://github.com/scientist-softserv/palni-palci/issues/1020
54168b7ccf1f7e849a1a1194f2a881af2ae4b4f5
ID must be changed so to be consistent with google analytics tracking.
Issue:
- https://github.com/scientist-softserv/palni-palci/issues/1020
fd8bdb741643826e6f80ab84c455fdb4d24e6349
This should avoid sending emails with blank names in the title.
608faf9b56a21c616a09ecc6eaadbd06d7e30d54
7c392159ae2be1a3c5255ca08551cf64662b9deb
pulls in ga4 typo fix
- https://github.com/samvera/hyrax/pull/6897
=> :broom: [i1020] - ga4 follow up

Gemfile.lock
This update will allow the document service query to only return Valkyrie resources instead of also the ones found in ActiveFedora.
Ref:
- https://github.com/scientist-softserv/willow_sword/commit/f401d9254a2b755947f47f588ee139463dcfcf4d
=> Update WillowSword gem

app/assets/stylesheets/hyku.scss, app/views/hyrax/homepage/_featured_collection_section.html.erb, app/views/themes/cultural_repository/_collections_section.html.erb, app/views/themes/institutional_repository/hyrax/homepage/_recent_document.html.erb, app/views/themes/institutional_repository/hyrax/homepage/_recently_uploaded.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_recent_document.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_recently_uploaded.html.erb
74e4e0a4f63b9219179c73e28185a967ea8b4ec5
This commit will adjust the featured colleciton section so it wraps and
doesn't clip anything else.
1af17b4236bf466a097a01f810daa1a036684d67
In the Institutional Repository and Neutral Repository themes, the
Recently Uploaded section was only showing one column, this commit makes
it show two.
=> Adjust themes

Gemfile.lock, app/forms/etd_resource_form.rb, app/forms/oer_resource_form.rb, app/indexers/etd_resource_indexer.rb, app/indexers/oer_resource_indexer.rb
Refs https://github.com/scientist-softserv/palni-palci/issues/1010
Bulkrax imports were sometimes not showing as completed on the importer page, because the created object couldn't be found for the link. This error was tracked down to some missing inclusion of the bulkrax metadata on some of the indexers and forms, resulting in the bulkrax_identifier not being saved on the newly created works. 
This change ensures that all models, forms, and indexers have the appropriate metadata included. Additionally bulkrax is updated to bring in the most recent fixes. 
Importers showed error `Error: NoMethodError - undefined method 'persisted?' for false:FalseClass` on certain models, and Item does not link.
<details>
<summary>Screenshot</summary>
</details>
Importer shows successful and links to …
=> Include bulkrax metadata in resource forms and indexers

app/indexers/concerns/hyku_indexing.rb, app/models/sort_title.rb
Issue: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/185
This commit fixes a bug in the ability to sort works by "Published date", "Upload date", and "Title" in the catalog search page and the collection show page reported in Adventist Knapsack.
Adds sorting to Solr doc in `HykuIndexing` module.  
Ascending sort:
Descending sort:
=> 🐛 Fix "Sort by: Published Date"

app/indexers/collection_resource_indexer.rb, app/models/collection_resource.rb
Removes `HykuIndexing` mix in from the `CollectionResource` model and adds `HykuIndexing` mix in to `CollectionResourceIndexer` to fix a bug when sorting the catalog. 
Ref:
- https://github.com/scientist-softserv/adventist_knapsack/issues/185
=> 🐛 Moves HykuIndexing to CollectionResourceIndexer

Gemfile.lock, db/schema.rb
Updates bulkrax gem and runs migration to add last_imported_at and next_import_at columns. This fixes the bulkrax index sorting errors.
Issue: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/758
=> ⚙️ Update Bulkrax + run migration

app/assets/stylesheets/hyrax.scss, app/helpers/application_helper.rb, spec/features/create_etd_spec.rb, spec/helpers/application_helper_spec.rb
- updates styling to make labels bold in the collection form
- updates locale helper method to account for collection resources
- Before, if there wasn't a matching term in the locale it would look like the labels were repeated. 
Issue:
- https://github.com/scientist-softserv/adventist_knapsack/issues/777
=> [i777] - collection metadata clean up

Gemfile, Gemfile.lock, app/presenters/hyku/work_show_presenter.rb, app/views/hyrax/base/_relationships.html.erb, app/views/hyrax/base/_representative_media.html.erb, app/views/themes/image_show/hyrax/base/show.html.erb
Refs https://github.com/scientist-softserv/adventist_knapsack/issues/760
There is no expected behavioral changes due to these changes beyond the Bulkrax update... it is simply some cleanup, documentation, and behind the scenes work needed to prepare for some cleanup & behavior changes in Adventist's knapsack repo.
- Updates Bulkrax
- Add documentation to work_show_presenter
- Update representative_media bootstrap classes
- Update _relationships partial to coordinate with current Hyrax
- Update some obsolete code in image_show/show.html.erb
=> Clean up viewer logic

app/controllers/catalog_controller.rb
This commit will update the `CatalogController` to use the Blacklight 7 option `link_to_facet`.
Ref:
- https://github.com/projectblacklight/blacklight/wiki/Blacklight-configuration#linking-a-value-to-a-facet-search
=> 🐛 Change `link_to_search` to `link_to_facet`

app/controllers/catalog_controller.rb, app/indexers/concerns/hyku_indexing.rb
This commit improves communication of intent by removing the multiple indicator from the hyku_indexing module.
Ref:
- https://github.com/scientist-softserv/adventist_knapsack/issues/185
=> 💄 Removes the multiple indicator from Solr suffix

app/assets/javascripts/application.js, app/assets/javascripts/blacklight_gallery.js, app/assets/stylesheets/hyku.scss, app/assets/stylesheets/hyrax.scss, app/views/hyrax/collections/show.html.erb
This PR updates styling for the public facing collections show page. It addresses the top bars, the gallery view and pagination issues. 
Pals [#137](https://github.com/scientist-softserv/palni_palci_knapsack/issues/137)
=> Public facing collections show page styling

Gemfile, Gemfile.lock, app/indexers/concerns/hyku_indexing.rb, app/presenters/hyrax/iiif_manifest_presenter_decorator.rb
Refs https://github.com/scientist-softserv/adventist_knapsack/issues/817
Updates IiifPrint to bring in fixes re: items list duplication.
Uses new index field to get full list of file set ids, since member_ids_ssim index override has been removed.
=> Fix universal viewer duplicates

Gemfile.lock
This commit will bring in a new functionality for WillowSword so that when a user hits the service_document endpoint, they will also see what admin sets they have access to.  This will let them know what admin set id to include in their deposit.
=> ⬆️ Update WillowSword gem

Gemfile.lock, app/assets/stylesheets/themes/institutional_repository.scss, app/forms/based_near_form_fields_behavior.rb, app/forms/etd_resource_form.rb, app/forms/oer_resource_form.rb, app/views/themes/institutional_repository/_logo.html.erb, config/metadata/oer_resource.yaml
refs
- https://github.com/samvera/hyku/issues/2356
Fixes:
- header text position in institutional repository
- location faceting (a reindex will get works using `based_near` to appear in the facet if they are missing)
- based_near behavior fixes for ETD and OER resources types
* update hyrax
* fix institutional repository layout
* ensure all resource types have based_near behavior that works
<details>
<summary>Institutional Repository layout after changes</summary>
</details>
<details>
<summary> Based near is now working</summary>
</details>
=> Update hyrax, fix institutional repository layout & based_near behavior

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/helpers/hyku/blacklight_helper_behavior.rb, app/helpers/shared_search_helper.rb, app/presenters/blacklight/thumbnail_presenter_decorator.rb, app/views/catalog/_index_header_list_default.html.erb, app/views/catalog/_index_list_default.html.erb, app/views/catalog/_thumbnail_list_default.html.erb, spec/helpers/shared_search_helper_spec.rb
Issue: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/769
<details> 
</details>
=> Fix snippets

app/controllers/catalog_controller.rb, app/helpers/shared_search_helper.rb, app/views/catalog/_index_list_default.html.erb, spec/helpers/shared_search_helper_spec.rb
Summary:
Fix generated work url.
Adjust char limit to accomplish full text search.
Modify view to only load field_value once.
Adjust specs for url change.
refs https://github.com/scientist-softserv/adventist_knapsack/issues/769
<details>
</details>
=> Snippet fixes for catalog search into viewer

.github/CONTRIBUTING.md, CONTRIBUTING.md
These agreements are no longer required to contribute to this project.
Also, remove the requirement to add your name to CONTIBUTORS.md, since no such file exists in this repo.
* Remove outdated CLA requirement from documentation about how to contribute to this project
* Remove the requirement that contributors write their name in a non-existent file (CONTRIBUTORS.md)
=> Remove contributor licence agreements from contributing docs

Gemfile.lock
ref:
- https://github.com/samvera/hyrax/pull/6968
the side bar type is missing once AF records are reindexed.
=> Update Hyrax and IIIF Print

app/services/hyrax/thumbnail_path_service_decorator.rb, config/environments/production.rb, spec/services/hyrax/thumbnail_path_service_spec.rb
The default work thumbnail was displaying even though the default collection thumbnail was set.
Issue:
- https://github.com/scientist-softserv/adventist_knapsack/issues/886
=> [i886] - update logic to fix collection thumbnail bug

app/assets/javascripts/application.js, app/assets/stylesheets/application.css, app/models/concerns/account_settings.rb, app/views/proprietor/accounts/edit.html.erb, app/views/shared/_settings.html.erb, config/initializers/assets.rb, lib/bulkrax/bulkrax_decorator.rb, spec/lib/bulkrax/bulkrax_decorator_spec.rb, spec/models/concerns/account_settings_spec.rb
In multi-tenant Hyku applications, different tenants can have different requirements for field mappings. This is usually fine for the `:from` setting; if one tenant has a column named `title_alpha` and another `title_beta`, both can be added to the `title`'s field mapping `:from` setting. 
However, conflicts arise when tenants have different requirements for other settings, such as `:split` or deciding which field should be considered the `source_identifier`. In those cases, having a single, static field mapping config doesn't work.
This PR introduces a new `Account` settings as well as an override to Bulkrax to allow for configuring field mappings completely independently on a per-tenant basis. 
<details><summary>New account default settings</summary>
</details> …
=> Add per-tenant Bulkrax field mappings

app/controllers/hyrax/dashboard/collections_controller_decorator.rb, app/presenters/hyrax/presenter_renderer_decorator.rb, app/views/hyrax/oers/_attribute_rows.html.erb, app/views/themes/cultural_show/hyrax/oers/_related_item.html.erb, app/views/themes/cultural_show/hyrax/oers/show.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_recent_document.html.erb, config/authorities/discipline.yml, spec/services/hyrax/discipline_service_spec.rb
Incorporates several small fixes:
- Moves several partials for the OER work type that was contributed back from pals and weren't included previously
- Collection metadata now shows text for based_near location instead of URI
- Fix collection branding (banner & logo)
Ref https://github.com/scientist-softserv/palni_palci_knapsack/pull/165
=> Small fixes for views & branding

.github/workflows/build-test-lint.yaml, spec/lib/bulkrax/bulkrax_decorator_spec.rb
Since `Hyku.default_bulkrax_field_mappings=` sets an instance variable, it can persist in scope for other specs, causing unexpected / flaky failures
=> Prevent field mappings set value from bleeding into other specs

app/controllers/hyrax/contact_form_controller_decorator.rb, app/controllers/hyrax/pages_controller_decorator.rb
Fixes 'invalid method error' by correcting the method name, number of arguments, and adding the appropriate object reference.
=> Fixes invalid method error in IR theme

app/assets/stylesheets/hyku.scss, app/views/hyrax/collections/show.html.erb, config/locales/en.yml
Blacklight has removed the info for how to start the slideshow. Not sure why it was removed [here](https://github.com/projectblacklight/blacklight-gallery/commit/498b463e0b4418411d303676c1877547044f43c8), without comment. It is probably better to have it in hyku so there is no worry about it being arbitrarily changed in the future. This change applies specifically to the public show page of collections.
=> Added slideshow start info back in from blacklight.

Gemfile, Gemfile.lock, docker-compose.yml, spec/features/appearance_theme_spec.rb, spec/features/create_etd_spec.rb, spec/features/create_generic_work_spec.rb, spec/features/create_image_spec.rb, spec/features/create_oer_spec.rb, spec/features/work_editor_role_spec.rb
- updates bulkrax
- updates docker-compose to improve spec speed
- Temporarily comments out failing feature specs to unblock the pipeline; these specs don't fail locally but consistently fail in the pipeline. Further investigation will be needed to resolve (in a separate issue).
=> Bulkrax chunked uploads pipeline fix

Gemfile, Gemfile.lock
Issue:
- https://github.com/scientist-softserv/adventist_knapsack/issues/858
ref:
- https://github.com/samvera/bulkrax/pull/982
=> Update bulkrax for chunked upload support

app/views/hyrax/pages/_form.html.erb, config/locales/hyrax.en.yml
Simpleform injects css classes into its button tags and those classes conflict with what is used in Hyku. The forms on the Pages page were using the button tag instead of the submit tag and causing the classes to be duplicated and conflict with each other. By using the submit tag it doesn't inject classes and only applies the classes specified in the tag.
Button color for "Save changes" button was white instead of blue like the rest of Hyku. This fixes that issue as well as issues in the future stemming from this "class injection".
=> Fix incorrectly colored save button

db/schema.rb
=> work_authorizations code is not in hyku yet, this schema change is an error

app/controllers/application_controller.rb, app/controllers/devise_guest_controllers_helpers_decorator.rb
guests fail to to find the existing guest account because of the default scope.
=> fix guest lookup to be unscoped

app/views/shared/_appearance_styles.html.erb, app/views/shared/_footer.html.erb, config/locales/en.yml
Builds on and completes prior appearance color fixes:
- https://github.com/samvera/hyku/pull/2398
- https://github.com/samvera/hyku/pull/2399
Prior work had not verified that colors applied appropriately to themes.
All themes and colors were tested and only a few minor revisions were needed.
=> Final appearance color fixes

app/views/hyrax/oers/_related_items.html.erb, app/views/themes/cultural_show/hyrax/oers/_related_items.html.erb
Ref:
- https://github.com/notch8/palni-palci/issues/1066
- https://github.com/notch8/palni-palci/pull/1069
Pagination was attempting to act upon a local variable that didn't exist; it was removed in this commit:
- https://github.com/notch8/palni-palci/commit/fbe9093
Replace it with the presenter method that Hyrax typically uses to display member presenters
Viewing the show page of an OER work that has 11+ members (e.g. FileSets) throws a 500 error 
OER members display in a paginated list 
<details>
<summary>Paginated members</summary>
</details>
=> Fix member pagination on OER show pages

Gemfile.lock, app/views/themes/cultural_repository/catalog/_search_form.html.erb, app/views/themes/institutional_repository/catalog/_search_form.html.erb
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/156
This commit:
- updated the search form override view files for the Cultural and Institutional Repositories to align with existing code in Hyrax which fixed styling issues in the search form dropdown menus
- updated the Hyku dependencies to the latest versions of Hyrax gems
=> 🧹 Updates to search form overrides

spec/presenters/hyku/work_show_presenter_spec.rb
This commit will ensure that the state of the test_strategy tenant is returned to its default after the test runs because we were seeing this interfere with other tests it was left set on non-default.
=> ✅ Fix flaky work_show_presenter_spec

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
when bulkrax fix gets merged this pr needs to be updated
=> working on issues with bulkrax and hyrax javascript

app/assets/stylesheets/themes/cultural_show.scss, app/views/themes/cultural_show/hyrax/base/_show_actions.html.erb, app/views/themes/cultural_show/hyrax/base/_work_title.html.erb, app/views/themes/cultural_show/hyrax/base/show.html.erb, app/views/themes/scholarly_show/hyrax/base/_show_actions.html.erb, app/views/themes/scholarly_show/hyrax/base/_work_title.html.erb, app/views/themes/scholarly_show/hyrax/base/show.html.erb, spec/services/create_account_spec.rb
This commit will adjust the show pages of various themes and make them look better.
Default show:
Cultural show:
Scholarly show:
=> 🧹 Adjust show pages

app/assets/stylesheets/themes/cultural_show.scss, app/views/themes/cultural_show/hyrax/base/show.html.erb
This commit will change the cultural show page's citations div to use css instead of using bootstrap utility classes.  This way it will be easier for knapsack applications to override the style of that div.
=> 🧹 Switch from bootstrap class to css

app/assets/stylesheets/hyku.scss, app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/views/shared/_appearance_styles.html.erb
Since the Hyrax 5 update the catalog gallery index page had a grid layout of four columns while in default Hyrax has three.  Also removed some extra spacing from top row of the items.  There was also an extra border that was around the facets that were removed.  The description facet on each result has a truncate of 200 characters.
=> 🧹 Fix catalog gallery view

app/views/hyrax/admin/appearances/_custom_css_form.html.erb
The CodeMirror editor was invisible until text was selected.  Added tab show event handler to properly refresh the editor when the CSS tab becomes visible.
=> 🐛 refresh CodeMirror editor when CSS tab is shown

app/views/hyrax/content_blocks/_form.html.erb, app/views/shared/_appearance_styles.html.erb, config/locales/hyrax.en.yml, spec/views/hyrax/content_blocks/edit.html.erb_spec.rb
Refs: 
https://github.com/samvera/hyku/pull/2417
https://github.com/notch8/palni_palci_knapsack/issues/172
Restore text color in dropdown menus: fix got lost during a merge conflict patch.
Restore facet border color but in the right location (removed https://github.com/samvera/hyku/pull/2420 due to double border)
Fixes appearance of content blocks form by removing duplicate tabs, adding appropriate classes, and adding translations.
<details>
An exception is the cultural theme
</details>
=> Fix content blocks

Gemfile.lock, app/services/hyrax/user_stat_importer_decorator.rb
8908166d017ee654b28caab0cddd550fa6107828
This commit will bring in view changes from Bulkrax for the importer
show page.
Ref:
- https://github.com/samvera/bulkrax/pull/1011
27345d898f675475affc1f47cd14c97c7fd7b2b4
This commit will override the #process_files method to use the Hyrax
query service instead of the old ActiveFedora way of finding the
FileSet.
Ref:
- https://github.com/samvera/hyrax/pull/6992
=> Update bulkrax and add user stat importer decorator

app/assets/stylesheets/hyku.scss, app/assets/stylesheets/themes/institutional_repository.scss, app/views/hyrax/homepage/_explore_collections.html.erb, app/views/hyrax/homepage/_featured_collection_fields.html.erb, app/views/hyrax/homepage/_sortable_featured_collections.html.erb, app/views/shared/_appearance_styles.html.erb
This commit will add a few more html tags to the featured collections, both from the admin end and public facing end, to make it look more like the featured works.  This will fix custom font issues where the titles of the collections were not getting the correct font that was set.
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/178
=> 🧹 Clean up featured collection UI

app/assets/javascripts/stat_slider.js, app/assets/stylesheets/themes/institutional_repository.scss, app/views/themes/institutional_repository/hyrax/homepage/_resource_type_slider.html.erb
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/189
The carousel on the homepage of the institutional repository was buggy. Icon duplications could be seen during transitions and the layout styling was not being applied during transitions.
<details>
<summary>Video: Reported issue</summary>
https://github.com/user-attachments/assets/316eb856-96a3-48c1-8bee-d7798b49c19d
</details>
When there are six or more resources in the institutional repository, there is a slider showing six of the icons. A user can click on arrows to move the icons one place to the right or left. The icons are in a continuous loop.
<details>
<summary>Video: Corrected resource carousel</summary>
https://github.com/user-attachments/assets/8bff82b0-45c5-4e59-8e52-b00e6241746f
</details>
Changes proposed in …
=> I189 institutional repository carousel

app/models/account.rb, app/models/concerns/account_settings.rb, app/views/hyrax/dashboard/profiles/_edit_primary.html.erb, app/views/hyrax/users/_user_info.html.erb, spec/features/accounts_spec.rb, spec/models/concerns/account_settings_spec.rb, spec/services/create_account_spec.rb
Issue: 
- https://github.com/notch8/palni_palci_knapsack/issues/209
Feature flags are now visible in  ADMIN DASHBOARD > SETTINGS > ACCOUNT. When enabled, they will trigger the relevant background jobs.
Additionally, if disabled a user will not see batch email frequency in their profiles. It also removed their ability to set it: 
<details> 
</details> 
<details> 
</details> 
</details> 
abf36be366b1c7b5468645d87255b9d178b48a30
- Updated `find_or_schedule_jobs` to dynamically include jobs based on environment variables.
- Introduced the following environment flags to control job scheduling:
- `ENABLE_BATCH_EMAIL` for `BatchEmailNotificationJob`
- `ENABLE_DEPOSITOR_EMAIL` for `DepositorEmailNotificationJob`
- `ENABLE_USER_STAT` for `UserStatCollectionJob`
- This allows buggy jobs to be …
=> :gift: adds batch email, depositor email, and user stat to Account Settings

Gemfile.lock
This commit will update IIIF Print gem's revision to include a fix for duplicate search results coming through the UV.
Ref:
- https://github.com/notch8/iiif_print/pull/379
- https://github.com/notch8/palni_palci_knapsack/issues/199
=> Update IIIF Print

app/controllers/hyrax/contact_form_controller_decorator.rb
Issue:
- https://github.com/notch8/palni_palci_knapsack/issues/159
The contact form was failing to process submissions due to conflicts between negative captcha and regular form parameters. This update:
- Removes category and contact_method from negative captcha protected fields
- Properly merges protected captcha values with regular form parameters
- Fixes the "Subject/Category can't be blank" validation error
- Ensures all form fields are properly processed while maintaining spam protection
This allows the contact form to successfully submit while keeping the negative captcha security measures intact.
https://github.com/user-attachments/assets/5d8307c0-823e-4be6-8184-8748144a5bab
=> :bug: Fix contact form submission with negative captcha

Gemfile, Gemfile.lock, app/assets/javascripts/application.js
This commit will lock Hyrax to the version right before the Rails 7 upgrade.  Since Hyrax pinned blacklight gallery to a lower version, we needed to change update the assets.
=> 🧹 Lock Hyrax to specific version

app/views/hyrax/base/_analytics_button.html.erb, app/views/hyrax/base/_show_actions.html.erb, app/views/hyrax/base/show.html.erb, app/views/hyrax/dashboard/sidebar/_activity.html.erb, app/views/hyrax/oers/show.html.erb, app/views/themes/cultural_show/hyrax/base/show.html.erb, app/views/themes/cultural_show/hyrax/oers/show.html.erb, app/views/themes/image_show/hyrax/base/show.html.erb, app/views/themes/scholarly_show/hyrax/base/show.html.erb, app/views/themes/scholarly_show/hyrax/oers/show.html.erb
We are now using Hyrax.config.analytics_reporting? instead.  The analytics_button partial is deprecated and all references removed.
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/177
=> 🧹 Remove Hyrax.config.analytics from the codebase

Gemfile, Gemfile.lock
Brings in fixes for resplitting a PDF & deleting the child works along with the parent work.
Uses released gem version
Refs https://github.com/notch8/palni_palci_knapsack/issues/80
=> Update IiifPrint Gem to v3.0.3

app/models/admin_set_resource.rb, spec/models/admin_set_resource_spec.rb
This commit will introduce two instance methods on the AdminSetResource:
- #member_of
- #member_collection_ids
These methods will make it possible for users to query for resources are on the given AdminSetResource.  This is particularly useful for the WillowSword gem.
Ref:
- https://github.com/notch8/palni-palci/issues/1071
=> Add member methods on AdminSetResource

app/assets/stylesheets/hyku.scss, app/assets/stylesheets/themes/cultural_repository.scss, app/assets/stylesheets/themes/institutional_repository.scss, app/assets/stylesheets/themes/neutral_repository.scss, app/views/_user_util_links.html.erb, app/views/catalog/_search_form.html.erb, app/views/hyrax/homepage/_explore_collections.html.erb, app/views/hyrax/homepage/_home_content.html.erb, app/views/shared/_footer.html.erb, app/views/themes/cultural_repository/_facets.html.erb, app/views/themes/cultural_repository/_masthead.html.erb, app/views/themes/cultural_repository/_user_util_links.html.erb, app/views/themes/cultural_repository/catalog/_search_form.html.erb, app/views/themes/cultural_repository/layouts/homepage.html.erb, app/views/themes/institutional_repository/_controls.html.erb, app/views/themes/institutional_repository/_logo.html.erb, app/views/themes/institutional_repository/_masthead.html.erb, app/views/themes/neutral_repository/_theme_container.html.erb, spec/features/institutional_repository_theme_spec.rb
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/142
Many of the themes needed styling clean ups and more streamlined transitions between screen sizes.
- Default Theme
- Spacing around the search bar in mobile view
- Cultural Theme
- Facet search in header will be more consistent across all viewports
- Setting the major breakpoint at 992 for header styles
- Institutional Theme
- Application name will be on the left side next to the logo with the search bar on the right
- In mobile view, the name will be centered and the search bar sits below, no need for a hamburger menu 
- Neutral Theme
- Home page body will adjust into a single column that takes up the full width of the browser in mobile view
- Footer
- The footer will drop into a single column in mobile view
<details> …
=> I142 home page themes

app/models/concerns/account_settings.rb, spec/models/concerns/account_settings_spec.rb
Disable Pitt feature that sends user stats and emails, until these feature bugs get fixed: 
:batch_email_notifications
:depositor_email_notifications
:user_analytics
The settings are no longer visible on the account form:
=> Pitt account settings follow up

app/models/solr_endpoint.rb
This commit will ensure that the adapter is set to solr.  There seems to be an error occuring when the worker is switching accounts where it loses the adapter and raises an error.
=> 🐛 Ensure solr adapter on account switch

app/helpers/hyku/blacklight_helper_behavior.rb
Issue: 
- https://github.com/notch8/palni_palci_knapsack/issues/199
This commit will remove a method that didn't seem to be working and instead use the #generate_work_url method instead.  This way it actually passes the UV search params.
=> 🐛 Add UV search params onto other gallery views

Gemfile.lock, app/assets/stylesheets/hyku.scss, app/assets/stylesheets/hyrax.scss, app/views/themes/cultural_show/hyrax/base/_work_title.html.erb, app/views/themes/image_show/hyrax/base/_work_title.html.erb, app/views/themes/scholarly_show/hyrax/base/_work_title.html.erb
be318f0e **Brings in fix for BatchCreateJob**
The BatchCreateJob was overwriting attributes, causing a retry to fail due to missing attributes. 
6868880f **Handles long titles in views**
Due to the way IiifPrint creates child works,  there were some very long titles which were all one word. These long titles can distort views by stretching containers. Normally this wouldn't be a major issue, but early IiifPrint child works that weren't fully split correctly did not have the attribute to prevent them from appearing in public views.
These CSS and/or html changes wrap long titles to avoid distortions.
<details>
<summary>Home page</summary>
</details>
<details>
<summary>Catalog page</summary>
</details>
<details>
<summary>Work show</summary>
</details>
<details>
<summary>Collection show  - …
=> Additional fixes based on issues found in Adventist

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, config/locales/blacklight.de.yml, config/locales/blacklight.en.yml, config/locales/blacklight.es.yml, config/locales/blacklight.fr.yml, config/locales/blacklight.it.yml, config/locales/blacklight.pt-BR.yml, config/locales/blacklight.zh.yml, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/hyrax.de.yml, config/locales/hyrax.es.yml, config/locales/hyrax.fr.yml, config/locales/hyrax.it.yml, config/locales/hyrax.pt-BR.yml, config/locales/hyrax.zh.yml, config/locales/it.yml, config/locales/pt-BR.yml, config/locales/zh.yml
This commit will remove the title property from the index show page because it already shows up in a different partial so it's redundant. Also, there were a few missing translations so those have been updated. It seemed that the translations were in two different spots so I consolidated them so it's easier to manage.  I've updated the other languages as well using the i18n Google translate task.
Before:
After:
=> 🧹 Remove title from index and update translations

app/assets/stylesheets/hyku.scss, app/forms/hyku/forms/admin/appearance.rb, app/views/shared/_appearance_styles.html.erb, config/locales/en.yml, config/locales/hyrax.en.yml
- Adds the ability to do more color customizations with the primary button.
- Removes some of the hint text that was redundant to reduce the size of the colors menu.
- Renames Default button to Secondary button on the colors menu for clarity.
- Adjusts CSS for the file button on items list so the text will stay within the box (previously for adventist it didn't due to larger fonts)
- The download button will now align with the rest of the row when logged out. 
<details>
</details>
=> Adds appearance color options

app/assets/javascripts/hyku/admin/appearance/colors.js, app/forms/hyku/forms/admin/appearance.rb, app/views/hyrax/admin/appearances/_default_colors_form.html.erb, config/home_themes.yml
Creates a simple way to define and set default colors for themes in the admin UI. 
The colors to override are defined by attaching them in the `home_themes.yml`. The button to set the colors to the default for the theme will only be displayed if the theme defines custom colors.
<details>
<summary>Video</summary>
[recorded (1).webm](https://github.com/user-attachments/assets/9ea4bc9c-b683-4d7b-85fb-98d3a1f60452)
</details>
=> Allow for theme color defaults

app/jobs/batch_email_notification_job.rb, spec/factories/mailboxer_messages.rb, spec/jobs/batch_email_notification_job_spec.rb, spec/rails_helper.rb
Ref:
- https://github.com/notch8/palni-palci/issues/1019
- Inconsistency in the batch email notifications vs what is seen in-app
- Failing feature specs due to database deadlocks in JavaScript-enabled feature
- Explicitly set batch emails to send all notifications that have the attributes `is_delivered: false` (has not been sent in a previous email) and `is_read: false` (has not been read in-app)
- Once an email is sent, the notifications are set to `is_delivered: true` and `is_read: true`
- Added additional specs to ensure batch email behavior is well defined
- All specs are passing
<details>
<summary>Image: Passing specs</summary>
</details>
=> I1019 batch email notifications

app/assets/stylesheets/themes/institutional_repository.scss, app/views/hyrax/homepage/_featured_collection_section.html.erb, app/views/themes/institutional_repository/hyrax/homepage/_resource_type_stats.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_explore_collections.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_featured_works.html.erb
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/240
<details>
<summary>Photo: Logged in user on neutral theme - misaligned sorting button and featured work card</summary>
</details>
<details>
<summary>Photo: Logged out user on neutral + cultural themes - featured collections were in a column, not a row</summary>
</details>
<details>
<summary>Photo: Logged in user on neutral theme - sorting button and featured work card are the same size</summary>
</details>
<details>
<summary>Photo: Logged out user on neutral + cultural themes - featured collections are a row and responsive</summary>
</details>
=> i240 home page layout on neutral and cultural theme

app/services/iiif_print/tenant_config.rb
This commit will add a fix for re-splitting PDFs, the problem was because of keyword arguments.
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/239
=> 🐛 Fix re-split for PDFs

app/assets/stylesheets/themes/neutral_repository.scss, app/views/themes/neutral_repository/_featured_carousel.html.erb
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/249
- Carousel container resized based on image dimensions causing page layout shifts
- Image transitions were jumpy
<details>
<summary>Video: Before changes</summary>
https://github.com/user-attachments/assets/b01089fb-3731-4e2e-9f31-d89a296b9da4
</details>
- Set container height and standard image size
- Smooth transition during carousel changes
<details>
<summary>Video: After changes</summary>
https://github.com/user-attachments/assets/eab06c76-c27f-4483-86ab-811ecd3c8c56
</details>
- adds a fixed height container (400px) to maintain consistent carousel size even when images have different dimensions
- adds object-fit and transition properties to prevent image stretching during slide transitions
- favors Bootstrap classes …
=> 🐛 Standardize carousel container dimensions

app/views/hyrax/homepage/_featured_collection_section.html.erb, app/views/themes/cultural_repository/hyrax/homepage/_featured_collection_section.html.erb, app/views/themes/institutional_repository/hyrax/homepage/_featured_collection_section.html.erb, app/views/themes/neutral_repository/hyrax/homepage/_featured_collection_section.html.erb, spec/views/hyrax/homepage/_featured_collection_section.html.erb_spec.rb, spec/views/themes/cultural_repository/_featured_collection_section.html.erb_spec.rb, spec/views/themes/institutional_repository/_featured_collection_section.html.erb_spec.rb, spec/views/themes/neutral_repository/_featured_collection_section.html.erb_spec.rb
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/240
The default theme's featured collection section on the logged out home page uses a table layout where all the other themes should use a grid layout but were rendering in a column.
All featured collection section on the logged out home page should follow the theme's desired structure.
<details>
<summary>Photo: Default theme featured collection section on the logged out home page</summary>
</details>
<details>
<summary>Photo: Cultural theme featured collection section on the logged out home page</summary>
</details>
<details>
<summary>Photo: Institutional theme featured collection section on the logged out home page</summary>
</details>
<details>
<summary>Photo: Neutral theme featured collection section on the logged out home …
=> I240 featured collections columns

app/models/account.rb, app/models/concerns/account_settings.rb, config/locales/simple_form.en.yml, spec/models/account_spec.rb, spec/models/concerns/account_settings_spec.rb, spec/services/create_account_spec.rb
Issue: 
- https://github.com/notch8/palni_palci_knapsack/issues/267
- removes user_analytics and rely on analytics_reporting instead.
- adds conditional to determine if jobs should be enqueued based on settings
- adds help text describing the settings
- adds specs
TODO: Add error handling to hyrax job
https://github.com/samvera/hyrax/issues/7029
=> rework user_analytics setting

app/controllers/hyrax/notifications_controller_decorator.rb, spec/controllers/hyrax/notifications_controller_spec.rb
Ref:
- https://github.com/notch8/palni-palci/issues/1019
- Notifications were only being marked as "read" if the user received a batch email with the notification
- If a user saw the email in the notification in the app dashboard the notification did not change status
- When a user visits the notification dashboard, all existing notifications will be marked "read"
- Read notifications are not included in the batch email
<details>
<summary>Photo: a user's unread notification</summary>
</details>
<details>
<summary>Photo: after visiting the notification dashboard, there are no more unread notifications</summary>
</details>
- Adds a decorator for the NotificationsController to mark notifications as read when the user visits the notification dashboard
- Ensures that the user will not receive …
=> 🎁 Marks Notifications as Read on Dashboard

config/metadata/with_video_embed.yaml
Viewer uses a different indexed term than the yaml specified. Changes video_embed_tesion to video_embed_tesim.
Fixes https://github.com/samvera/hyku/issues/2485
=> Fixes video embed viewer

.github/workflows/deploy.yaml
Update the deploy image to have /web to align with build and push of image with the new rework of the build actions.
Removes the extra setup-env steps that are unnecessary when using the notch8 actions setup-env block
Updated the version of setup-env we are using from the notch8 actions repo.
=> Get deploy action working again for repo

config/initializers/willow_sword.rb
This commit will change the default work model for WillowSword to `GenericWorkResource` explicitly.
=> ⚙️ Change default work model for WillowSword

app/models/concerns/account_settings.rb
This commit will add a conditional check to see if the analytics reporting checkbox in the settings is checked or not.
=> 🐛 Make analytics go away if it is not checked

.github/workflows/build-test-lint.yaml, docker-compose.yml
Add base multiarch push
When updating the base image, we need to build and push a multi-architecture image tagged with its SHA digest.
This allows us to pin a specific version to the hyku-knap-base image in Knapsack during application development, ensuring consistency across environments.
=> Add base multiarch push

app/services/hyrax/custom_queries/find_by_model_and_property_value.rb, config/initializers/wings.rb
This query had previously been defined in Bulkrax. Bulkrax needed a change to be able to find metadata without the model, but the original query is still needed in IiifPrint.
Ideally this should be defined in IiifPrint directly, but the current setup has the custom query for bulkrax being registered here. To avoid confusion, this query is being added to Hyku since it is registered in Hyku.
If we determine a better way to register custom queries in gems, this can be moved to IiifPrint.
refs: https://github.com/samvera/bulkrax/pull/1025
=> Add custom query for IiifPrint

lib/blacklight_advanced_search/advanced_query_parser_decorator.rb
Ref:
- https://github.com/notch8/hykuup_knapsack/issues/299
Override BlacklightAdvancedSearch v7.0.0 to ensure `@params` has indifferent access. This resolves a bug where field-specific queries (e.g. { title: "foo" }) weren't working because:
1. `@params` was a Hash
2. `@params[:search_field]` was being invoked while the expected value was in `@params['search_field']`
3. The advanced search logic was short-circuited in #keyword_queries because `@params[:search_field]` was nil
Reading the code in BlacklightAdvancedSearch, it's clear that `@params` is intended to have indifferent access. Strangely, advanced search worked as expected in development mode; `@params` was a ActiveSupport::HashWithIndifferentAccess in development mode as opposed to a Hash in production mode.
See …
=> Fix advanced search

app/helpers/application_helper.rb
Prior to this change, if you wanted to add record-specific locales for a class that has 1+ words in its name (e.g. `GenericWork`), you had to use the `downcase`d class name (e.g. `genericwork`). This PR aligns locale labels with the existing pattern in Hyku where lowercase class names are represented in snake case (e.g. `generic_work`). 
```yaml
hyrax:
genericwork:
my_label: Snake case best case
```
```yaml
hyrax:
generic_work:
my_label: Snake case best case
```
=> Favor snake case for class-based locale lookups

config/initializers/rack_attack.rb, ops/demo-deploy.tmpl.yaml, ops/staging-deploy.tmpl.yaml
The throttle limit previously had to be increased to 500 by default because each thumbnail a page loads counts as a request. Bots primarily scrape `/catalog` pages, so we're narrowing our focus to specifically throttle those requests more aggressively
=> Only throttle `/catalog` requests

app/models/solr_document.rb, app/presenters/hyku/work_show_presenter.rb, app/views/hyrax/base/_video_embed_viewer.html.erb
The root of the problem is that we changed `video_embed_tesim` to `video_embed_tesi` which makes sense since it's not a multiple field.
Ref:
- http://github.com/notch8/wvu_knapsack/issues/44
=> 🐛 Fix video_embed

Dockerfile
Whenever running tesseract with IIIF Print we were getting the error: `Error opening data file /usr/share/tesseract-ocr/5/tessdata/eng_best.traineddata`
This indicated that it was looking for the traineddata file in the wrong spot.  This commit will update the build to put it in the expected location.
Ref:
- https://github.com/notch8/hykuup_knapsack/issues/332
=> ⚙️ Update tessdata download location

Gemfile
fixes a regression in the 6.2.0.rc1 code merges
=> use the prebuilt binaries for google protobuf again

Gemfile.lock
- https://github.com/samvera/hyrax/commit/ec3ac86200a5b81dd4ef79405301a534d6d55e59
Fully upload should be 72.92MB (which is the size of the file), but it only partially uploaded. When saved the file is invalid.
=> bumps hyrax version for chunk upload fix

Gemfile, Gemfile.lock, app/models/hyrax/flexible_schema_decorator.rb, app/services/hyrax/core_metadata_validator.rb, app/services/hyrax/flexible_schema_validator_service.rb, config/metadata_profiles/m3_profile.yaml, db/schema.rb, lib/flexible/m3_json_schema.json, spec/fixtures/files/m3_profile.yaml, spec/services/hyrax/core_metadata_validator_spec.rb, spec/services/hyrax/flexible_schema_validator_service_spec.rb
Previously, invalid profiles could break the app because it would allow the user to save bad profiles. Users were unable to resolve the issues themselves. 
This validator is required for the hyku v6.2.0 release. 
- https://github.com/notch8/amigos/issues/29
Validation Rules include: 
We considered turning houndstooth into a gem, however we decided to hold off for now. There's a ticket to revisit this topic at a later date: 
- https://github.com/notch8/hykuup_knapsack/issues/409
- samvera community convo is happening [here](https://samvera.slack.com/archives/C0X9STKSP/p1752619285458939)
=> I29 m3 validator

app/models/concerns/account_settings.rb, app/views/hyrax/dashboard/_user_activity.html.erb
New tenants had analytics turned on by defaut when the global env variable was set. It should be set to false on a tenant level by default regardless if of the ENV var.
<details>
Error present in demo.hykudemo.org reproduced locally:
</details>
Additionally, when a tenant added configs that the site admin hasn't added as a service account to their Google Analytics, a Google::Cloud::PermissionDeniedError would break the site. This override will gracefully handle it by displaying an error on the dashboard.
=> :bug: rescue google permission denied error

app/controllers/admin/work_types_controller.rb, app/services/hyrax/flexible_schema_validator_service.rb, app/services/hyrax/quick_classification_query_decorator.rb, app/views/admin/work_types/edit.html.erb, spec/services/hyrax/flexible_schema_validator_service_spec.rb
Issue: 
- https://github.com/notch8/hykuup_knapsack/issues/429
This will prevent users from being able to create works from work types that haven't been defined in their metadata profiles, when Hyrax.config.flexible? is true
Previously, users could upload a profile without defining the class then enable that work type in "available work types". If the user then tried to create a work error (because it wasn't defined in the profile). 
[m3_profile.yaml.zip](https://github.com/user-attachments/files/21418324/m3_profile.yaml.zip)
=> I429 profile defines available work types

app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb, config/application.rb, spec/config/application_spec.rb
Hyrax changed the way derivatives are retrieved for audio and video resources which was not compatible with the way Hyku generates IIIF manifest urls.  This commit will simplify the code by using one av url generator instead of separate ones for audio and video and pass the mime_type in.
Ref
- https://github.com/notch8/hykuup_knapsack/issues/389
- https://github.com/samvera/hyrax/pull/6297
=> 🐛 A/V was not loading correctly

app/factories/bulkrax/object_factory_interface_decorator.rb
I thought about putting this in bulkrax directly, however I don't think it should know about the concept of flexible metadata in Hyrax. 
When a user includes a work type that is either not in their metadata profile, or it is but it's not enabled, Bulkrax will report a more helpful error than a NoMethodError. 
Upload a profile that doesn't have GenericWorkResource defined.
Import this zip with bulkrax's csv parser
[Archive(1).zip](https://github.com/user-attachments/files/21436270/Archive.1.zip)
<details>
</details>
<details> 
</details>
=> Handles error gracefully when worktype isn't configured

Gemfile.lock
pulls in 'make _citations partial more flexible'
ref:
- https://github.com/samvera/hyrax/commit/a3118683116df6d85a6d0657d87301525cbee91a
st-jude was failing because their description property must've been a string when this partial expects it to be an array. This broke the app and the user is blocked from fixing it. 
This should resolve the error: 
```
I, [2025-07-30T20:52:16.284285 #8]  INFO -- : [0f70a9542cb4f447dc753a5b6dfef58e] Completed 500 Internal Server Error in 1651ms (ActiveRecord: 233.2ms | Allocations: 635092)
D, [2025-07-30T20:52:16.287502 #8] DEBUG -- : [0f70a9542cb4f447dc753a5b6dfef58e]   Account Load (0.8ms)  SELECT "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."tenant" = $1 LIMIT $2  [["tenant", "public"], ["LIMIT", 1]]
F, …
```
=> Updates hyrax

app/services/hyrax/flexible_schema_validator_service.rb, app/services/hyrax/flexible_schema_validators/class_validator.rb, app/services/hyrax/flexible_schema_validators/schema_validator.rb, spec/services/hyrax/flexible_schema_validator_service_spec.rb
Start with Hyku's default profile.
Create ImageResource works then try uploading the following profile
[no-image.yaml.zip](https://github.com/user-attachments/files/21454859/no-image.yaml.zip)
=> 🎁 Prevents removal of classes that have already-persisted records

app/services/sample/active_fedora_service.rb, app/services/sample/valkyrie_service.rb, lib/tasks/sample_seeds.rake
- Adds bulkrax identifier to sample seeds.
- Adjust title of admin set to clearly identify it as coming from the seeds. The ActiveFedora admin set is not able to be migrated or edited at the current time. The cause is unknown but does not affect using the remainder of the data.
Additional testing of the resulting data is recommended to enhance the sample seeding services.
=> Fix sample seeds

Gemfile.lock
Active Fedora only => Valkryie forms would only render the title when other metadata is available to display.
This required rework because I forgot to apply the same implementation to the collections controller. Note: FileSets only rendered the title before this anyways so is less of an issue/concern - but I applied the code there as well for consistency's sake. 
Issue:
- https://github.com/notch8/hykuup_knapsack/issues/461#issuecomment-3214458421
ref: https://github.com/samvera/hyku/pull/2677
=> [i461] - Rework fix for collection forms

config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/hyrax.de.yml, config/locales/hyrax.es.yml, config/locales/hyrax.fr.yml, config/locales/hyrax.it.yml, config/locales/hyrax.pt-BR.yml, config/locales/hyrax.zh.yml, config/locales/it.yml, config/locales/pt-BR.yml, config/locales/zh.yml
This commit will add the translation for
`hyku.admin.groups.humanized_name.group/admin` and `en.hyku.admin.groups.humanized_name.group/work_editor` and run the I18n task to translate them.
Fixes #2542
=> Add missing translations

app/forms/collection_resource_form.rb, app/search_builders/adv_search_builder.rb, app/views/hyrax/dashboard/collections/_form_discovery.html.erb, config/locales/hyrax.en.yml, config/metadata/collection_resource.yaml, config/metadata_profiles/m3_profile.yaml, spec/forms/collection_resource_form_spec.rb, spec/indexers/collection_resource_indexer_spec.rb, spec/models/collection_resource_spec.rb, spec/search_builders/adv_search_builder_spec.rb
This adds the ability to exclude a collection from the catalog search results. A checkbox to `Hide from catalog search` is added to the `Discovery` tab of the collection edit form. Checking the box will set the `hide_from_catalog_search` attribute on the CollectionResource to true which will filter it from the search results.
The `hide_from_catalog_search` attribute will be required in the flexible metadata profile if flexible is enabled.
Ref:
- https://github.com/notch8/adventist_knapsack/issues/892
=> 🎁 i892 exclude collections from catalog search

config/metadata/collection_resource.yaml, config/metadata_profiles/m3_profile.yaml
Remove the `Hide from catalog search` from create/edit form with metadata fields. Ensure it only appears as a checkbox on the collection edit branding tab for both flexible=true and flexible=false
Ref:
- https://github.com/notch8/adventist_knapsack/issues/892
=> 🐛 Remove `Hide from catalog search` from metadata

app/helpers/hyrax/form_helper_behavior.rb, app/models/concerns/account_settings.rb
Prevents error when discogs set up isn't complete: 
User would see the app crash when creating a new work
App no longer crashes
=> Controlled vocab follow up

config/initializers/hyrax.rb
Handles multiple authority location branches, which allows a knapsack to set a branch with authority files to overwrite the content in any of hyku's authority files.
=> Update authorities to load multiple paths

Gemfile.lock
Version bump:
This commit updates the version of Hyrax 5.0-flexible that prevents admin users from enabling batch_upload in settings.
This addresses the issue that batch uploads and Valkyrized works are incompatible. The current Batch Add uses a fake Active Fedora form with fixed terms that ignore the selected work type, causing Valkyrie validations to fail (especially on 6.2).
It was determined that fixing this issue is low-priority compared to general Bulkrax improvements. To ensure users are not enabling broken features, batch_upload is disabled until further decisions are made.
Ref:
- notch8/palni_palci_knapsack#479
=> ⚙️ Temporarily disable batch_upload feature

app/services/hyrax/quick_classification_query_decorator.rb, spec/services/hyrax/quick_classification_query_decorator_spec.rb
Fixes #2728 
Simple check in the decorator to address issues in ticket https://github.com/samvera/hyku/issues/2728
Addition of return to filtered_available_works "      return available_works if Site.account&.search_only?"
Updated spec tests.
=> Fix search tenant flexble metadata

app/helpers/blacklight/catalog_helper_behavior_decorator.rb, app/indexers/concerns/hyku_indexing.rb
Sometimes the `document` is actually a presenter, so if it responds to `#solr_document` then we should get the SolrDocument.  If it doesn't then we use the SolrDocument that is passed in.
=> 🐛 Fix FileSet show page from breaking

app/helpers/hyrax/form_helper_behavior.rb, config/initializers/hyrax_controlled_vocabularies.rb, spec/helpers/hyrax/form_helper_behavior_spec.rb, spec/services/controlled_vocabularies_spec.rb
This commit converts the controlled_vocab_mappings hash to a method in the ControlledVocabularies initializer to allow for custom controlled vocab overrides as well as converts the SERVICES and REMOTE_AUTHORITIES consts to methods to follow better OOP practices.
Ref:
- https://github.com/notch8/hykuup_knapsack/issues/531
=> 🐛 Move controlled_vocab_mappings to initializers

app/views/hyrax/dashboard/collections/_form_discovery.html.erb
Prevents the application from crashing when creating a new collection, if the hide_from_catalog_search attribute is not defined in the metadata schema.
Issue:
- https://github.com/notch8/palni_palci_knapsack/issues/490
=> :bug: [i490] Adds guard to display hide_from_catalog_search checkbox
